### ISSUE TITLE
Mine blocks and furnace bug Minecraft 1.12.2

### ISSUE THREAD

**Issue by MobadMG** [Geforce132/SecurityCraft#105]
Hi, I installed Security Craft 1.8.16 for minecraft 1.12.2 in my server and also in my client minecraft, so I was testing the mines, the mines blocks and the mine furnace and the block didn't  explode when I stood over them and the furnace didn't explode when I right clicked on it, both only explode when you break it. Also if you stand on them you sink.

EDIT: I decided to download the before update and it works perfect.

![2020-02-05_01 18 12](https://user-images.githubusercontent.com/33408754/73819662-a5879400-47b5-11ea-8a62-3ea4edab0260.png)
![2020-02-05_01 18 18](https://user-images.githubusercontent.com/33408754/73819665-a7515780-47b5-11ea-8a1c-e92abcd3eafe.png)

**Comment by bl4ckscor3** [comment]
Read the changelog of v1.8.16:
`- Fix: Various mines do not ignore their owner`
This is intended.
