### ISSUE TITLE
Player logger is a bit...Messy

### ISSUE THREAD

**Issue by STOKE-STER** [Geforce132/SecurityCraft#108]
Currently when the player logger logs a person frequently in and out of their base it looks like this:

![2020-02-13_22 21 05](https://user-images.githubusercontent.com/36657224/74437386-c0dc5880-4eb3-11ea-8270-1522a3e7c7a2.png)

I spent some time in paint.net designing something that I feel would look a lot better (The scrollbar is a direct rip from refined storage but it's just so you get the idea):
![gui](https://user-images.githubusercontent.com/36657224/74437511-f5e8ab00-4eb3-11ea-8635-772bc8f4f05d.png)

This would give us a way to scroll down and see a log of players coming and going as WELL as what time (would work off server time and date). This would help us in a few ways like finding out who raided a base, which person with access to a base let in someone unauthorized etc.

Would probably also suggest a way to sort the log by name, time/date and ascending or descending.
Maybe even hovering over a name could show their uuid as a tooltip?
Just some thoughts :)

**Comment by bl4ckscor3** [comment]
I already implemented a scrollable list, however showing the time/UUID is a good idea.

**Comment by bl4ckscor3** [comment]
https://cdn.discordapp.com/attachments/318543441757995008/678575437408108548/2020-02-16_13-15-03.mp4

**Comment by STOKE-STER** [comment]
That looks 10x better gg
