### ISSUE TITLE
Cant craft reinforced stuff!

### ISSUE THREAD

**Issue by SugarDaddii** [Geforce132/SecurityCraft#11]
Hey i have a problem whenever i try to make reinforced stuff i cant craft them!
Is that a bug?
Pls help me!

http://abload.de/image.php?img=uncraftablestkaj.jpg
http://abload.de/image.php?img=uncraftable1s3s3f.jpg

**Comment by Geforce132** [comment]
If you're using SecurityCraft v1.8.0, the one with the cameras, you don't need to "craft" reinforced blocks anymore, simply mine (left-click while not in Creative mode) the block you want to reinforce with one of the Universal Block Reinforcers. :)

**Comment by bl4ckscor3** [comment]
Since this is not a bug and it's easily "fixable", i'll close this.
