### ISSUE TITLE
[1.15.2] Sack of Holding can pick up reinforced blocks

### ISSUE THREAD

**Issue by Quu1337** [Geforce132/SecurityCraft#114]
Cyclic Sack of Holding can pick up reinforced blocks, making reinforcing blocks bit useless.
Is it possible to disable that, or is it do i just need to wait for cyclic to hopefully fix it?

1.15.2
forge 31.1.14
securitycraft 1.8.16

https://github.com/Lothrazar/Cyclic/issues/1321

**Comment by bl4ckscor3** [comment]
I would assume that the Cyclic dev needs to fix it on his end. What does the sack of holding do?

**Comment by Quu1337** [comment]
Not 100% sure (havent checked the code, not good enough to do it anyways) but i think it can pick up ANY block/entity with NBT-tags. cant pick vanilla blocks, but can chests and furnaces and stuff.

Allows you to pick up eg. reinforced oak planks, gives you Sack of Holding with "reinforced oak planks" "enchant" or whatever, and allows you to place them anywhere you want.

Sorry, really bad at explaining stuff i dont understand fully.

**Comment by bl4ckscor3** [comment]
You explained it well enough for me to understand what it does. I'll take a look at what I can do.

**Comment by Lothrazar** [comment]
Hey dev of cyclic here.

Should i check if its "unbreakable", or whats the best way to check "Can player harvest this"

**Comment by bl4ckscor3** [comment]
`if(tileEntity instanceof IOwnable && !((IOwnable)tileEntity).getOwner().isOwner(playerWhoTriesToUse))`

IOwnable is an interface that all our tile entities implement which defines that a tile entity is ownable. More info here: https://github.com/Geforce132/SecurityCraft/blob/1.15.x/src/main/java/net/geforcemods/securitycraft/api/IOwnable.java
