### ISSUE TITLE
Crash Opening the guide

### ISSUE THREAD

**Issue by SoyJetixXD** [Geforce132/SecurityCraft#116]
Information:I added the latest version of the mod to my modpack, and when I tried it I opened the guide and the game crashed.
![Captura de pantalla (2)](https://user-images.githubusercontent.com/60457424/76674290-a6ad9d00-657b-11ea-995c-5726584be860.png)
Link:https://paste.dimdev.org/udikecogaw.mccrash

**Comment by RedstoneDubstep** [comment]
With me the SecurityCraft Manual worked well in 1.12.2 (and I hoped you meant it with "Guide"), so could you please send the list of the mods you used? Also, could you please describe a bit more how and when the crash occured (opening the manual, clicking on one of the arrows, hovering over the middle bar, etc.)?

**Comment by bl4ckscor3** [comment]
@RedstoneDubstep He is using the Spanish language. 
@SoyJetixXD Fixed in da35577136f776597396f2dc4ab3b951a7f626b3 which means the fix will be released with v1.8.18. Thanks for reporting!
