### ISSUE TITLE
Crash when making cobble with fake water and fake lava

### ISSUE THREAD

**Issue by Rhinorulz** [Geforce132/SecurityCraft#12]
Server crash (from the SSP client server) http://paste.ee/p/2z208
Client log http://paste.ee/p/bL2iZ
Forge log http://paste.ee/p/1xPu0

**Comment by bl4ckscor3** [comment]
I marked this as a bug since this is clearly unintended. I will look into this issue in more detail.

**Comment by Rhinorulz** [comment]
nope.  Was testing things out in creative, and the buckets were the first thing down.  no other blocks from this mod were active in the chunks

**Comment by bl4ckscor3** [comment]
That is weird, because the crashlog references the TileEntity of a SecurityCamera as the issue.

**Comment by Rhinorulz** [comment]
That is indeed really weird.  I'll load up the world again to make sure, but i'm 99.99% sure that the only  craft things that had been placed were the fake water/lava.  will edit this soon if i can.

**Comment by Raqbit** [comment]
I was looking at this issue, and the pastes  have expired. @Rhinorulz can you repost or reproduce?

**Comment by bl4ckscor3** [comment]
I cannot reproduce this. As Raqbit said, your pastes are expired. Unless you can provide new crash-reports, I will close this.
