### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by RayHsueh** [Geforce132/SecurityCraft#122]
What can I do to help you translate? I am not very good at operating this site, sorry. I want to help you translate traditional Chinese. Can you teach me?

**Comment by bl4ckscor3** [comment]
First of all: This issue tracker is not for questions about how to do something, but to report bugs or request new features. 

Fork this project. Make sure that you are on branch 1.15.x. Go to `assets/securitycraft/lang/` and create a new file for Chinese. Copy the contents of `en_us.json` into it and translate. Make sure that you keep the translations for the reinforced blocks as close to the vanilla translations as possible. Save the file and create a new pull request. If you don't know how to do some of these things, please use the GitHub FAQ or a tutorial on git.
