### ISSUE TITLE
 Placing and using objects is heard by all server users

### ISSUE THREAD

**Issue by belterrwan** [Geforce132/SecurityCraft#125]
When using the taser, placing the Key Panel and placing the electrified iron fence, a specific sound is generated, this sound is heard by all users who are online on the server

I think it is a serious problem since it becomes annoying after a few hours playing and constantly listening to these sounds.

**Comment by RedstoneDubstep** [comment]
Hi, thanks for reporting that bug. I'm not a developer (just for clarification), but I want to test the bug out myself, and I want to ask what Minecraft and SecurityCraft version you are using.

**Comment by bl4ckscor3** [comment]
We have fixed something regarding this in v1.8.17. Please try out this version and report back if the issue still happens. If so, please provide a video that shows this problem, as I cannot reproduce it.

**Comment by belterrwan** [comment]
I am using minecraft forge 1.12.2 14.23.5.2847, and the version of securitycraft is v1.8.17
so yes, the problem persists, in fact in old versions it did not happen to me, until I update

**Comment by bl4ckscor3** [comment]
Ok, I will look at this again. For the future: When creating bug reports, ALWAYS include the versions of the software that you're using. I was testing in 1.15.2.
