### ISSUE TITLE
whenever i open the suitcase my game crashes

### ISSUE THREAD

**Issue by zineroyal** [Geforce132/SecurityCraft#126]
I have items that are important in there too
heres the error message

<details>
<summary>Details</summary>

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/9/20 11:29 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 27, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(Unknown Source)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(Unknown Source)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityClientPlayerMP['ZombiesNinja'/50, l='MpServer', x=673.76, y=65.62, z=-770.23]]
Chunk stats: MultiplayerChunkCache: 289, 289
Level seed: 0
Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
Level generator options: 
Level spawn location: World: (656,64,-120), Chunk: (at 0,4,8 in 41,-8; contains blocks 656,0,-128 to 671,255,-113), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
Level time: 165611 game time, 194036 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 62 total; [EntityTrail['unknown'/645, l='MpServer', x=673.76, y=65.62, z=-770.23], EntityCreeper['Creeper'/3079, l='MpServer', x=692.50, y=46.00, z=-789.50], EntityHuman['Searge'/3080, l='MpServer', x=687.75, y=45.00, z=-791.19], EntityHuman['Jessassin'/3081, l='MpServer', x=693.50, y=46.00, z=-790.50], EntitySpider['Spider'/3214, l='MpServer', x=649.50, y=22.00, z=-701.50], EntitySpider['Spider'/2961, l='MpServer', x=630.50, y=13.00, z=-738.50], EntityHuman['Talonos'/151, l='MpServer', x=801.50, y=75.00, z=-790.50], EntityZombie['Zombie'/3355, l='MpServer', x=695.50, y=31.00, z=-833.50], EntityZombie['Zombie'/3356, l='MpServer', x=693.50, y=31.00, z=-833.50], EntityGaiaYeti['Yeti'/159, l='MpServer', x=638.50, y=70.00, z=-717.50], EntityChunin['Chunin'/3368, l='MpServer', x=641.50, y=15.00, z=-764.50], EntityClientPlayerMP['ZombiesNinja'/50, l='MpServer', x=673.76, y=65.62, z=-770.23], EntityBattleshipHime['Battleship Princess'/52, l='MpServer', x=658.66, y=64.00, z=-768.00], EntityNorthernHime['Northern Princess'/53, l='MpServer', x=663.88, y=65.00, z=-773.31], EntityAirfieldHime['Airfield Princess'/54, l='MpServer', x=656.47, y=64.56, z=-769.00], EntityHuman['xBCrafted'/56, l='MpServer', x=665.16, y=64.00, z=-766.38], EntityHuman['kappe'/57, l='MpServer', x=674.50, y=13.00, z=-795.50], EntityItem['item.item.shincolle:Grudge'/3897, l='MpServer', x=654.00, y=64.13, z=-759.25], EntityCarrierWo['Standard Carrier Wo-Class'/58, l='MpServer', x=663.38, y=64.00, z=-767.63], EntityZombie['Zombie'/59, l='MpServer', x=650.88, y=64.00, z=-791.38], EntitySkeleton['Skeleton'/60, l='MpServer', x=700.16, y=64.00, z=-753.16], EntityCarrierWo['Standard Carrier Wo-Class'/61, l='MpServer', x=655.50, y=64.00, z=-774.06], EntityHarbourHime['Harbour Princess'/62, l='MpServer', x=648.50, y=64.00, z=-772.69], EntityCarrierHime['Aircraft Carrier Princess'/63, l='MpServer', x=652.63, y=64.00, z=-773.44], EntityDestroyerAkatsuki['Destroyer Akatsuki'/64, l='MpServer', x=652.13, y=64.00, z=-769.88], EntitySkeleton['Skeleton'/3393, l='MpServer', x=648.50, y=12.00, z=-705.50], EntityHuman['KingLemming'/66, l='MpServer', x=707.34, y=52.00, z=-792.66], EntitySkeleton['Skeleton'/3394, l='MpServer', x=648.50, y=12.00, z=-704.50], EntityCreeper['Creeper'/69, l='MpServer', x=665.50, y=57.00, z=-728.50], EntityWitch['Witch'/70, l='MpServer', x=662.50, y=57.00, z=-727.50], EntityHuman['Mhykol'/3398, l='MpServer', x=677.50, y=40.00, z=-892.50], EntityWitch['Witch'/71, l='MpServer', x=664.50, y=57.00, z=-730.50], EntityHuman['Eloraam'/3399, l='MpServer', x=677.50, y=40.00, z=-891.50], EntityBat['Bat'/3273, l='MpServer', x=674.03, y=32.95, z=-727.44], EntityGaiaEnderEye['Ender Eye'/75, l='MpServer', x=649.91, y=48.00, z=-734.59], EntityEnderman['Enderman'/76, l='MpServer', x=723.50, y=30.00, z=-736.84], EntityHuman['ChimneySwift'/77, l='MpServer', x=724.63, y=30.00, z=-736.47], EntityZombie['Zombie'/80, l='MpServer', x=716.91, y=12.00, z=-723.44], EntityGaiaFleshLich['Flesh Lich'/81, l='MpServer', x=682.69, y=14.00, z=-719.22], EntityGaiaEnderEye['Ender Eye'/82, l='MpServer', x=670.91, y=48.00, z=-713.41], EntityGaiaEnderEye['Ender Eye'/83, l='MpServer', x=671.69, y=48.00, z=-711.72], EntitySkeleton['Skeleton'/85, l='MpServer', x=621.50, y=17.00, z=-759.50], EntitySquid['Squid'/2133, l='MpServer', x=725.50, y=60.22, z=-749.16], EntitySquid['Squid'/2134, l='MpServer', x=723.69, y=59.06, z=-755.78], EntityZombie['Zombie'/87, l='MpServer', x=724.09, y=12.00, z=-720.72], EntitySquid['Squid'/2135, l='MpServer', x=722.06, y=60.34, z=-751.50], EntitySpider['Spider'/88, l='MpServer', x=653.50, y=44.00, z=-719.44], EntitySquid['Squid'/2136, l='MpServer', x=730.50, y=59.00, z=-751.53], EntitySquid['Squid'/2137, l='MpServer', x=722.50, y=59.00, z=-752.06], EntitySquid['Squid'/90, l='MpServer', x=706.84, y=56.34, z=-716.22], EntitySquid['Squid'/2138, l='MpServer', x=724.47, y=60.31, z=-746.44], EntitySquid['Squid'/91, l='MpServer', x=709.16, y=60.31, z=-715.66], EntitySquid['Squid'/2139, l='MpServer', x=729.69, y=60.38, z=-744.88], EntityBat['Bat'/3299, l='MpServer', x=615.47, y=26.00, z=-812.05], EntitySkeleton['Skeleton'/101, l='MpServer', x=729.50, y=44.00, z=-704.50], EntitySkeleton['Skeleton'/102, l='MpServer', x=656.91, y=22.00, z=-694.53], EntityCreeper['Creeper'/105, l='MpServer', x=593.50, y=15.00, z=-809.50], EntityHuman['JSano19'/110, l='MpServer', x=574.56, y=16.00, z=-768.72], EntityBat['Bat'/3310, l='MpServer', x=689.84, y=42.57, z=-799.69], EntityHuman['wyld'/112, l='MpServer', x=683.50, y=50.00, z=-675.50], EntitySkeleton['Skeleton'/2931, l='MpServer', x=658.50, y=22.00, z=-698.50], EntityHuman['WayofFlowingTime'/3069, l='MpServer', x=572.97, y=20.00, z=-777.47]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1196859536 bytes (1141 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 102
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 74 mods loaded, 74 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAAmcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAAAAFML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHIJAAAAForge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHIJAAAACodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
UCHIJAAAAImmibisMicroblocks{59.1.0} [Immibis's Microblocks] (immibis-microblocks-59.1.0.jar) 
UCHIJAAAAivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
UCHIJAAAALambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
UCHIJAAAANotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
UCHIJAAAAOpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
UCHIJAAAAbattlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
UCHIJAAAAsecuritycraft{v1.8.13} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.13.jar) 
UCHIJAAAADamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
UCHIJAAAALambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
UCHIJAAAAacademy-craft{1.0.7} [Academy Craft] (AcademyCraft-1.0.7.jar) 
UCHIJAAAAforgeendertech{1.7.10-1.9.2.0} [Forge Endertech] (ForgeEndertech-1.7.10-1.9.2.0-build.0061.jar) 
UCHIJAAAAadhooks{1.7.10-2.1.1.0} [Advanced Hook Launchers] (AdHooks-1.7.10-2.1.1.0-build.0061.jar) 
UCHIJAAAAaiimprovements{0.0.1.19} [AI Improvements] (AIImprovements-1.7.10-0.0.1b19-dev.jar) 
UCHIJAAAAarmourersWorkshop{1.7.10-0.48.3} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.48.3.jar) 
UCHIJAAAAFLabsBF{4.3} [Better Furnaces] (Better-Furnaces-Mod-1.7.10.jar) 
UCHIJAAAAbetterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
UCHIJAAAABiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
UCHIJAAAABaubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
UCHIJAAAAThaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
UCHIJAAAARailcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
UCHIJAAAAchisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
UCHIJAAAACarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's+Blocks+v3.3.8.2+-+MC+1.7.10.jar) 
UCHIJAAAAChunkAnimator{@VERSION@} [Chunk Animator] (ChunkAnimator-MC1.7.10-1.0.1.jar) 
UCHIJAAAAcosmeticarmorreworked{1.7.10-v6b} [CosmeticArmorReworked] (CosmeticArmorReworked-1.7.10-v6b.jar) 
UCHIJAAAAcustomnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
UCHIJAAAADisenchanterMod{1.6} [Disenchanter] (DisenchanterMod-[1.7.10]1.6.jar) 
UCHIJAAAAfairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
UCHIJAAAAGardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
UCHIJAAAAGardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
UCHIJAAAAGardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
UCHIJAAAAGardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
UCHIJAAAAGrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
UCHIJAAAAhammertime{Hammer Time-1.7.10-1.3.6} [Hammer Time!] (HammerTime-1.3.6.jar) 
UCHIJAAAAheadcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-1.7.4.jar) 
UCHIJAAAAhidenames{1.1.7} [Hide Names] (Hide Names-1.7.10-1.1.8.jar) 
UCHIJAAAAiChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
UCHIJAAAAImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
UCHIJAAAAImmibisCore{59.1.1} [Immibis Core] (immibis-core-59.1.1.jar) 
UCHIJAAAAInfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
UCHIJAAAAInventoryPets{1.5.2} [Inventory Pets] (inventorypets-1.7.10-1.5.2-universal.jar) 
UCHIJAAAAironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (IronBackpacks-1.7.10-1.2.20.jar) 
UCHIJAAAAIronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
UCHIJAAAAjourneymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
UCHIJAAAAlogin_shield{1.7.10-2-gf6e21a7} [Login Shield] (Login_Shield-1.7.10-2-gf6e21a7.jar) 
UCHIJAAAARadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
UCHIJAAAAMCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
UCHIJAAAAMorpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
UCHIJAAAAcfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
UCHIJAAAAAM{1.0.0} [Naruto Mod] (Naruto-Anime-Mod_V0.9.17_Beta_1.7.10-1.0(10).jar) 
UCHIJAAAAndm{1.0} [Naruto Dojutsu Mod] (NarutoDojutsuMod2.jar) 
UCHIJAAAANBTEdit{1.7.2.2} [In-game NBTEdit] (NBTEdit_1.7.10.jar) 
UCHIJAAAAnetherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.0.jar) 
UCHIJAAAArecipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
UCHIJAAAAOpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
UCHIJAAAAOpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
UCHIJAAAAplaceableitems{2.0.1} [Placeable Items Mod] (placeableitems-2.0.1.jar) 
UCHIJAAAApotioncore{@VERSION@} [Potion Core] (PotionCore-1.2_beta_for_1.7.10.jar) 
UCHIJAAAARandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
UCHIJAAAAropebridge{1.1} [Rope Bridge] (RopeBridge-v1.2-mc1.7.10.jar) 
UCHIJAAAAsecretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
UCHIJAAAAshincolle{1.7.10.rv26.2} [Shinkeiseikan Collection] (ShinColle-1.7.10.rv26.2.jar) 
UCHIJAAAAtcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
UCHIJAAAATravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
UCHIJAAAAtumbleweed{1.7.10-0.2} [Tumbleweed] (tumbleweed-1.7.10-0.2.jar) 
UCHIJAAAAWaila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
UCHIJAAAAWailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
UCHIJAAAAwaystones{1.0.12} [Waystones] (Waystones-mc1.7.10-1.0.12.jar) 
UCHIJAAAAworldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
UCHIJAAAAxprings{1.3.0} [Experience Rings] (xprings-1.7.10-1.3.0.jar) 
UCHIJAAAAyarr_cutemobmodels{1.0.9} [Cute Mob Models] (yarrcutemobmodels-1.0.9-1.7.10.jar) 
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13560 Compatibility Profile Context 26.20.11026.12' Renderer: 'AMD Radeon(TM) RX Vega 10 Graphics'
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@6ea39581) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@15706bf7) returned non-null result: 0
Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
Stencil buffer state: Function set: GL30, pool: internal, bits: 8
Armourer's Workshop: 
Render Type: MODEL_ATTACHMENT
Texture Render: false
Baking Queue: 0
Request Queue: 0
Texture Painting: true
Multipass Skin Rendering: true
Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
LWJGL: 2.9.1
OpenGL: AMD Radeon(TM) RX Vega 10 Graphics GL version 4.6.13560 Compatibility Profile Context 26.20.11026.12, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

</details>

**Comment by bl4ckscor3** [comment]
We no longer support SecurityCraft for Minecraft 1.7.10. Please update to at least 1.12.2 to receive support.
