### ISSUE TITLE
Game Crash after active Cameramonitor 

### ISSUE THREAD

**Issue by SugarDaddii** [Geforce132/SecurityCraft#13]
Like topic!

Two different crashlogs!
http://paste.ee/p/3NaSm
http://paste.ee/p/EiXL7

**Comment by Geforce132** [comment]
Hmmm, those don't seem to be related to SecurityCraft. They seem to be coming from Botania and Immersive Integration. Hey @Vazkii and @UnwrittenFun, could you check those crashlogs out for me, please?

**Comment by Vazkii** [comment]
Fixed mine with https://github.com/Vazkii/Botania/commit/69ed66aca0182462dad1cbc756c0a391754aa2af

The fact that it even was placed with wrong metadata to begin with is very iffy though.

**Comment by SugarDaddii** [comment]
What can i do now??
