### ISSUE TITLE
Request: Add option to disable mines entirely

### ISSUE THREAD

**Issue by SauROnmiKE** [Geforce132/SecurityCraft#130]
Hello there,

I am running a small server with about 25 people and I really like the security options this mod gives, but only that. I'd like to request if it will ever be possible to add an option to configure whether we want all the mines to be craftable or even enabled at all and not use a plugin or another way to do so, as it's very easy for players to spam them. Thank you for your time!

Stay safe,
Michael

**Comment by bl4ckscor3** [comment]
I'll add a configuration option to disable all mine recipes.
