### ISSUE TITLE
Mines

### ISSUE THREAD

**Issue by Luis0411** [Geforce132/SecurityCraft#131]
Hello, I wanted to know how I can activate the option to see with the universal block remove the name of the person who put the mine on a public server

**Comment by bl4ckscor3** [comment]
1. This isn't a place to ask for help, but to report issues. If you need help, please use the #help channel in [our discord](https://discord.gg/U8DvBAW) server.
2. There's no specific option to do that. However if you are an admin, you can enable the admin tool in the configuration file and (sneak-)rightclick the mine to find out who it belongs to.
