### ISSUE TITLE
Can't see players on cameras

### ISSUE THREAD

**Issue by nikolas223idk** [Geforce132/SecurityCraft#132]
I don't know if this is something normal without a fix but i can't see my friend on security cameras.If you could it would be great for Fnaf or horror games.Thanks

**Comment by bl4ckscor3** [comment]
What Minecraft and SecurityCraft versions are you using?

**Comment by nikolas223idk** [comment]
securitycraft 1.8.11 and minecraft 1.12.2

**Comment by bl4ckscor3** [comment]
Update the mod and test again. If the issue persists, feel free to reopen this issue.
