### ISSUE TITLE
Add More Config Option

### ISSUE THREAD

**Issue by anar4732** [Geforce132/SecurityCraft#14]
Add More Config Option

 * B:"explodes damage blocks?"=true
 * I:"Limited Use keycard How many times used"=5

* B:"Allow Password Furnace"=true
* B:"Allow Password Chest"=true
* B:"Allow Alarm"=true
* B:"Allow (Other Blocks and items)"...

------------------------------------

Add More Block

* Camera Monitor Block

------------------------------------
Bug

* Security Camera Not Work Emit Redstone

**Comment by bl4ckscor3** [comment]
1. There is a camera monitor block (rightclick a Frame with a Camera Monitor)
2. Do you have the Redstone Module installed in the camera?
3. I see why we would need the damage and limited use keycard options, but why would we want to disallow blocks?

**Comment by anar4732** [comment]
* There is a camera monitor block : Thanks, I did not know it

* Do you have the Redstone Module installed in the camera? : Yes, I am sure

* I see why we would need the damage and limited use keycard options, but why would we want to disallow blocks? : For a adventure map

**Comment by Geforce132** [comment]
But if you're adding SecurityCraft to your modpack, wouldn't you want the player to be able to use all the blocks/items in the mod? xD

**Comment by anar4732** [comment]
@Geforce132 

just a mod pack for adventure maps

in this mode the alarm is insufficient
to use another mod for Alarm

-----------------------------

update, when will you?

**Comment by bl4ckscor3** [comment]
If we add config options for everything the config gets far too huge. You can use MineTweaker to remove recipes if you like.
