### ISSUE TITLE
Se crachea con el escaner de retina

### ISSUE THREAD

**Issue by LimaLimon90** [Geforce132/SecurityCraft#140]
Buenas tardes.
tengo un server con mis amigos, y este es uno de los mods que tenemos en el. Sin embargo, cuando le doy clic derecho al escáner de retina, ya sea para colocar una antorcha de redstone detras de el o para utilizar el  Universal block midifier para usar el Disguise module, se crachea mi minecraft(no el server).
Aqui dejo el crash report
https://pastebin.com/58KcWiaG
Espero y se pueda solucionar esto, ya que me gusta mucho este mod, gracias.

**Comment by RedstoneDubstep** [comment]
Hi,
I'm not familiar to speaking in Spain, so I'll use english to write to you. If you can't understand this language, I will try to translate this message.
I'm 90% sure that the crash you are talking about has already been fixed and the fix will be implemented in the next version of SecurityCraft.

**Comment by bl4ckscor3** [comment]
Hello, I don't speak your language. It's incredibly rude of you to assume that everyone speaks your language, especially when everything on this repository is English. Additionally, the name of your player does not correspond to a legally obtained Minecraft/Mojang account, so we won't be providing support for this crash.
