### ISSUE TITLE
Bug with keypad_furnace 1.15.2

### ISSUE THREAD

**Issue by BigShadow155** [Geforce132/SecurityCraft#142]
forge version 31.1.37

I have a problem with the keypad_furnace item, when I put something to do in the oven it doesn't work and the items disappear.

Any solution?

**Comment by bl4ckscor3** [comment]
Update the mod to [v1.8.18.1](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/2960791) and report back, whether it works when you use that version.

**Comment by BigShadow155** [comment]
Okay, thank you. I'll check it out.

**Comment by bl4ckscor3** [comment]
Since it's been seven days without another report about it not working, I am assuming that udpating the mod fixed it for you.

**Comment by BigShadow155** [comment]
Right, I've tested it and works correctly. Thank you very much.
