### ISSUE TITLE
SecurituCraft-sentry bugged

### ISSUE THREAD

**Issue by Dereck11111** [Geforce132/SecurityCraft#149]
Hi...I have a problem with a sentry, I used an universal owner changer on it (just to see what it does) and apparently I changed the owner of the sentry from me to a bunch of numbers that I suppose are like a ghost player..
The thing that I'm asking for is a way to take the sentry out, with out being the owner(I tried using cretive and /set block but It did not work)

**Comment by bl4ckscor3** [comment]
Hi! First of all, we use this issue tracker as a way to report bugs not to ask for help with the mod. For the latter, please use the #help channel in [our Discord](https://discord.gg/U8DvBAW). Secondly the Sentry is an entity and not a block, hence it cannot be removed with the setblock command. You can use the kill command instead.
