### ISSUE TITLE
Owner block broken

### ISSUE THREAD

**Issue by hyoungjink** [Geforce132/SecurityCraft#152]
Owner block is broken by Plustic mod razor

**Comment by bl4ckscor3** [comment]
PlusTiC is no longer available in CurseForge because its author was banned from the site for good reason. I won't be writing support for this mod. Read: https://old.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/fnr8rv2/
