### ISSUE TITLE
Duplicate Tileentity causes Lag

### ISSUE THREAD

**Issue by HeberonYT** [Geforce132/SecurityCraft#153]
Hello, does anyone know what is going on with the reinforced blocks?
I have a lot of reinforced blocks and turrets in the overworld, but when the players go to another world and the overworld is empty of players, it begins to drastically increase the amount of "tileentityownable" to the point of throwing the server.
I found a way to temporarily solve it, and it is returning a player to the overworld for a few seconds, thus decreasing the tileentityownable count to a thousand, which is normal.

![Screenshot_10](https://user-images.githubusercontent.com/13698597/83172694-966a8000-a0dd-11ea-9c2b-487d0c0738ae.png)

[1.12.2]+SecurityCraft+v1.8.18.2.jar

**Comment by bl4ckscor3** [comment]
1. Sentries are entities, not blocks
2. Having no players in a dimension should not increase the amount of tile entities that are loaded. Do you notice an increase of other tile entities as well when there are zero players in the overworld?

**Comment by HeberonYT** [comment]
Entities don't augment, mobs or turrets aren't the problem.
The following data shows the constant increase over a period of 15 minutes.
It seems that the problem is related to TileEntities, since in each sample an increase in blocks of different mods is observed, the data is provided by TickProfiler.

https://pastebin.com/raw/tz4FAsqy

**Comment by HeberonYT** [comment]
In the image of the beginning, it is also observed how there is a count of 3796 RetinalScanner, which is illogical because in my world I will have 50 maximum.

**Comment by HeberonYT** [comment]
It seems to be a problem with the server core.
Thank you for your time and sorry for the inconvenience.
