### ISSUE TITLE
Incompatible Crash w/ Fairy Lights

### ISSUE THREAD

**Issue by colbyrobison** [Geforce132/SecurityCraft#157]
Keypad Furnace causes game to crash when installed alongside Fairy Lights mod

[crash-2020-06-04_13.29.52-client.txt](https://github.com/Geforce132/SecurityCraft/files/4731789/crash-2020-06-04_13.29.52-client.txt)

**Comment by bl4ckscor3** [comment]
1. That crash-report is incomplete. It's missing the stacktrace which gives developers information about what caused the crash. 
2. What makes you so sure that it is Fairy Lights that SecurityCraft is conflicting with? Please try to reproduce the crash with only Fairy Lights and SecurityCraft installed.
3. Can you provide a way to reproduce this crash, please?

**Comment by colbyrobison** [comment]
Crash report with only Fairy Lights & Securitycraft installed
[crash-2020-06-05_13.56.00-client.txt](https://github.com/Geforce132/SecurityCraft/files/4737722/crash-2020-06-05_13.56.00-client.txt)
