### ISSUE TITLE
World Corruption

### ISSUE THREAD

**Issue by TerdyTheTerd** [Geforce132/SecurityCraft#16]
A user on my server was experimenting with ways to remove protected SecurityCraft blocks, he was using a quarry, when the quarry attempted to break the block the sever crashed, and the world became corrupted. The server would instantly freeze after loading and I had to roll back those chunks for it to be playable again. I don't have a lot of info about this issue yet but I will be running test on a spare server to get exacts to help you figure out to prevent this issue.

**Comment by Geforce132** [comment]
@TerdyTheTerd Sorry about that! Could you post the crashlog though? That will definitely help.

**Comment by TerdyTheTerd** [comment]
That's the issue, it doesn't crash, just as soon as it finishes loading the entire server become unresponsive, as if it is stuck on a single tick. I was told by the person who placed the QuarryPlus quarry that it isn't an issue of the quarry mining the blocks, its that he placed it next to a securitycraft block and when the quarry tried to make its orange pipe frame that's when it crashed. My guess is it gets stuck in an infinite loop trying to break the block to place the frame pipe, but can't due to some code in your mod. I'm not sure if there is some way to add like a checkPlayerBreak method to see if its a player trying to break the block, if so don't break, if not then break, or if that would cause issues with otehr entities that can break stuff (mining turtles).

**Comment by bl4ckscor3** [comment]
I thought of that being the issue, too, but we just set the block to unbreakable, and have an event check for a rightclick with the Universal Block Remover. There should not be any issue with that. What I think is happening, is that the quarry mod does not take unbreakable blocks into account, and will hang up because it doesn't know what to do with them. Have you notified the developer(s) of that mod of this problem, too?

**Comment by TerdyTheTerd** [comment]
Will post an issue there right away, thanks for looking into it

**Comment by Geforce132** [comment]
What's the name of the quarry mod you're using? Maybe I can hit up the developer of that mod as well.

**Comment by TerdyTheTerd** [comment]
Sorry, it was from QuarryPlus mod

**Comment by bl4ckscor3** [comment]
I'll close this as it is nothing we can fix.
