### ISSUE TITLE
how do i disable claims

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [Geforce132/SecurityCraft#160]

**Comment by GamingWithaAlexYouTube** [comment]
i me and my players can not place down chests and there is not part of that in the config

**Comment by bl4ckscor3** [comment]
This does not sound like an issue with SecurityCraft. Check if you have the mod installed on the server as well, and that you are launching the forge jar file, and not the minecraft jar file.
Other than that, this is not a place to seek help. Only report bugs on this site, please. To receive help, please join our Discord server, read the rules, then ask your question *in detail* in the #help channel.
