### ISSUE TITLE
Visual bug related to reinforced chests

### ISSUE THREAD

**Issue by MartinSalinas98** [Geforce132/SecurityCraft#165]
There are some weird graphic bugs related to reinforced chests. One of them, is that, if you walk one block above a reinforced chest, there is a specific position where the chest becomes invisible. Also, if you place a normal chest on one of de adjacent blocks of a reinforced chest, the normal chest doubles it size and the reinforced chest becomes invisible. I've attached a picture showing that. The reinforced chest still has a hitbox, the normal chest still has the same inventory size, and the second block of the normal chest doesn't have any hitbox, so it's just a visual thing. When you remove either the normal chest or the reinforced chest, everything goes back to normal. If you place then any block where the imaginary chest block is, you are allowed to place it and both blocks sort of merge and you can kind of see both textures overlapping each other.
![bug](https://user-images.githubusercontent.com/23634297/84550983-73121880-ad0c-11ea-98c8-d026ff6df870.JPG)
At first I thought that could be a shadders' issue, but I deactivated them, tried it again, and the same thing happened.
Btw, I'm using 1.8.18.2

**Comment by bl4ckscor3** [comment]
It's a very old bug which has been known for years and is unlikely to be fixed. Leaving this open just in case.

**Comment by MartinSalinas98** [comment]
12.2.2 support is useful for compatibility with certain mods, like Thaumcraft. Some really good mods are not being developed any more and are only available for some old versions like 1.12.2, so, if you want to play them, you have to put up with that and hope that every mod you want to include also supports that version (and works fine with the least amount of bugs possible).
Anyway, I know it's hard to work on a mod with several branches for each minecraft version at a time, and I'd understand that 1.12.2 support ended sooner or later.

**Comment by bl4ckscor3** [comment]
I'm not saying we're ending 1.12.2 support any time soon, just that it will be ending in the future at all. And since the SecurityCraft editions for newer Minecraft versions don't have the described issue, and I already put in a lot of work into trying to fix it with no success, a fix is not very likely.

**Comment by MartinSalinas98** [comment]
Maybe, if you remember anything about what things you tried and what changes did that cause, and you want to share it, somebody could actually take a look at the code and potentially fix it. I'd take a look at it myself, but I'm really new to minecraft modding and I have no idea about what packages/methods handle what things and how do the do it. But maybe sharing your research about it could help someone who actually understands everything that's going on in the code and ends up reading this issue. Again, only if you feel comfortable with it.
