### ISSUE TITLE
Problem with Inventory Scanner

### ISSUE THREAD

**Issue by LenniGengar** [Geforce132/SecurityCraft#168]
So I set the inventory scanner as everyone else does, the laser appeared, I put the item I want to have deleted in the scanner but it doesn't work. It was a modded item, but it also doesn't work with normal, vanilla items. Is this bug known? Is it even a bug?

**Comment by bl4ckscor3** [comment]
If you are on v1.8.18.x, the Inventory Scanner does nothing by default. In order for it to have any useful functionality, you need to rightclick the Inventory Scanner with a Universal Block Modifier and insert a Storage and/or Redstone Module. A Storage Module will remove blacklisted items from a player and add them to the inventory of the Inventory Scanner. A Redstone Module will emit a redstone signal if a blacklisted item has been found.
