### ISSUE TITLE
SecurityCraft is nota valid mod file

### ISSUE THREAD

**Issue by RealBoost-R** [Geforce132/SecurityCraft#169]
Hi, every time I go on Minecraft it says SecurityCraft is not a valid mod file please can you Help.

**Comment by bl4ckscor3** [comment]
You are trying to run a version of SecurityCraft that is not made for the Minecraft version you're using. The number in the square brackets (`[]`) at the start of SecurityCraft's file name tell you what Minecraft version that file is made for. If they do not match up for you, download the correct file from [the CurseForge page](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/all).
