### ISSUE TITLE
New version problem with FutureMC (1.12.2)

### ISSUE THREAD

**Issue by Alee-OneHit** [Geforce132/SecurityCraft#173]
Since I updated the SecurityCraft, I started having crash problems on my server and disconnection of my users, there must be some entity problem with the FutureMC mod, then I leave the crash log;

https://pastebin.com/Bvsp5BN7

**Comment by bl4ckscor3** [comment]
You are using an old version of Future MC. Update and try again. Other than that, SecurityCraft is not at fault here. Future MC is expecting SecurityCraft's iron ore mine to be rotatable, which it is not. Furthermore, it thinks that the mine is a beehive, which is incorrect as well. If this issue still happens after you updated Future MC, please report it to them.
