### ISSUE TITLE
[Suggestion] Pair Keycards with Keycard Reader

### ISSUE THREAD

**Issue by Vulant** [Geforce132/SecurityCraft#175]
I think right now, any keycard created can open any keycard reader. That's kind of a security breach! If you could make it to where the keycards are paired with a keycard reader, that would be great.

**Comment by JayWagner99** [comment]
Hi there! That's a real security breach. Please add pairing keycards to readers. Or u may modify whitelist module for keycard reader, so player would be able to open it only at BOTH circumstances: 1) He has required level keycard and 2) He is in whitelist. If whitelist module isn't installed - it would be enough for player just to use required level keycard, as usual as it's today's version of securitycraft. I love this mod and playing it with my friends at 14.4.4, hope to see an update, thanks)

**Comment by Scwestbrook** [comment]
Same here, but I think you shouldn't add the whitelist condition, or it would be smarter to use a keypad (More resourcce-friendly)

**Comment by bl4ckscor3** [comment]
Implemented in 84881450034936cd8d54e33a28e20060ccd66c03 (1.16.2), af07480806536ce0ce2b6d98c7017986f5f4a85f (1.15.2), 290853f2b588dde3bccd7966e28a16c8e3237770 (1.14.4), and 4509da066d6754abcba06885e57a37c3bf49e21a (1.12.2)
