### ISSUE TITLE
Mod version 1.16.1

### ISSUE THREAD

**Issue by Romaindu35** [Geforce132/SecurityCraft#177]
Hello,
Can you develop the mod in 1.15.2 or 1.16.1?
Romaindu35

**Comment by bl4ckscor3** [comment]
Hi. We use this issue tracker for bug reports, not for general questions. Please join our Discord server, read the rules, and then check the #1_16-update channel for the status on the 1.16.1 update. We will notify everyone when we release a first beta version. Until then, please be patient and don't ask for updates. The 1.15.2 version of the mod can be found [here](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/2992300).
