### ISSUE TITLE
I do not find the discord

### ISSUE THREAD

**Issue by Romaindu35** [Geforce132/SecurityCraft#178]
Hello,
Can you send the link of Discord ? 
Romaindu35

**Comment by bl4ckscor3** [comment]
I told you in the other issue that this issue tracker is for **bug reports** and _not_ general questions. If you don't have a bug to report, don't post. The Discord link can be found on [the mod's CurseForge page](https://www.curseforge.com/minecraft/mc-mods/security-craft).
