### ISSUE TITLE
camera screen when mounted in the block made for it vanishes

### ISSUE THREAD

**Issue by crunkazcanbe** [Geforce132/SecurityCraft#18]
As the title says the camera screen vanishes off the block made to hold it when I close MC down and start it back and log into my world . Can you fix this ? I am using version 1.8.0 ,and also this is just single player MC . Oh and using it with LookingGlass .

**Comment by Geforce132** [comment]
Since you're using LookingGlass, simply right-clicking the frame should make the view reappear.

**Comment by crunkazcanbe** [comment]
I did that and still nothing ?????

**Comment by bl4ckscor3** [comment]
@crunkazcanbe I cannot reproduce the issue you're having, when I have an active Frame with a bound Camera Monitor and exit out of the game and go back in, the Frame is empty and the Camera Monitor is black. Once I rightclick on the Frame, both it and the Camera Monitor regain the view of the camera. That /should/ also work for you.
