### ISSUE TITLE
KeypadFurnance causes crashes

### ISSUE THREAD

**Issue by VitalityDoS** [Geforce132/SecurityCraft#181]
I don't have the log, but I have read it and it causes a crash in my server.

**Comment by VitalityDoS** [comment]
I have [1.12.2] SecurityCraft v1.8.17.jar version installed, I will try to update it to v1.8.19.1

**Comment by bl4ckscor3** [comment]
If you are still experiencing crashes after updating the mod to v1.8.19.1 or later, please reply with the crash report from the Password-protected Furnace crash. You can find that file in the `crash-reports` folder in the same place where the `mods` folder is located.
