### ISSUE TITLE
Sentry disappearing in my server.

### ISSUE THREAD

**Issue by xCreeperYT** [Geforce132/SecurityCraft#191]
Hello, I have a server with mods and plugins (KCauldron), when I put a Sentry and a few hours pass it disappears automatically. I don't know what to do and I've checked the configuration. I haven't found anything...

**Comment by bl4ckscor3** [comment]
Minecraft and SecurityCraft version?

**Comment by xCreeperYT** [comment]
1.7.10 and SecurityCraft version 1.8.13

**Comment by xCreeperYT** [comment]
I'd also like to add that I have some mobs set aside and they do not disappear.

**Comment by bl4ckscor3** [comment]
We've had someone else report that their sentry disappeared, and it turned out that something (probably another mob) killed the sentry. Maybe that's what's happening here to.
I will close this issue, as we no longer support or update the mod for Minecraft 1.7.10, I'm afraid.
