### ISSUE TITLE
[MC : 1.7.10] [SC : 1.8.13] Wither still breaks SecurityCraft blocks

### ISSUE THREAD

**Issue by ExDomino** [Geforce132/SecurityCraft#192]
Minecraft version : 1.7.10
SecurityCraft version : 1.8.13

In this version, the wither do breaks blocks of SecurityCraft. All of them. Not just doors, cameras an so on, but also walls, floor and ceilling, in my case "Reinforced Cobblestone". These blocks are dropped on the ground like normal blocks. A previous version was fine for blocks, I don't remember which version, but it's no longer the case.

**Comment by Geforce132** [comment]
Sorry about that. Unfortunately, the 1.7.10 version of SecurityCraft is no longer being supported. Update to a newer version of Minecraft such as 1.14.4 or 1.15.2 if possible, and if you still encounter that issue, we'll be happy to investigate and fix it.
