### ISSUE TITLE
Breaking scanner doors

### ISSUE THREAD

**Issue by Pechu317** [Geforce132/SecurityCraft#202]
How do you break a scanner door that you own?

**Comment by bl4ckscor3** [comment]
Just like any other SecurityCraft block that you own, you can break it by rightclicking (or sneak-rightclicking if that doesn't work) it with a Universal Block Remover.

Also, we use this issue tracker for bugs in the mod, not for general help inquiries. If you need further assistance in how to use SecurityCraft, please join our Discord server.
