### ISSUE TITLE
I cant exit the cameras.

### ISSUE THREAD

**Issue by maxiiPLAYZYT** [Geforce132/SecurityCraft#204]
I've been using securitycraft for 3 days now and, no one in our server can exit. We all  try to click control on the camera and its broken. I even tried on a singleplayer game and cant exit the cameras. Thanks

**Comment by bl4ckscor3** [comment]
What Minecraft version, Forge version, and SecurityCraft version are you using?

**Comment by maxiiPLAYZYT** [comment]
> What Minecraft version, Forge version, and SecurityCraft version are you using?

> The lates 1.12.2 forge version, the lates SC version.

**Comment by bl4ckscor3** [comment]
Don't say "latest". For all you know, what you think is the latest version may not be the latest one. _Always_ say the exact version numbers to be 100% clear and everybody knows what's going on. Ambiguity doesn't help.

**Comment by bl4ckscor3** [comment]
I cannot reproduce this on Forge 14.23.5.2847 and SecurityCraft v1.8.19.3. If you do not use these or newer versions, please update. If your issue still persists after updating, please provide further info on this.
