### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Me1231313** [Geforce132/SecurityCraft#205]
How do I download this mod there is nothing in the text that says how to download it.

**Comment by Geforce132** [comment]
You download and install SecurityCraft like any other Minecraft Forge mod. I'll give you the links to a few videos below in case you don't already have Forge installed.

SecurityCraft's CurseForge page (where you will download the mod from): https://www.curseforge.com/minecraft/mc-mods/security-craft
How to install Forge on 1.16.2: https://www.youtube.com/watch?v=rgy1HiR-W9I
How to install mods on 1.16.2 (the video even specifically shows SecurityCraft being installed): https://www.youtube.com/watch?v=WqSC5glbPCw
