### ISSUE TITLE
Gradlew problem

### ISSUE THREAD

**Issue by SkyrixFr** [Geforce132/SecurityCraft#207]
I've tried to start the project and i had a bunch of errors i fixed them and then i have that pls help :
> Failed to apply plugin [id 'forge']
   > You must set the Minecraft Version!
      > java.lang.NullPointerException (no error message)

PS : it was with the 1.7.10 version.

**Comment by bl4ckscor3** [comment]
Based on the error, I am assuming you did not set the Minecraft version in the `build.gradle` file properly (no idea how you can do so, I haven't touched 1.7.10 in a long time). You could also try deleting the `.gradle` folder in your user directory, or using a different Forge version. You can also download the [1.7.10 Forge "Src" file](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html) for the version you're using, and compare the `build.gradle` file in there with yours.

As we no longer support nor maintain the 1.7.10 version of SecurityCraft, we can't assist you any further, I'm afraid.
