### ISSUE TITLE
Rail Mine X-Ray Bug

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Geforce132/SecurityCraft#212]
There is a glitch where the rail mine makes blocks transparent under it. The mod version is [1.16.3/.4] SecurityCraft v1.8.20.1 and my Forge version is 1.16.4-forge-35.0.1
![2020-11-07_16 23 12](https://user-images.githubusercontent.com/50182206/98451696-2e9d7400-2116-11eb-9d83-afb265fe89ff.png)

**Comment by bl4ckscor3** [comment]
Duplicate of #210. Will be fixed in the next release.
