### ISSUE TITLE
Electrified Fence Gate Not Opening

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Geforce132/SecurityCraft#213]
Every time I'm using an Electrified Fence Gate it won't open. The mod version is [1.16.3/.4] SecurityCraft v1.8.20.1 and my Forge version is 1.16.4-forge-35.0.1
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/50182206/98585946-00df3900-2296-11eb-92f7-2ac3ea7a144c.gif)

**Comment by bl4ckscor3** [comment]
You can only open the electrified fence gate by placing a Keypad/Keycard Reader/Inventory Scanner/... next/above/below it, and activating that block. Rightclicking and vanilla redstone do not work.

**Comment by ChrisLTheNerd** [comment]
Woops, i'm sorry about wasting your time.

**Comment by bl4ckscor3** [comment]
Don't worry about that.
