### ISSUE TITLE
plugin.yml is missing

### ISSUE THREAD

**Issue by h3tz** [Geforce132/SecurityCraft#217]
<img width="884" alt="Unbenannt" src="https://user-images.githubusercontent.com/6421402/99877810-04ad7c80-2c01-11eb-9d5c-c81c71aeb3d7.PNG">

**Comment by Tanguygab** [comment]
SecurityCraft is a Forge mod, not a Bukkit/Spigot plugin.
Thus, it won't work if you try to us eit as a plugin =)
