### ISSUE TITLE
Create mod compat

### ISSUE THREAD

**Issue by tealtoxic** [Geforce132/SecurityCraft#218]
tl:dr; wand of symmetry and blockzapper dont really work well with reinforced block from security craft.

1. playin in a modpack that has SC and Create, when used together with Wand of Symmetry, some block dont register me as block owner and instead 'owner' as the owner.

2. blockzapper cant register reinforced block to be used.

ill also report to Create mod dev. 

picture link via ImgBB since imgur(atm) cant be used: https://ibb.co/5knyM7g

mc version 1.15.2

**Comment by bl4ckscor3** [comment]
I am closing this as this is fixable by the Create devs.
