### ISSUE TITLE
Client Crash when right clicking camera with camera viewer tablet

### ISSUE THREAD

**Issue by plazia** [Geforce132/SecurityCraft#22]
Crashes the second I use the camera viewer tablet thingy to right click on my camera in the world.
Seems the crash report even mentions Steves's Carts. Not sure if this is a mod interaction issue/conflict.

Crash report: http://pastebin.com/rU4UGYBy

**Comment by bl4ckscor3** [comment]
Definetly an issue between LookingGlass and Steve's Carts. Report this crash to the author of Steve's Carts and disable LookingGlass in the config file of SecurityCraft until the issue is fixed.
