### ISSUE TITLE
Seus Shader - Lava/Water compatibility problem

### ISSUE THREAD

**Issue by Bright625** [Geforce132/SecurityCraft#221]
Hello,

I have realised that with SEUS Shaders, lava has the textures of water and instead 'fake lava' has the normal lava textures. Hope this gets fixed ASAP because have a look lol...[
![2020-12-15_21 12 15](https://user-images.githubusercontent.com/48101969/102274980-a4b6a700-3f1c-11eb-8ba6-c9524102cc8d.png)
](url)

**Comment by bl4ckscor3** [comment]
The only problem I can see is that the fake water has throws a "shadow". The nether looks fine for me. https://i.imgur.com/v58YIQu.jpeg
https://i.imgur.com/9PuUWp8.jpeg

**Comment by Bright625** [comment]
> The only problem I can see is that the fake water throws a "shadow", which I'm not sure if we can fix it. The nether looks fine for me.
> 
> https://i.imgur.com/v58YIQu.png
> 
> https://i.imgur.com/9PuUWp8.png

Hmmm, I'll have a look around, maybe it's some mod interfering

**Comment by Moto42** [comment]
Downgrading Alex's Mobs to version 1.18.5 fixed this issue for me.
