### ISSUE TITLE
I'm not able to craft the Camera.

### ISSUE THREAD

**Issue by Begnom** [Geforce132/SecurityCraft#224]
I downloaded some mods and make a new survival world to play with them, and in the middle of playing i thought about Security craft, since it adds cameras to the game so i could see what's happening outside my house, if there are any mobs there or anything like that, but when i got all the materials for a camera 6 Iron, 1 Stick, 1 Redstone Block and 1 Reinforced Glass Block, and put the all in the crafting table, i can't craft anything with them. Could anyone help me with this issue?
![unknown](https://user-images.githubusercontent.com/76882765/103464857-4456a080-4d37-11eb-85cf-2d4f962d3955.png)

**Comment by bl4ckscor3** [comment]
You need a Reinforced Block of Redstone.
