### ISSUE TITLE
Not loading.

### ISSUE THREAD

**Issue by madzhis** [Geforce132/SecurityCraft#226]
So basicly i want to play this mod with a mod called Scooty's Plants vs Zombies mod but every time i launch my forge 1.15.2 version it doesn't load (I use the newest 1.15.2 version of the mod)

**Comment by bl4ckscor3** [comment]
Please provide your latest.log and/or debug.log file. Otherwise we're not able to diagnose your issue.

**Comment by RedstoneDubstep** [comment]
It works for me with PvsZ 0.7.2, SecurityCraft 1.8.20.2 and Forge 31.2.47.

**Comment by bl4ckscor3** [comment]
Closing this then as it doesn't seem to be related to SecurityCraft. @madzhis, if you are able to provide the log files I requested above, and they are different from RedstoneDubstep's, feel free to post them and we can take another look to see if we can do something about it if it's related to SecurityCraft.
