### ISSUE TITLE
Server crash when accessing keypad chest from ComputerCraft due to false assumption

### ISSUE THREAD

**Issue by MCJack123** [Geforce132/SecurityCraft#229]
I'm a user on the ComputerCraft Discord server, and someone has recently told us that there was an issue when using SecurityCraft keypad chests and ComputerCraft turtles. I'm making this issue on their behalf.

[Here is the crash log they sent.](https://github.com/Geforce132/SecurityCraft/files/5875202/crash-2021-01-26_16.06.26-server.txt)

The crash log leads to this line:

https://github.com/Geforce132/SecurityCraft/blob/0a1c002dd9528a8c1f1ca458e5b547a7178dc81d/src/main/java/net/geforcemods/securitycraft/tileentity/KeypadChestTileEntity.java#L139

This assumes that `side` is not `null`, since as far as I can tell from the source code of Minecraft, `BlockPos.offset` does not like `null` arguments. However, ComputerCraft calls this function with `side` as `null`:

##### [CC-Tweaked/src/main/java/dan200/computercraft/shared/peripheral/generic/GenericPeripheralProvider.java](https://github.com/SquidDev-CC/CC-Tweaked/blob/1316d6a3c906eb1dcc0323982b46f655777ee628/src/main/java/dan200/computercraft/shared/peripheral/generic/GenericPeripheralProvider.java#L48)<br>Line 48 in [`1316d6a`](https://github.com/SquidDev-CC/CC-Tweaked/commit/1316d6a3c906eb1dcc0323982b46f655777ee628)
```java
LazyOptional<?> wrapper = tile.getCapability( capability );
```

This causes `KeypadChestTileEntity.getCapability` to call `BlockPos.offset` with a `null` argument, causing the server to crash.

To reproduce, place a keypad chest down, and place a turtle facing the chest, but a few blocks away. Then place some fuel in the turtle's inventory and run `refuel`. Finally, run `go forward 100` in the turtle to cause it to move towards the chest. Once it ends up next to the chest, the server will crash. (I haven't tested this myself, however.)

Environment:
* Minecraft 1.16.4
* SecurityCraft v1.8.20.2
* CC: Tweaked 1.95.2
* OS: Linux amd64
* Java: 1.8.0_275

More info is available in the attached crash log.

**Comment by bl4ckscor3** [comment]
Thanks for bringing this to our attention. The contract of `getCapability` actually notes that the Direction argument is nullable, so we were violating that contract with our implementation.
