### ISSUE TITLE
Game Crash Issue!

### ISSUE THREAD

**Issue by Ravin4t** [Geforce132/SecurityCraft#234]
If you accidentally try to use a keycard on a keycard reader that has not been set up my game crashes.

**Comment by bl4ckscor3** [comment]
I cannot reproduce this. Which SecurityCraft version are you using? Try updating if it's not v1.8.20.1. When reporting crashes, ALWAYS include the crash report, latest.log or debug.log file. It contains this and more information to help us modders to diagnose the issue much more easily.

**Comment by bl4ckscor3** [comment]
I am going to close this, as we have fixed this bug way back in March 2019 in v1.8.12 and it doesn't seem to have reappeared since then.
