### ISSUE TITLE
Client not starting / crashing

### ISSUE THREAD

**Issue by JoshyDo** [Geforce132/SecurityCraft#235]
Hey, can you look at this and tell me what information you need to help me start the game?

---- Minecraft Crash Report ----
[B#617]  // My bad.
[B#617]  
[B#617]  Time: 2021-02-26 11:24:40 CET
[B#617]  Description: Initializing game
[B#617]  
[B#617]  java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
[B#617]      at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
[B#617]      at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
[B#617]      at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
[B#617]      at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
[B#617]      at com.pam.harvestcraft.blocks.BlockRegistry.onBlockRegistry(BlockRegistry.java:460)
[B#617]      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2018_BlockRegistry_onBlockRegistry_Register.invoke(.dynamic)
[B#617]      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[B#617]      at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
[B#617]      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[B#617]      at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
[B#617]      at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
[B#617]      at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
[B#617]      at net.minecraft.client.Minecraft.init(Minecraft.java:467)
[B#617]      at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
[B#617]      at net.minecraft.client.main.Main.main(SourceFile:123)
[B#617]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#617]      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#617]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#617]      at java.lang.reflect.Method.invoke(Unknown Source)
[B#617]      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#617]      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by RedstoneDubstep** [comment]
This is not a bug with SecurityCraft, but with Pam's Harvestcraft, as seen in the crash report. Please report the problem to them, not to us.

**Comment by bl4ckscor3** [comment]
No, this is not a problem with Pam's Harvestcraft, or any mods in fact. The problem here is that you have too many mods installed that add new blocks/items/etc.
Install [JustEnoughIDs](https://www.curseforge.com/minecraft/mc-mods/jeid)  to fix this.
