### ISSUE TITLE
Disable Ownership/ Unbreakability completely

### ISSUE THREAD

**Issue by Kippenhof** [Geforce132/SecurityCraft#236]
Hey There,
We have an WW3 Modpack, and we just want the "balanced" stuff, where other players can actually do something about (e.g. Claimed Blocks) Is there any way to Disable Unbreakability or to give other players the option to "unlock" Claimed Blocks with the Codebreaker? Would be Really Nice for our Case 

Thx, and have an Nice Day :)

**Comment by bl4ckscor3** [comment]
Hi, these features of SecurityCraft are a very substantial part of the mod and cannot be changed, I'm afraid. There will not be a way to do so in the future.
