### ISSUE TITLE
Problemas con securityCraft

### ISSUE THREAD

**Issue by drummerplay** [Geforce132/SecurityCraft#237]
Tengo un servidor en la pagina de 4players y el problema que tengo es que este mod (que es el unico que tengo puesto con un mapa) Jugando yo solo si me funciona, pero jugando en el servidor marca el cubo pero desaparece al momento. He leido un post parecido que hay similar pero no me queda claro lo que hay que hacer, ya que el servidor que tengo es de pago. Dentro de la ventana del servidor meto tanto el mod como el forge (copiar y pegar) pero no tiene la opcion de instalar nada. Me podrian ayudar? Este es el segundo servidor que alquilo y me pasa exactamente lo mismo. No se que mas hacer. Gracias!

**Comment by bl4ckscor3** [comment]
This is not a place to ask for help with the mod, but a place to report bugs. As for your issue: Ask whatever server host you use how to create a Forge server. Make sure you have SecurityCraft installed on the server and on your client. Make sure you start the server with the proper jar file (forge jar, not minecraft_server jar). And lastly, you cannot assume that everyone on the internet speaks your language. We don't know any Spanish. Please use Google Translate next time when submitting an issue report.
