### ISSUE TITLE
Converting chests to password-protected chests does not set the owner properly

### ISSUE THREAD

**Issue by jarn123** [Geforce132/SecurityCraft#239]
I right clicked the right chest from a double chest with a key panel but the left ppc is owned by no one and has the password that i set on the right ppc but i wanted to remove the password protected double chest so now there is a unremovable block in the server with some friends so i have to ask my friend to delete it

p.p.c = password protected chest
version 1.12.2 
mod version 1.8.21

**Comment by jarn123** [comment]
![2021-04-03_09 50 22](https://user-images.githubusercontent.com/69686962/113472328-cbb0ce80-9462-11eb-9cc4-695f03d7d4ea.png)

**Comment by bl4ckscor3** [comment]
Set the `allowBlockClaim` configuration option to `true`, then right-clicking the chest with a Universal Block Modifier to claim it. Note, that enabling this configuration option only allows people to claim blocks that don't have an owner like this chest for example.
