### ISSUE TITLE
[suggestion] Config option to disable explotions breaking blocks

### ISSUE THREAD

**Issue by winsrp** [Geforce132/SecurityCraft#242]
The fact that you can put mines around you base helps a lot!, but the holes that are generated seem a little too much when you have mods like red moon flooding your base with enemies XD, I tried to look at all the config files but couldn't find one for that.

Can we have a config setting for sever side that disables explosions destroying blocks please.

Thanks.

**Comment by bl4ckscor3** [comment]
We can add it as a server configuration file option. This will not be a Universal Block Modifier per-block option, though.

**Comment by winsrp** [comment]
Sounds great tx so much
