### ISSUE TITLE
Module redstone do not work : /

### ISSUE THREAD

**Issue by Lun3z** [Geforce132/SecurityCraft#243]
Hi , i use the mod on 1.12.2 but when i use the Inventory Scanner , the redstone do not active , but i have put the redstone module

**Comment by bl4ckscor3** [comment]
The Inventory Scanner completely ignores its owner. Only other players will trigger a redstone output.

**Comment by Lun3z** [comment]
okay , thanks

**Comment by Lun3z** [comment]
but i'm not the owner and the system do no active

**Comment by Lun3z** [comment]
oh the system work !
