### ISSUE TITLE
How to add all players to the whitelist?

### ISSUE THREAD

**Issue by dd880602** [Geforce132/SecurityCraft#245]
How to add all players to the whitelist?

**Comment by bl4ckscor3** [comment]
Hello! We use this issue tracker for bug reports, not for general questions about or help with the mod. Next time, please join our discord server and ask in #help for questions and help for SecurityCraft.

To answer your question, there is no way to do that. You can add up to 50 players to the list and you have to add them one by one. For new lists you can use the copy/paste buttons in the whitelist module's GUI.
