### ISSUE TITLE
[Bug] Sentry won't stop shooting at a wall (1.12)

### ISSUE THREAD

**Issue by DereC4** [Geforce132/SecurityCraft#246]
Playing this on a 1.12 modpack but after the sentries finish off something they just keep shooting at a wall for some reason. This only happens when they're set to aggressive mode.

**Comment by DereC4** [comment]
https://drive.google.com/file/d/1qjy5FcSVx8UopcBitKkkews1iZmFvrGZ/view?usp=sharing

**Comment by DereC4** [comment]
Footage of the glitch

**Comment by bl4ckscor3** [comment]
What happens if you set the difficulty to peaceful?

**Comment by bl4ckscor3** [comment]
Closing this as we cannot reproduce it. If you can provide a minimal testing environment that reliably reproduces this, please reply with a setup.
