### ISSUE TITLE
[Suggestion] Pushable Reinforced Blocks

### ISSUE THREAD

**Issue by RealSourceOfficial** [Geforce132/SecurityCraft#247]
Using the Universal Owner Changer on a block with the name Minecraft will make the item movable

**Comment by bl4ckscor3** [comment]
Can you please elaborate? And what do you mean by "movable"?

**Comment by RealSourceOfficial** [comment]
As in pushable by pistons.

**Comment by RealSourceOfficial** [comment]
As in when you use the Universal Block Changer when its named "minecraft" or "game" in the anvil, it can be pushed by pistons

**Comment by bl4ckscor3** [comment]
Ah, so you want reinforced blocks that can be pushed by pistons. We did work on something like that some time ago, but didn't finish it. We may pick up work on that again in the future.

**Comment by RealSourceOfficial** [comment]
Ok, sounds great. Thanks for the quick response!

**Comment by bl4ckscor3** [comment]
Added for 1.12.2 (2d377be13da8d29b875a85353cb31fa3a89a4dd9), 1.15.2 (2caf9ae6a2aab17b8e78019539f40f12567636b1), 1.16.5 (879e220fe305c4f708d18d0c00b4b7ac1e9e6599), and 1.17.1 (45e6fafd9c4eb78509c13002b9bb5aa147c6b348).
