### ISSUE TITLE
alarm bug is back!

### ISSUE THREAD

**Issue by scottycool64** [Geforce132/SecurityCraft#250]
i am running a proper server with this mod, but the alarm causes the server to crash! i started the alarm, they made duplicate floor drops, and then the server closed itself, this is an extreme bug

**Comment by bl4ckscor3** [comment]
Please post the corresponding crash report.

**Comment by scottycool64** [comment]
the crash log is gine, let me see if its still stored.

**Comment by scottycool64** [comment]
ah, the bug is not reoccuring, not sure what happened.
