### ISSUE TITLE
Doors Not Updating

### ISSUE THREAD

**Issue by bekelly423** [Geforce132/SecurityCraft#252]
Hey folks. When one puts a security door down, with the retina scanner to the right, the door makes the sound that it is opening, but door stays closed. However one is then able to walk through said door. What could cause this? This has been witnessed by two different clients, one using Optifine and the other not. Thanks!

**Comment by bl4ckscor3** [comment]
Which Minecraft and SecurityCraft version are you using?

**Comment by bekelly423** [comment]
We are using Security Craft Verstion 1.8.21.1 and Java Minecraft 1.16.5

**Comment by bl4ckscor3** [comment]
I can't reproduce this. The Reinforced Iron Door, Scanner Door, and Keypad Door all open fine for me in singleplayer and multiplayer. This is likely some mod incompatibility. To narrow down the culprit, please move half your mods out of the mods folder (always keep SecurityCraft installed) and check if the issue persists. If it does, move the half of the remaining mods out of the mods folder and check for the issue again. If the issue no longer happens, swap the mods in the mods folder with the most recently moved half and try again. Do this until you're left with the mod(s) that cause this. Please report back if you find anything.
