### ISSUE TITLE
How to integrate the mod into a personal plugin

### ISSUE THREAD

**Issue by IzumiTV** [Geforce132/SecurityCraft#253]
Hello,
Is it possible to integrate the mod into a plugin (created manually) to allow for example to add an order to give the items because we cannot with Essentials for example, message saying that the item does not exist.

This will allow me to run a give command to players on my server to prevent them from being GM creatively.

Thanks you.
IzumiTV

**Comment by bl4ckscor3** [comment]
No, we cannot do something like this. SecurityCraft is a mod for Minecraft Forge, and will work on servers that have Forge installed. If you are getting a message that the item does not exist, then you need to install SecurityCraft and Forge properly. SecurityCraft will not work on a server that only has Spigot/Bukkit installed.

**Comment by IzumiTV** [comment]
My server has mohist and forge installed too.

**Comment by bl4ckscor3** [comment]
If SecurityCraft works properly on your server (i.e. you can place down blocks from SecurityCraft and all in all play with the mod), then such a give command should work. If it doesn't, it's not our problem as the command does not belong to our mod.
