### ISSUE TITLE
About Inventory Scanner

### ISSUE THREAD

**Issue by MCTF-Alpha-27** [Geforce132/SecurityCraft#257]
After the 1.8.21 release update, I don't know how to use it.
I put something in it.When I cross it, I found it didn't work.
And the GUI of it looks very strange
(PS:My English is poor, I'm just a chinese student.)

**Comment by bl4ckscor3** [comment]
1. The Inventory Scanner does not work for the owner.
2. If you want the Inventory Scanner to output a redstone signal when a disallowed item is found, you have to insert a Redstone Module
3. If you want the Inventory Scanner to store the disallowed item, you have to insert a Storage Module

To insert a module, rightclick the Inventory Scanner with the module, or rightclick it with a Universal Block Modifier and put the module into one of the slots at the top.
