### ISSUE TITLE
[Suggestion] Add config option to change reinforced block hardness.

### ISSUE THREAD

**Issue by nicolaibertolyu** [Geforce132/SecurityCraft#259]
Currently running a modded SMP and we've found that letting players place unbreakable blocks is a bit too strong, especially since the premise of the server is defending against mobs that can break blocks. A config that would let us change the block hardness applied to all reinforced blocks would be very useful, so we can set it to something closer to obsidian rather than bedrock.

**Comment by bl4ckscor3** [comment]
Sorry, that's a no from us. The blocks being unbreakable is an integral part of the mod. Adding this config option would mean we'd have to overhaul/change/remove large portions of SecurityCraft.
