### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by alexiprosa1245** [Geforce132/SecurityCraft#263]
i tried new versions and the older ones from the 1.12.2 mod but all the blocks with camouflage are textured as stone. i tried different ways to place the block like with shift + right click or near a bock but it still did not change anything.  the block sound is changed to the right block.

the stone in the picture is a secret chest

![Screenshot 2021-07-30 162604](https://user-images.githubusercontent.com/54320883/127667781-fc1961e0-b06e-46ec-83f0-e1c6014883d5.png)

**Comment by bl4ckscor3** [comment]
SecurityCraft does not have a secret chest. We have a password-protected chest, however that one cannot be disguised. Are you sure this bug report concerns SecurityCraft?

**Comment by alexiprosa1245** [comment]
oh sorry, i wasted your time. it is part from an other mod, my brother told me that it was from this mod. so i think its best to close this.
