### ISSUE TITLE
The abuse of the bedrock glitch on reinforced materials and protected chests & doors in version 1.16.5.

### ISSUE THREAD

**Issue by BeyondTheExistence** [Geforce132/SecurityCraft#264]
There is a glitch that is being abused in a server for removing reinforced blocks & protected items without the consent of the owner or without the use of "Universal Owner Changer" and/or "Universal Block Remover".
[SecurityCraft glitch](https://youtu.be/h86NWeTbgPY)
Consists on the use of vanilla blocks such as pistons, tnt and obsidian to remove reinforced blocks, protected chest & doors.

I personally feel unsecured with such glich and find no purpose on crafting reinforced blocks & security items.

Modpack:
Tinkers Construct (by mDiyo)
Macaw's Roofs (by sketch_macaw)
Applied Energistics 2 (by AlgorithmX2)
Corpse (by henkelmax)
Bookshelf (by DarkhaxDev)
Crafting Dead Survival (by Sm0keySa1m0n)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Vending Machine (by MacTso)
Cooking for Blockheads (by BlayTheNinth)
Macaw's Doors (by sketch_macaw)
Macaw's Furniture (by sketch_macaw)
Simple Voice Chat (by henkelmax)
MrCrayfish's Vehicle Mod (by MrCrayfish)
Clumps (by Jaredlll08)
Crafting Dead Immerse (by Sm0keySa1m0n)
Immersive Posts (by TwistedGate)
Just Enough Items (JEI) (by mezz)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mantle (by mDiyo)
City Blocks (by Hallzmine)
MrCrayfish's Furniture Mod (by MrCrayfish)
Immersive Engineering (by BluSunrize)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Waila Harvestability (by squeek502)
Macaw's Windows (by sketch_macaw)
Hwyla (by TehNut)
Crafting Dead (by nexusnode)
Dynamic Surroundings (by OreCruncher)
Wawla - What Are We Looking At (by DarkhaxDev)
Configured (by MrCrayfish)
Security Craft (by Geforce132)
JourneyMap (by techbrew)
Just Enough Vehicles (by Ozelot5836)
Better Animals Plus (by cybercat5555)
Obfuscate (by MrCrayfish)

**Comment by RedstoneDubstep** [comment]
Unfortunately, that is a Minecraft glitch (that also works for removing Bedrock or any block you wish, as you said) and thus this is most likely not fixable by us without hooking deep into Minecraft's code. Maybe there exists a mod or datapack somewhere that fixes this mechanic, but if you can't find such a tool then you probably need to wait until Mojang fixes this bug.
