### ISSUE TITLE
Turret Causes Game Crash *CRITICAL ERROR*

### ISSUE THREAD

**Issue by WoahdangJr142** [Geforce132/SecurityCraft#265]
I made a server with some of my friends, and it contained Security Craft. One of my friends placed a turret, that eventually glitched and started shooting at nothing. The next day or maybe even later that same day, I get online and head over to his house. I was the only one anywhere near it and I was on my way through. But when I came close enough to I believe load entities, my game crashed. He is the only one with a turret, and it was already glitched so I believe that to mean it is the turret causing the problem. Anytime me or any of my friends go near it our game crashes, and I have to use console to teleport them to somewhere not in entity-loading range of the turret.

**Comment by bl4ckscor3** [comment]
Please provide the crash report.

**Comment by bl4ckscor3** [comment]
Do you have a latest.log or know how to cause this bug? Otherwise, this bug is hard to reproduce for us.

**Comment by WoahdangJr142** [comment]
I believe it was shooting at me, the I used /home with FTB Essentials and it glitched out.

**Comment by bl4ckscor3** [comment]
Ah, you're using a Forge/Spigot hybrid server. It's possible that that one causes the issue. If you can't provide anything concrete, unfortunately there's little we can do.

**Comment by WoahdangJr142** [comment]
No it is 100% forge FTB Essentials is a mod

**Comment by bl4ckscor3** [comment]
Oh, I misread. Sorry, my bad. The point still stands.

**Comment by WoahdangJr142** [comment]
[debug.log](https://github.com/Geforce132/SecurityCraft/files/6925388/debug.log)
[latest.log](https://github.com/Geforce132/SecurityCraft/files/6925390/latest.log)
Here is debug.log and latest.log, but I left the server running for about an hour after the errors happened and we all left, and there are some other normal errors and warns from other mods.

**Comment by WoahdangJr142** [comment]
If you need I can start the server later, get booted from the server, and stop it and send the logs again.

**Comment by bl4ckscor3** [comment]
The server logs don't show anything, sadly. Can you provide the client logs? Perhaps they contain something.

**Comment by WoahdangJr142** [comment]
Client:
[latest.log](https://github.com/Geforce132/SecurityCraft/files/6925632/latest.log)
New Server logs after going through the whole thing again:
[debug (1).log](https://github.com/Geforce132/SecurityCraft/files/6925639/debug.1.log)
[latest (1).log](https://github.com/Geforce132/SecurityCraft/files/6925640/latest.1.log)

**Comment by bl4ckscor3** [comment]
Hm, sadly these don't contain anything either. I'll have to see if I can reproduce this by doing what you explained in an earlier comment.

**Comment by WoahdangJr142** [comment]
Ok. For now do you know of a way to fix it without resetting the world?

**Comment by bl4ckscor3** [comment]
Remove the Sentry with an external program like MCEdit, or NBT Explorer.

**Comment by WoahdangJr142** [comment]
I am using Apex Hosting to host my server. Is there a way I could access the world even when it is on there using one of these? or would I have to install WorldEdit mod on the server and do a very wide-range //replacenear?

**Comment by bl4ckscor3** [comment]
Not sure if Apex Hosting allows for the world to be downloaded, but if they do, then download it and edit it locally. Then upload the edited version again. Otherwise, WorldEdit might work, though I do not know if it will work through unloaded chunks.

**Comment by WoahdangJr142** [comment]
Does the Sentry count as an entity or a block? From a distance I can see his base but when I get within I believe it is entity-loading range, it breaks my game.

**Comment by bl4ckscor3** [comment]
It's an entity.

**Comment by WoahdangJr142** [comment]
Hm so WorldEdit probably wouldn't work, and I can't get a world download from Apex.

**Comment by bl4ckscor3** [comment]
I could not reproduce this. The steps I've tried:
1. Set my home
2. Teleport far away to a sentry
3. Let a sentry shoot at me
4. Execute /home
5. Go back to the sentry

This did not kick me from the server and worked as it should.

**Comment by WoahdangJr142** [comment]
That's weird. When it happened it was with me and my friend, where his turret shot at me, I /homed, it later started shooting randomly at something we couldn't see, then the next day the Chunk has an Entity Ticking Error or something causing the surrounding area to be corrupted.

**Comment by WoahdangJr142** [comment]
What is the entity ID so I can /cofh killall

**Comment by bl4ckscor3** [comment]
That entity ticking error, do.you still have it somewhere?

The sentry is registered as `securitycraft:sentry`, though cofh should really show suggestions...

**Comment by WoahdangJr142** [comment]
No I just assume that is what it is because that was the most common thing that came up for my error

**Comment by WoahdangJr142** [comment]
as for the ID question I was trying to do it through console so there were no suggestions

**Comment by WoahdangJr142** [comment]
Oh well
