### ISSUE TITLE
icon rendering conflict [1.8.9]

### ISSUE THREAD

**Issue by kotoroshinoto** [Geforce132/SecurityCraft#27]
can't see thaumcraft's arcane bellows icon, perhaps others, with securitycraft installed

**Comment by bl4ckscor3** [comment]
Is this still an issue with the latest version? (v1.8.7)

**Comment by bl4ckscor3** [comment]
I'm going to close this due to lack of response. Please feel free to reopen and provide screenshots if this issue persists.
