### ISSUE TITLE
Reinforced Smooth Quartz looks like Reinforced Quartz

### ISSUE THREAD

**Issue by Loganad325** [Geforce132/SecurityCraft#277]
The Reinforced Smooth Quartz Block looks like the Reinforced Quartz Block.
Here are some images, on the right is Smooth Quartz and on the left is Quartz.
(I am testing this on 1.16.5)

The first image is with shaders and texture packs.
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 9_17_2021 5_45_51 PM](https://user-images.githubusercontent.com/84825962/133861470-7f445197-51df-484c-9f85-6a0e72c9d2b8.png)

The second image is without shaders and no texture packs.
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 9_17_2021 5_46_45 PM](https://user-images.githubusercontent.com/84825962/133861525-7de2f525-6f5d-4b69-8eaa-ab83e3a59543.png)

This is normal quartz, this is what I would expect it to look like, but still be gray/reinforced
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 9_17_2021 5_52_48 PM](https://user-images.githubusercontent.com/84825962/133861690-85c33f46-c729-4906-b08d-cb5ef1187fe1.png)

I would appreciate it if this issue was fixed, thank you for the great mod!

**Comment by bl4ckscor3** [comment]
Thanks a lot! It'll be fixed in the next update of the mod. In the meantime, you can use this resource pack to fix it:
[sc_smooth_quartz_fix.zip](https://github.com/Geforce132/SecurityCraft/files/7189631/sc_smooth_quartz_fix.zip)
