### ISSUE TITLE
keypad door returns to barrel 1.16.5

### ISSUE THREAD

**Issue by Milkdude27** [Geforce132/SecurityCraft#278]
ive been using securitycraft and the create mod, and i made a door that closes to hide the keypad door, yet whenever i close the create mod door (two stone blocks right in front of the keypad door, moved by a mechanical piston to hide it) the keypad door will stay where it is until the chunk gets unloaded, in which it returns to the barrel i stored it in. how does this happen?

**Comment by bl4ckscor3** [comment]
Can you please post a video of this happening and showing the exact setup? I have zero knowledge about Create.

**Comment by Milkdude27** [comment]
nevermind, it was an issue with the server, not with the door or create. (id post a video to show you anyway but i dont exactly know how to do that

**Comment by bl4ckscor3** [comment]
Upload to YouTube, paste link here. Or drag and drop the video into the comment box (if the file size's less than 10MB).
