### ISSUE TITLE
[1.16.5] Using key panels on unopened chests with a loot table dupes items

### ISSUE THREAD

**Issue by Nebula240** [Geforce132/SecurityCraft#279]
Using a key panel on chests locked with the Locks mod. (https://www.curseforge.com/minecraft/mc-mods/locks)
will cause the chest to be "destroyed" and dropping items on the ground.

Then it will ask to set up a password. By setting it and opening the chest there will be a new loot table of items generated inside, basically duping items.

https://user-images.githubusercontent.com/62150697/134615681-5950cf2d-f252-4255-bf2e-a761fb08a5b5.mp4

**Comment by bl4ckscor3** [comment]
This is not an issue with the Locks mod. Placing a chest down, locking it, then converting it to a password-protected chest does not spill out the contained items. This issue happens with any chest whose loot has not been generated yet.
