### ISSUE TITLE
1.7.10 security camera not working on SMP

### ISSUE THREAD

**Issue by johnfg12** [Geforce132/SecurityCraft#28]
testing the mod in SMP on a delected kcauldron server it would apper the camera does not work i have lookingglass installed

**Comment by bl4ckscor3** [comment]
LookingGlass does not work on (K)Cauldron servers, as the server provides invalid chunk data with which LookingGlass cannot do anything. This is unfixable on our side, and XCompWiz could do a hacky workaround, however that task would be far too hard to accomplish.
Ultimately, it's up to the (K)Cauldron guys to fix that.

**Comment by johnfg12** [comment]
so should i report it to them?

**Comment by johnfg12** [comment]
also does it work with out it looking glass

**Comment by bl4ckscor3** [comment]
You can try reporting it to them, but in the past they have shown little interest in fixing that issue.

Yes, SecurityCraft works fine without LookingGlass, however keep in mind that you won't be able to place monitors into frames anymore and that monitors won't show the camera view anymore. You can merely rightclick them to view a camera.

**Comment by johnfg12** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/issues/396
could you put how the invald chunk things work im a modpack builder not good at java :D

**Comment by DragonbornAtDawn** [comment]
I used SecurityCraft with the RLCraft modpack and the camera monitor won't let me view cameras. What do I do?

**Comment by bl4ckscor3** [comment]
You can't view cameras in frames in any version other than 1.7.10. To view them in 1.12.2, make sure the camera is in a loaded area, and it's bound to your monitor. Then rightclick the monitor, and click on the button of the camera you want to view.

Also, this is an issue tracker which we use for bug reports, not for general help inquiries. I don't know how the hell you got to this ancient issue, but please don't create issues here unless you are reporting a bug, and don't comment on issues unless you have further information on them. We offer general help for SecurityCraft on our Discord server in the #help channel.
