### ISSUE TITLE
Suggestion: Make possible to reinforce modded blocks

### ISSUE THREAD

**Issue by Nebula240** [Geforce132/SecurityCraft#281]
I think that it would be a neat idea, considering this mod is run on different modded servers

**Comment by bl4ckscor3** [comment]
No. Reinforced blocks have to be added manually one by one, and if we start doing that for one mod, we get a request for the next one, and another one, and so on. We don't have the time to support this amount of mod compatibility. Modded reinforced blocks will have to be added by a different mod - either the one whose blocks should be reinforced, or an add-on mod.

**Comment by Nebula240** [comment]
> No. Reinforced blocks have to be added manually one by one, and if we start doing that for one mod, we get a request for the next one, and another one, and so on. We don't have the time to support this amount of mod compatibility. Modded reinforced blocks will have to be added by a different mod - either the one whose blocks should be reinforced, or an add-on mod.

Ooh I see. Thanks!
