### ISSUE TITLE
Alarm sound does not play

### ISSUE THREAD

**Issue by triscuitthebiscuit** [Geforce132/SecurityCraft#285]
the beta version of security craft 1.17.1 alarm doesn't play a sound it lights up but no sound i would like to see this fixed in the next beta version

**Comment by bl4ckscor3** [comment]
Known issue across all versions we support, will be fixed in the next version of the mod.

**Comment by triscuitthebiscuit** [comment]
thank you i wanted to use it for my bunker when someone enters
