### ISSUE TITLE
Bug with darker reinforced block textures

### ISSUE THREAD

**Issue by Fred09x** [Geforce132/SecurityCraft#286]
Hello, I have a problem with a bug that presents the mod in my server, this mod when it reinforces blocks usually turns them a little darker color but there is supposed to be an option in the mod configuration so that when a block is reinforced It no longer becomes a darker shade, but when I do this it doesn't work. So I think it is a bug. Also below I put the configuration of the mod so that it is seen that despite having set "false" in the configuration line, there is no effect. Also i'm using the game version 1.12.2

options {
    B:"Allow claiming unowned blocks?"=false
    B:"Are mines unbreakable?"=true
    D:"Camera Speed when not using LookingGlass:"=2.0
    B:"Craftable Limited Use keycard?"=true
    B:"Craftable level 1 keycard?"=true
    B:"Craftable level 2 keycard?"=true
    B:"Craftable level 3 keycard?"=true
    B:"Craftable level 4 keycard?"=true
    B:"Craftable level 5 keycard?"=true
    B:"Craftable mines?"=false
    **B:"Darker reinforced block textures?"=false**
    B:"Display a 'tip' message at spawn?"=true
    B:"Display owner face on retinal scanner?"=true
    B:"Do mines' explosions break blocks?"=true
    I:"Inventory Scanner range:"=2
    B:"Is admin tool allowed?"=false
    B:"Is codebreaker allowed?"=true
    I:"Laser range:"=5

**Comment by bl4ckscor3** [comment]
This config option only works when changed on the client, it does nothing in servers.

**Comment by Fred09x** [comment]
> This config option only works when changed on the client, it does nothing on servers.

Ok thanks for helping me with my problem.
