### ISSUE TITLE
Linked keycards with /give?

### ISSUE THREAD

**Issue by likl** [Geforce132/SecurityCraft#289]
Hello, is there a way to get already linked keycard with the /give command?

**Comment by bl4ckscor3** [comment]
Hi.

First of all, this is a bug tracker, not a place to get help. If you need support with the mod, please join our Discord server and ask in the #help channel.
As for your question, yes it is possible. You can set NBT on the card according to the settings you want it to have. This tag can have the following entries (entries marekd with * are required):

"ownerName"* (string) the name of the owner of the keycard readers this keycard can open
"ownerUUID"* (string) the UUID of the owner of the keycard readers this keycard can open
"signature"* (integer) a number denoting which keycard readers this keycard works on (those of the card owner which have the same signature as the card)
"limited" (boolean) for saying whether the keycard is a limited use keycard
"uses" (integer) for denoting how many times a limited use keycard can be used
