### ISSUE TITLE
java.lang.ClassCastException: net.geforcemods.securitycraft.api.Owner cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by MilleniumModsSources** [Geforce132/SecurityCraft#296]
Game crashing when joined dedicated server.

Console error: lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

Crash report:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
llibrary (llibrary-core-1.0.11-1.12.2.jar)
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
CreativePatchingLoader (CreativeCore_v1.10.65_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 12/11/21 11:41 AM
Description: Ticking entity

java.lang.ClassCastException: net.geforcemods.securitycraft.api.Owner cannot be cast to java.lang.Integer
at net.geforcemods.securitycraft.entity.EntitySentry.getMode(EntitySentry.java:499)
at net.geforcemods.securitycraft.entity.EntitySentry.func_70030_z(EntitySentry.java:120)
at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2096)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
at net.minecraft.world.World.func_72866_a(World.java:1996)
at net.minecraft.world.World.func_72870_g(World.java:1958)
at net.minecraft.world.World.func_72939_s(World.java:1762)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at net.geforcemods.securitycraft.entity.EntitySentry.getMode(EntitySentry.java:499)
at net.geforcemods.securitycraft.entity.EntitySentry.func_70030_z(EntitySentry.java:120)
at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2096)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
at net.minecraft.world.World.func_72866_a(World.java:1996)
at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
Entity Type: securitycraft:sentry (net.geforcemods.securitycraft.entity.EntitySentry)
Entity ID: 1787
Entity Name: entity.Sentry.name
Entity's Exact location: -200.50, 90.00, 460.50
Entity's Block location: World: (-201,90,460), Chunk: (at 7,5,12 in -13,28; contains blocks -208,0,448 to -193,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Entity's Momentum: 0.00, -3.90, 0.00
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['Disgotk_74'/1740, l='MpServer', x=-22.78, y=68.00, z=452.05]]
Chunk stats: MultiplayerChunkCache: 456, 456
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options:
Level spawn location: World: (-116,64,252), Chunk: (at 12,4,12 in -8,15; contains blocks -128,0,240 to -113,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 62152351 game time, 7794637 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 85 total; [EntityPlayerSP['Disgotk_74'/1740, l='MpServer', x=-22.78, y=68.00, z=452.05], MoCEntityPetScorpion['PetScorpion'/1920, l='MpServer', x=-82.22, y=11.00, z=474.99], EntityPainting['Cuadro'/237, l='MpServer', x=-54.50, y=111.50, z=315.03], EntitySpider['Araña'/1921, l='MpServer', x=-92.50, y=11.00, z=477.50], EntityPainting['Cuadro'/238, l='MpServer', x=-58.03, y=105.50, z=318.50], MoCEntityRat['Rat'/1922, l='MpServer', x=-88.50, y=24.00, z=470.50], EntityPainting['Cuadro'/239, l='MpServer', x=-57.50, y=111.50, z=315.03], EntityPainting['Cuadro'/259, l='MpServer', x=-44.03, y=102.00, z=327.50], EntitySkeleton['Esqueleto'/1923, l='MpServer', x=-89.50, y=25.00, z=479.50], EntityPainting['Cuadro'/240, l='MpServer', x=-55.50, y=118.50, z=319.97], EntityPainting['Cuadro'/260, l='MpServer', x=-44.03, y=102.00, z=323.50], EntityCreeper['Creeper'/1924, l='MpServer', x=-94.83, y=65.00, z=465.51], EntityPainting['Cuadro'/241, l='MpServer', x=-56.97, y=101.50, z=325.50], VengeanceSpirit['Espíritu de la venganza'/1925, l='MpServer', x=-88.49, y=67.00, z=474.15], EntityPainting['Cuadro'/242, l='MpServer', x=-60.97, y=107.00, z=324.00], EntityPainting['Cuadro'/243, l='MpServer', x=-51.50, y=105.50, z=320.97], EntityCreeper['Creeper'/1927, l='MpServer', x=-97.56, y=71.00, z=517.80], EntityPainting['Cuadro'/244, l='MpServer', x=-51.50, y=105.50, z=328.03], EntityPainting['Cuadro'/245, l='MpServer', x=-56.03, y=105.50, z=328.50], EntityCreeper['Creeper'/1931, l='MpServer', x=-90.50, y=73.00, z=382.50], EntityPainting['Cuadro'/270, l='MpServer', x=-24.00, y=99.00, z=334.97], EntityPainting['Cuadro'/271, l='MpServer', x=-26.00, y=99.00, z=334.97], EntityPainting['Cuadro'/253, l='MpServer', x=-52.50, y=113.50, z=320.03], EntityPainting['Cuadro'/272, l='MpServer', x=-24.00, y=100.50, z=334.97], EntityPainting['Cuadro'/254, l='MpServer', x=-59.50, y=113.50, z=320.03], EntityPainting['Cuadro'/255, l='MpServer', x=-55.50, y=118.50, z=330.03], EntityPainting['Cuadro'/259, l='MpServer', x=-44.03, y=102.00, z=327.50], EntityPainting['Cuadro'/260, l='MpServer', x=-44.03, y=102.00, z=323.50], EntityPainting['Cuadro'/270, l='MpServer', x=-24.00, y=99.00, z=334.97], EntityPainting['Cuadro'/271, l='MpServer', x=-26.00, y=99.00, z=334.97], EntityPainting['Cuadro'/272, l='MpServer', x=-24.00, y=100.50, z=334.97], EntityPainting['Cuadro'/380, l='MpServer', x=-19.03, y=108.50, z=341.00], EntityPig['Cerdo'/1944, l='MpServer', x=-39.25, y=70.00, z=527.50], EntitySpider['Araña'/1946, l='MpServer', x=-72.50, y=26.00, z=432.50], EntityPainting['Cuadro'/1947, l='MpServer', x=-35.97, y=66.00, z=440.00], EntityPainting['Cuadro'/1948, l='MpServer', x=-35.97, y=73.00, z=443.00], EntityCreeper['Creeper'/1949, l='MpServer', x=-69.50, y=25.00, z=468.50], EntityCreeper['Creeper'/1950, l='MpServer', x=-67.50, y=37.00, z=456.50], EntityPainting['Cuadro'/1751, l='MpServer', x=-27.00, y=74.50, z=454.97], EntityPainting['Cuadro'/1752, l='MpServer', x=-32.00, y=74.50, z=454.97], EntityPainting['Cuadro'/1947, l='MpServer', x=-35.97, y=66.00, z=440.00], EntityPainting['Cuadro'/1948, l='MpServer', x=-35.97, y=73.00, z=443.00], EntityItemFrame['entity.ItemFrame.name'/1741, l='MpServer', x=-28.50, y=68.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1742, l='MpServer', x=-28.50, y=70.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1743, l='MpServer', x=-25.50, y=68.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1744, l='MpServer', x=-25.50, y=70.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1745, l='MpServer', x=-22.50, y=68.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1746, l='MpServer', x=-22.50, y=70.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1747, l='MpServer', x=-31.50, y=70.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1748, l='MpServer', x=-31.50, y=68.50, z=455.97], EntityItemFrame['entity.ItemFrame.name'/1749, l='MpServer', x=-19.03, y=68.50, z=454.50], EntityItemFrame['entity.ItemFrame.name'/1750, l='MpServer', x=-19.03, y=70.50, z=454.50], EntityPainting['Cuadro'/1751, l='MpServer', x=-27.00, y=74.50, z=454.97], EntityPainting['Cuadro'/1752, l='MpServer', x=-32.00, y=74.50, z=454.97], EntitySpider['Araña'/1892, l='MpServer', x=-100.72, y=65.00, z=454.35], EntityPainting['Cuadro'/237, l='MpServer', x=-54.50, y=111.50, z=315.03], EntityPainting['Cuadro'/238, l='MpServer', x=-58.03, y=105.50, z=318.50], EntityPainting['Cuadro'/239, l='MpServer', x=-57.50, y=111.50, z=315.03], EntityPainting['Cuadro'/240, l='MpServer', x=-55.50, y=118.50, z=319.97], EntityPainting['Cuadro'/241, l='MpServer', x=-56.97, y=101.50, z=325.50], EntitySkeleton['Esqueleto'/1905, l='MpServer', x=-100.50, y=48.00, z=410.50], EntityPainting['Cuadro'/242, l='MpServer', x=-60.97, y=107.00, z=324.00], EntityCreeper['Creeper'/1906, l='MpServer', x=-82.31, y=73.00, z=388.48], EntityPainting['Cuadro'/243, l='MpServer', x=-51.50, y=105.50, z=320.97], EntityPainting['Cuadro'/244, l='MpServer', x=-51.50, y=105.50, z=328.03], EntityPainting['Cuadro'/245, l='MpServer', x=-56.03, y=105.50, z=328.50], EntityArmorStand['Soporte para armadura'/246, l='MpServer', x=-51.50, y=111.00, z=321.50], EntityArmorStand['Soporte para armadura'/247, l='MpServer', x=-51.50, y=111.00, z=324.50], EntitySkeleton['Esqueleto'/1911, l='MpServer', x=-84.36, y=72.00, z=402.73], EntityArmorStand['Soporte para armadura'/248, l='MpServer', x=-51.50, y=111.00, z=327.50], EntityCreeper['Creeper'/1912, l='MpServer', x=-100.02, y=25.00, z=473.43], EntityArmorStand['Soporte para armadura'/249, l='MpServer', x=-60.50, y=111.00, z=324.50], MoCEntityRat['Rat'/1913, l='MpServer', x=-99.65, y=24.00, z=474.86], EntityArmorStand['Soporte para armadura'/250, l='MpServer', x=-60.50, y=111.00, z=321.50], EntityZombie['Zombi'/1914, l='MpServer', x=-101.73, y=34.00, z=474.43], EntityArmorStand['Soporte para armadura'/251, l='MpServer', x=-60.50, y=111.00, z=327.50], EntitySentry['entity.Sentry.name'/1787, l='MpServer', x=-200.50, y=90.00, z=460.50], EntityCreeper['Creeper'/1915, l='MpServer', x=-98.50, y=65.00, z=470.50], EntityPainting['Cuadro'/380, l='MpServer', x=-19.03, y=108.50, z=341.00], EntityPainting['Cuadro'/253, l='MpServer', x=-52.50, y=113.50, z=320.03], MoCEntityThrowableRock['entity.mocreatures:trock.name'/1917, l='MpServer', x=-86.82, y=64.00, z=450.50], EntityPainting['Cuadro'/254, l='MpServer', x=-59.50, y=113.50, z=320.03], MoCEntityThrowableRock['entity.mocreatures:trock.name'/1918, l='MpServer', x=-93.11, y=64.00, z=433.09], EntityPainting['Cuadro'/255, l='MpServer', x=-55.50, y=118.50, z=330.03], EntitySpider['Araña'/1919, l='MpServer', x=-82.30, y=11.00, z=482.30]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1747271208 bytes (1666 MB) / 2751463424 bytes (2624 MB) up to 3741319168 bytes (3568 MB)
JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3560m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 38 mods loaded, 38 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State  | ID                | Version         | Source                                        | Signature                                |
|:------ |:----------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
| LCHIJA | minecraft         | 1.12.2          | minecraft.jar                                 | None                                     |
| LCHIJA | mcp               | 9.42            | minecraft.jar                                 | None                                     |
| LCHIJA | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | forge             | 14.23.5.2855    | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | creativecoredummy | 1.0.0           | minecraft.jar                                 | None                                     |
| LCHIJA | securitycraft     | v1.8.22.2       | [1.12.2]-SecurityCraft-v1.8.22.2.jar          | None                                     |
| LCHIJA | deconstruction    | 3.0.4           | [MC1.12.2]DeconTable-3.0.4.jar                | None                                     |
| LCHIJA | abyssaldepths     | 1.12.2-0.3.2    | AbyssalDepths-1.12.2-0.3.2.jar                | None                                     |
| LCHIJA | baubles           | 1.5.2           | Baubles-1.12-1.5.2.jar                        | None                                     |
| LCHIJA | llibrary          | 1.7.19          | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
| LCHIJA | mowziesmobs       | 1.5.8           | mowziesmobs-1.5.8.jar                         | None                                     |
| LCHIJA | patchouli         | 1.0-21          | Patchouli-1.0-21.jar                          | None                                     |
| LCHIJA | bewitchment       | 0.22.63         | bewitchment-1.12.2-0.0.22.64.jar              | None                                     |
| LCHIJA | bibliotheca       | 1.3.6-1.12.2    | bibliotheca-1.3.6-1.12.2.jar                  | None                                     |
| LCHIJA | cannibalism       | 5.2.0           | Cannibalism-5.2.0-1.12.2.jar                  | None                                     |
| LCHIJA | carryon           | 1.12.3          | carryon-1.12.2-1.12.6.20.jar                  | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
| LCHIJA | geckolib3         | 3.0.0           | geckolib-forge-1.12.2-3.0.0-beta.9.jar        | None                                     |
| LCHIJA | jei               | 4.16.1.302      | jei_1.12.2-4.16.1.302.jar                     | None                                     |
| LCHIJA | cqrepoured        | 2.5.3B          | Chocolate-Quest-Repoured-1.12.2-2.5.3B.jar    | None                                     |
| LCHIJA | creativecore      | 1.10.0          | CreativeCore_v1.10.65_mc1.12.2.jar            | None                                     |
| LCHIJA | cyclopscore       | 1.6.7           | CyclopsCore-1.12.2-1.6.7.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
| LCHIJA | mocreatures       | 12.0.5          | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
| LCHIJA | erebus            | 1.0.32          | Erebus-1.0.32.jar                             | None                                     |
| LCHIJA | evilcraft         | 0.10.78         | EvilCraft-1.12.2-0.10.78.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
| LCHIJA | evilcraftcompat   | 1.0.0           | EvilCraft-1.12.2-0.10.78.jar                  | None                                     |
| LCHIJA | hammertime        | 2.2.0           | Hammer-Time-2.2.0-1.12.2.jar                  | None                                     |
| LCHIJA | waila             | 1.8.26          | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
| LCHIJA | infernalmobs      | 1.7.6           | InfernalMobs-1.12.2.jar                       | None                                     |
| LCHIJA | joshxmas          | 1.12.2-1.2.0    | joshxmas-1.12.2-1.2.0.jar                     | None                                     |
| LCHIJA | journeymap        | 1.12.2-5.7.1    | journeymap-1.12.2-5.7.1.jar                   | None                                     |
| LCHIJA | mantle            | 1.12-1.3.3.55   | Mantle-1.12-1.3.3.55.jar                      | None                                     |
| LCHIJA | mca               | 6.1.0           | MCA-1.12.2-6.1.0-universal.jar                | None                                     |
| LCHIJA | mcwdoors          | 1.3             | mcw-doors-1.0.3-mc1.12.2.jar                  | None                                     |
| LCHIJA | natura            | 1.12.2-4.3.2.69 | natura-1.12.2-4.3.2.69.jar                    | None                                     |
| LCHIJA | playerrevive      | 1.0             | PlayerRevive_v1.2.40_mc1.12.2.jar             | None                                     |
| LCHIJA | rustic            | 1.1.7           | rustic-1.1.7.jar                              | None                                     |
| LCHIJA | twilightforest    | 3.11.1021       | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
| LCHIJA | walljump          | 1.3.2           | walljump-1.12.2-1.3.2.jar                     | None                                     |

Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)

CreativePatchingLoader (CreativeCore_v1.10.65_mc1.12.2.jar)

GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12036.11001' Renderer: 'AMD Radeon R5 Graphics'
Pulsar/natura loaded Pulses: 
    - NaturaCommons (Enabled/Forced)
    - NaturaOverworld (Enabled/Not Forced)
    - NaturaNether (Enabled/Not Forced)
    - NaturaDecorative (Enabled/Not Forced)
    - NaturaTools (Enabled/Not Forced)
    - NaturaEntities (Enabled/Not Forced)
    - NaturaOredict (Enabled/Forced)
    - NaturaWorld (Enabled/Not Forced)

Patchouli open book context: n/a
Launched Version: 1.12.2-forge-14.23.5.2855
LWJGL: 2.9.4
OpenGL: AMD Radeon R5 Graphics GL version 4.6.13559 Compatibility Profile Context 26.20.12036.11001, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: SenseCraft-1.11-1.12.zip
Current Language: Español (España)
Profiler Position: N/A (disabled)
CPU: 4x AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
OptiFine Version: OptiFine_1.12.2_HD_U_G5
OptiFine Build: 20210124-142939
Render Distance Chunks: 10
Mipmaps: 0
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12036.11001
OpenGlRenderer: AMD Radeon R5 Graphics
OpenGlVendor: ATI Technologies Inc.
CpuCount: 4`

**Comment by bl4ckscor3** [comment]
This crash should not be possible as the data parameter that is being queried in the line of code that crashes has a fixed type (it can only ever be a number and never an Owner). The crash however says that it's trying to work with both at the same time.
This looks like the server you are trying to connect to is using an older version of the mod. Please verify that the server and your client both have the same version of SecurityCraft installed. If that is the case, then please try updating SecurityCraft to v1.8.23.2 and check if the issue persists.

**Comment by bl4ckscor3** [comment]
I can't reproduce this in v1.9 (released today). If you can, please provide steps to reproduce this and a new crash report and I'll reopen this.
