### ISSUE TITLE
JEI causing log spam due to recipes of reinforced blocks

### ISSUE THREAD

**Issue by Kaleidio** [Geforce132/SecurityCraft#298]
the following pastebin is just one snippet of several to help clear things up for you:
https://pastebin.com/Q2xXpgTr
full log:
[latest.log](https://github.com/Geforce132/SecurityCraft/files/7715062/latest.log)

**Comment by Kaleidio** [comment]
we suspect it might have also caused this but we are unsure.

https://github.com/TinyModularThings/UniqueEnchantments/issues/44

**Comment by bl4ckscor3** [comment]
I cannot reproduce this on default installations of SC v1.8.23 and JEI 7.7.1.138. This error is very weird, as the recipes seem to not have any output, however there is always one input and one output, and never both items in only the input. I'll push something that may mitigate the log spam, but it won't solve the underlying issue (which is very likely not on our end).

**Comment by Kaleidio** [comment]
the issue is because some mods might provide air blocks in their creative inventory slots, as mentioned in the link.  so yes, this mod can "cause" a problem but only if it does not have protection.  that is what your hotfix should do.  not trying to be rude or anything but that's what I have been told.  hope the fix works!

**Comment by Kaleidio** [comment]
note; mc 1.16.5

**Comment by bl4ckscor3** [comment]
f083f57 6347e1e

**Comment by Kaleidio** [comment]
coolio, awaiting curseforge release so I can test :)

**Comment by bl4ckscor3** [comment]
Will be a couple days as we finish up the update.

**Comment by Kaleidio** [comment]
no problem
