### ISSUE TITLE
Alarm won't stop!

### ISSUE THREAD

**Issue by Satoryc** [Geforce132/SecurityCraft#299]
I am on a properly set up server, no bugs in the console itself, however- there was an alarm placed in our world and once broken the alarm didn't stop going off, after placing blocks where the alarm was, and trying to add a new alarm, turn it on, then turn it off- nothing worked. The alarm can be heard by all players, and the sound is still coming from the exact spot where the alarm once was. The server is 1.12.2

**Comment by bl4ckscor3** [comment]
Which SecurityCraft version?

**Comment by Satoryc** [comment]
> Which SecurityCraft version?

v1.8.23.2

**Comment by bl4ckscor3** [comment]
Ok. There was an internal change for the alarm in between v1.8.22 and v1.8.23, however I've made sure (and just tested it again) that updating properly converts the old alarm to the new one. What you are explaining may be something left over for some reason, try placing a furnace or something with an inventory at the spot where the alarm was. If it doesn't stop, then there's probably a different alarm somewhere that still does a sound.
