### ISSUE TITLE
securitycraft 1.8.1 for mc 1.7.10

### ISSUE THREAD

**Issue by quentfr21** [Geforce132/SecurityCraft#30]
hello

i got a crash with the logger when he try to get name from an EntityTameable

i got this when my animal try to defend me and pass on the top of an active logger

http://pastebin.com/UjVRLZed

thanks

**Comment by bl4ckscor3** [comment]
That's already fixed.
[See first fix](https://github.com/Geforce132/SecurityCraft/blob/master/Changelog%20v1.8.x.md)
