### ISSUE TITLE
crash with phosphor [1.12.2]

### ISSUE THREAD

**Issue by BSG-Walter** [Geforce132/SecurityCraft#300]
i'm using the last version released a few hours ago, this new update crashes with phosphor
i have other mods too, the problem is just with phosphor

complete log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.2B.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  FutureMC (future-mc-1.12.2-0.2.7.4.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  FastBenchFMLPlugin (FastWorkbench-1.12.2-1.7.3.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 12/19/21 4:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 437328480 bytes (417 MB) / 1567096832 bytes (1494 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version               | Source                                        | Signature                                |
	|:----- |:-------------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                  | 1.12.2                | minecraft.jar                                 | None                                     |
	| LC    | mcp                        | 9.42                  | minecraft.jar                                 | None                                     |
	| LC    | FML                        | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                      | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy          | 1.0.0                 | minecraft.jar                                 | None                                     |
	| LC    | micdoodlecore              |                       | minecraft.jar                                 | None                                     |
	| LC    | openmodscore               | 0.12.2                | minecraft.jar                                 | None                                     |
	| LC    | foamfixcore                | 7.7.4                 | minecraft.jar                                 | None                                     |
	| LC    | obfuscate                  | 0.4.2                 | minecraft.jar                                 | None                                     |
	| LC    | securitycraft              | v1.9                  | [1.12.2] SecurityCraft v1.9.jar               | None                                     |
	| LC    | aether_legacy              | 1.5.3.2               | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LC    | creativecore               | 1.10.0                | CreativeCore_v1.10.69_mc1.12.2.jar            | None                                     |
	| LC    | ambientsounds              | 3.0                   | AmbientSounds_v3.1.7_mc1.12.2.jar             | None                                     |
	| LC    | architecturecraft          | @VERSION@             | architecturecraft-1.12-3.98.jar               | None                                     |
	| LC    | baubles                    | 1.5.2                 | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LC    | bookshelf                  | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | jei                        | 4.16.1.302            | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LC    | botania                    | r1.10-364             | Botania r1.10-364.4.jar                       | None                                     |
	| LC    | carryon                    | 1.12.3                | carryon-1.12.2-1.12.6.20.jar                  | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LC    | ctm                        | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LC    | chisel                     | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LC    | chiselsandbits             | 14.33                 | chiselsandbits-14.33.jar                      | None                                     |
	| LC    | geckolib3                  | 3.0.11                | geckolib-forge-1.12.2-3.0.12.jar              | None                                     |
	| LC    | phosphor-lighting          | 1.12.2-0.2.6          | phosphor-1.12.2-0.2.6+build50-universal.jar   | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LE    | cqrepoured                 | 2.6.2B                | Chocolate_Quest_Repoured-1.12.2-2.6.2B.jar    | None                                     |
	| L     | codechickenlib             | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | None                                     |
	| L     | comforts                   | 1.4.1.3               | comforts-1.12.2-1.4.1.3.jar                   | None                                     |
	| L     | cucumber                   | 1.1.3                 | Cucumber-1.12.2-1.1.3.jar                     | None                                     |
	| L     | cyclopscore                | 1.6.7                 | CyclopsCore-1.12.2-1.6.7.jar                  | None                                     |
	| L     | ebwizardry                 | 4.3.4                 | ElectroblobsWizardry-4.3.4-MC1.12.2.jar       | None                                     |
	| L     | evilcraft                  | 0.10.78               | EvilCraft-1.12.2-0.10.78.jar                  | None                                     |
	| L     | evilcraftcompat            | 1.0.0                 | EvilCraft-1.12.2-0.10.78.jar                  | None                                     |
	| L     | extrautils2                | 1.0                   | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| L     | fastfurnace                | 1.3.1                 | FastFurnace-1.12.2-1.3.1.jar                  | None                                     |
	| L     | fastbench                  | 1.7.3                 | FastWorkbench-1.12.2-1.7.3.jar                | None                                     |
	| L     | fencejumper                | 1.0.5                 | fencejumper-1.12-1.0.5.jar                    | None                                     |
	| L     | foamfix                    | 0.10.14-1.12.2        | foamfix-0.10.14-1.12.2.jar                    | None                                     |
	| L     | forgelin                   | 1.8.4                 | Forgelin-1.8.4.jar                            | None                                     |
	| L     | ftblib                     | 5.4.7.2               | FTBLib-5.4.7.2.jar                            | None                                     |
	| L     | ftbutilities               | 5.4.1.131             | FTBUtilities-5.4.1.131.jar                    | None                                     |
	| L     | cfm                        | 6.3.1                 | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| L     | futuremc                   | 0.2.6                 | future-mc-1.12.2-0.2.7.4.jar                  | None                                     |
	| L     | ic2                        | 2.8.170-ex112         | industrialcraft-2-2.8.170-ex112.jar           | None                                     |
	| L     | galacticraftcore           | 4.0.2.280             | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
	| L     | galacticraftplanets        | 4.0.2.280             | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     |
	| L     | harvest                    | 1.12-1.2.8-25         | Harvest-1.12-1.2.8-25.jar                     | None                                     |
	| L     | waila                      | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| L     | journeymap                 | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| L     | malisiscore                | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| L     | malisisdoors               | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| L     | mcwbridges                 | 1.0.6                 | mcw-bridges-1.0.6b-mc1.12.2.jar               | None                                     |
	| L     | mcwfences                  | 1.0.0                 | mcw-fences-1.0.0-mc1.12.2.jar                 | None                                     |
	| L     | modularvc                  | 1.1.1                 | ModularVoiceChat-1.1.1.jar                    | None                                     |
	| L     | msmlegacy                  | @VERSION@             | MoreSwordsLegacy-1.12.2-1.0.7.jar             | None                                     |
	| L     | mysticalagriculture        | 1.7.5                 | MysticalAgriculture-1.12.2-1.7.5.jar          | None                                     |
	| L     | recipehandler              | 0.13                  | NoMoreRecipeConflict-0.13(1.12.2).jar         | None                                     |
	| L     | opframe                    | 1.4.0                 | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar       | None                                     |
	| L     | openmods                   | 0.12.2                | OpenModsLib-1.12.2-0.12.2.jar                 | None                                     |
	| L     | openblocks                 | 1.8.1                 | OpenBlocks-1.12.2-1.8.1.jar                   | None                                     |
	| L     | performant                 | 1.12.2-1.5            | performant-1.11 (1).jar                       | None                                     |
	| L     | placebo                    | 1.6.0                 | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| L     | playerrevive               | 1.0                   | PlayerRevive_v1.2.40_mc1.12.2.jar             | None                                     |
	| L     | xreliquary                 | 1.12.2-1.3.4.796      | Reliquary-1.12.2-1.3.4.796.jar                | None                                     |
	| L     | rustic                     | 1.1.7                 | rustic-1.1.7.jar                              | None                                     |
	| L     | silentlib                  | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar               | None                                     |
	| L     | stupidthings               | 1.1.6                 | Stupid+Things-1.12.2-1.1.6.jar                | None                                     |
	| L     | theaurorian                | 1.12.2-Release        | theaurorian-1.12.2-release-may3021.jar        | None                                     |
	| L     | tlauncher_custom_cape_skin | 1.4                   | tlskincape_1.12.2-1.4.jar                     | None                                     |
	| L     | tombstone                  | 4.5.1                 | tombstone-4.5.1-1.12.2.jar                    | None                                     |
	| L     | torchbandolier             | 0.1.1                 | TorchBandolier-1.12.2-0.1.1-4.jar             | None                                     |
	| L     | torchmaster                | 1.8.4.84              | torchmaster_1.12.2-1.8.4.84.jar               | None                                     |
	| L     | travelersbackpack          | 1.0.35                | TravelersBackpack-1.12.2-1.0.35.jar           | None                                     |
	| L     | traverse                   | 1.6.0                 | Traverse-1.12.2-1.6.0-69.jar                  | None                                     |
	| L     | uteamcore                  | 2.2.5.147             | u_team_core-1.12.2-2.2.5.147.jar              | None                                     |
	| L     | unloader                   | 1.2.0                 | unloader-1.2.0.jar                            | None                                     |
	| L     | usefulbackpacks            | 1.5.4.85              | useful_backpacks-1.12.2-1.5.4.85.jar          | None                                     |
	| L     | variedcommodities          | 1.12.2                | VariedCommodities_1.12.2.jar                  | None                                     |
	| L     | vehicle                    | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                 | None                                     |
	| L     | midnight                   | 0.3.5                 | themidnight-0.3.5.jar                         | None                                     |
	| L     | mysticallib                | 1.12.2-1.13.0         | mysticallib-1.12.2-1.13.0.jar                 | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.2B.jar)
  team.cqr.cqrepoured.asm.CQRClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FutureMC (future-mc-1.12.2-0.2.7.4.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
FastBenchFMLPlugin (FastWorkbench-1.12.2-1.7.3.jar)
  shadows.fastbench.asm.FastBenchTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by bl4ckscor3** [comment]
Use this file I just uploaded, it does not ship mixin and requires either MixinBootstrap, or another mod that loads mixin (like Phosphor). https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3573460
