### ISSUE TITLE
[1.16.5] Mixin Crash during early loading

### ISSUE THREAD

**Issue by Darkmega18** [Geforce132/SecurityCraft#301]
I get this crash when loading with the latest version [1.16.5] SecurityCraft v1.9.jar.
[crash-2021-12-20_18.27.37-client.txt](https://github.com/Geforce132/SecurityCraft/files/7743284/crash-2021-12-20_18.27.37-client.txt)

I have... a lot of mods in relation to my modpack: _Order of All Creation: Relic hunters_ when updating securitycraft on it's latest current version this occurs. 

Edit: A coder friend says it's a Magnesium conflict? Should I cross report this to magnesium or is it something you can fix?

**Comment by bl4ckscor3** [comment]
It's something we would need to fix, as Magnesium completely replaces a piece of vanilla code that we want to modify. We'd have to make it compatible with Magnesium . For now, SecurityCraft v1.9 and Magnesium are incompatible.

**Comment by Darkmega18** [comment]
probably not something I can do if I want to have the update in a modpack unfortunately, cause curseforge would probably detect any weirdness? and even if it doesn't, it'll just download the original for everyone else and blow up again.

**Comment by bl4ckscor3** [comment]
You're right, that solution is not viable for modpacks. I uploaded an additional jar file that applies the modification I mentioned in my previous comment. https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3573460

**Comment by Darkmega18** [comment]
Thank you. :D 
for clarification, it only causes issues with viewing remote cameras from a longway off while moving?
So like... if you decide to check your cameras while casually riding minecarts sorta moving? and your base is a few hundred blocks in the opposite direction kinda long range?

**Comment by bl4ckscor3** [comment]
From what I am aware of, that is correct.
