### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by lazytspo** [Geforce132/SecurityCraft#302]
Owner of SecurityCraft. it is best for you to do the following:

A creation of 1.18 version of SecurityCraft.
An intergration to Fabric.

i will give you credit if you do what the following saids.

**Comment by Geforce132** [comment]
1.18 port: we are already working on a 1.18 port, [see the 1.18.1 branch of this repository].(https://github.com/Geforce132/SecurityCraft/tree/1.18.1)
Fabric version: currently, we do not have the resources to maintain a Fabric version of this mod nor the knowledge that Fabric supports all of the features that SecurityCraft adds/uses. We are not saying that it will _never_ happen, but definitely not in the near future.
