### ISSUE TITLE
Projector in projector crashes client on 1.18.1 forge

### ISSUE THREAD

**Issue by antiLimitGit** [Geforce132/SecurityCraft#304]
### Reproducing the bug
Step 1: Run Forge version 39.0.9 1.18.1, Have SecurityCraft 1.9.0.2-beta1.
Step 2: Create a new world and place down a projector anywhere.
Step 3: Set the projecting item to be another projector.

### Results
The client crashes and the world can not be loaded with the projector.
The crash report is shown [here](https://gist.github.com/antiLimitGit/ae472f6011ff06a3ed79c41c5f813c09)

**Comment by bl4ckscor3** [comment]
Fixed by dc60f177231116afe8afed1a9df608209aed332d 0a9cc3d03c175a2eafcd40edf8879d3130b43f1f 345a3dd0be0a95e6da7dfd6d05a61c94f5471ae2 614352ed84f120bc144f4a4ebecaa9f19302e7b8
