### ISSUE TITLE
Assets license

### ISSUE THREAD

**Issue by AFCMS** [Geforce132/SecurityCraft#307]
I tried to search around the repository and didn't find any textures and models related license.

I would like to use these assets to make an open source porting of this mod to another Minecraft inspired game.

**Comment by bl4ckscor3** [comment]
This covers the whole project. https://github.com/Geforce132/SecurityCraft/blob/1.17.1/LICENSE

Someone else made a Minecraft: Bedrock Edition port of the mod, and this is what our texture artist said in regards to using his assets: ![Screenshot_20220103-103452-933](https://user-images.githubusercontent.com/5149876/147916305-c1987dec-35f2-4640-ba20-615c4b4c3537.png)

**Comment by AFCMS** [comment]
Thank you very much!
That will help me a lot!
