### ISSUE TITLE
1.12.2 Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by Coolkc456** [Geforce132/SecurityCraft#308]
As the name suggests, the version 1.9.0.2 for Minecraft 1.12.2 is incompatible with 1.12.2 Pixelmon or SpongeForge version 2838-7.4.4. I doubt this will get any fixes, but I figured I should report it anyway in case another player has the issue because it took me hours to pin point which mod was doing this out of an 80 mod modpack.

For some reason, the error doesn't say anything related to Security Craft but instead talks about Pixelmon berries and Pixelmon world gen. But things rarely clash with Pixelmon which is why it could be linked to SpongeForge and it just spits out Pixelmon errors since a lot of Pixelmon sidemods rely on SpongeForge (some of which I have installed). The reason how I know it's Security Craft despite the errors being vague is because in order to find what mod was causing the crash, I had to remove each mod one at a time and restart the server 10 times until it no longer crashed because the crash didn't happen every time - just very frequently. After getting the server to generate a new world 10 times successfully after removing Security Craft, I tried adding it again and instantly resulted in another crash the next time I attempted to generate a world. The crash is highly replicable when adding Security Craft. It's very strange.

Server log: https://pastebin.com/KeFeSVsn
Crash log: https://pastebin.com/QvJdjQm0

Without Security Craft installed:
Server log: https://pastebin.com/2bih7V84

**Comment by bl4ckscor3** [comment]
From what I can see - and I could be wrong - the incompatibility lies with SpongeForge. Pixelmon is just the mod that triggerd it, it could be other mods as well. I am not quite sure why this would happen, as the affected code is not touched by SecurityCraft and thus nothing we do should change the outcome. The fact that this does not happen every time sounds like a race condition where one thing runs before the other during the times it works, and the other way around during those where the crash occurs. This can only really happen when a mod is modifying the same code that crashes, which, as I've already said, SecurityCraft does not. We'll be doing some testing on our own to see if we can fix this.

**Comment by Coolkc456** [comment]
Thanks for doing some testing! It's nice to see that some mod developers don't give up or ignore mods on the older builds. Hope you can figure out what's causing the weird crashes. Security Craft is a nostalgic favorite of mine. Good luck.

**Comment by bl4ckscor3** [comment]
You should be able to use the additional file we publish with each 1.12.2 file to prevent the issue. This additional file does not contain mixin, and from my testing it does work. Please report back whether it does for you. Tested with spongeforge-1.12.2-2838-7.4.7 on Forge 14.23.5.2860. https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3577171

Sorry that this simple solution took so long, it should have been something to test right off the bat.

**Comment by Coolkc456** [comment]
Works like a charm. Thanks!
