### ISSUE TITLE
Make an Official Wiki, Please!

### ISSUE THREAD

**Issue by CLtheman1** [Geforce132/SecurityCraft#315]
The Wiki tab here in GitHub just tells you to look at the in-game manual. What about people who can't play MC? What about those who have fallen from being able to play MC due to increased system requirements? Those people may want to go to an official wiki with updated information and pictures. Please give us that.

**Comment by MAGA2233** [comment]
Why would they need information on the mod if they cant play Minecraft? And they can easily just join the support discord server. [https://discord.gg/U8DvBAW](url)

**Comment by bl4ckscor3** [comment]
The GitHub wiki is now updated to contain the infor the SecurityCraft Manual contains. Please keep in mind, that it is automatically generated, and the manual may visualize things (like recipes) better than the wiki does.

**Comment by CLtheman1** [comment]
> Why would they need information on the mod if they cant play Minecraft?
It would be out of curiosity, mostly. Also, if they were to get a new computer in the future and play SecurityCraft on it, it may be handy to know the stuff beforehand.
