### ISSUE TITLE
Placing a Sonic Security System inside of any replaceable block crashes the game

### ISSUE THREAD

**Issue by 4winyt** [Geforce132/SecurityCraft#316]
Placing a Sonic Security System inside of any replaceable block (like grass, ferns, dead bushes, etc...) crashes the game on both the latest 1.17.1 and 1.18.1 releases with this error:
```
java.lang.NullPointerException: Cannot invoke "net.geforcemods.securitycraft.blockentities.SonicSecuritySystemBlockEntity.transferPositionsFromItem(net.minecraft.nbt.CompoundTag)" because the return value of "net.minecraft.world.level.Level.m_7702_(net.minecraft.core.BlockPos)" is null
```
The error consistently happened and crashed my game multiple times. The Sonic Security System, however, was actually placed in the world.

**Comment by RedstoneDubstep** [comment]
Could you please send the full crash report? From the single line you gave us, we can only see what happens but not where in the code it happens, while the full crash report mentions it (and many other things) to let us have an easier time fixing the crash

**Comment by 4winyt** [comment]
Ah, I'm sorry. Here it is
[crash-2022-02-24_13.33.32-client.txt](https://github.com/Geforce132/SecurityCraft/files/8137051/crash-2022-02-24_13.33.32-client.txt)
