### ISSUE TITLE
Bug about Security Camera

### ISSUE THREAD

**Issue by MCTF-Alpha-27** [Geforce132/SecurityCraft#317]
I can see myself in the Security Camera when I first opened the game, but when I quit the Security Camera, no matter how I use it again, I can't see myself any longer

**Comment by bl4ckscor3** [comment]
Which Minecraft version are you using?

**Comment by MCTF-Alpha-27** [comment]
Sorry, Minecraft version 1.12.2 and the mod version 1.9.0.2

**Comment by bl4ckscor3** [comment]
Thank you. There _might_ be a fix for this in v1.9.1 of SecurityCraft. We will release that version once Forge for Minecraft 1.18.2 is more stable (no ETA). Once it's available, please try it out and report back.
