### ISSUE TITLE
Change UUID offline to online.

### ISSUE THREAD

**Issue by Loowop** [Geforce132/SecurityCraft#318]
Does the file exist in 1.7.10 where I have registered the uuid to which the reinforced blocks belong? Or does the mod call the uuid of some .json?

It happens that I made a server in offline mode (not premium) for a long time and now I want to change it to premium, it happens that the blocks are not inherited by nick and, therefore, the uuid to which it belongs is not updated, my goal is to try to find some file where you have the "playerdata" type information in which you can manually change the uuid and inherit the hardened blocks to their owners who will now be online.

Is this possible? I reiterate, I am in version 1.7.10.

Translate by google, original:

¿Existe el archivo en la 1.7.10 donde tenga registrado la uuid a la que pertenecen los bloques reforzados? O bien ¿el mod llama a la uuid de algún .json?

Pasa que hice un server en modo offline (no premium) durante un tiempo largo y ahora lo quiero cambiar a premium, pasa que los bloques no se heredan por nick y, por tanto, no se actualiza la uuid a la que pertenece, mi objetivo es tratar de encontrar algún archivo donde tenga la información tipo "playerdata" en la que pueda cambiar manualmente la uuid y heredar los bloques reforzados a sus dueños que ahora estarán en online.

¿Es posible esto? Reitero estoy en la versión 1.7.10.

**Comment by bl4ckscor3** [comment]
The UUID is saved in the region files, just like any other tile entity data.
