### ISSUE TITLE
SecurityCraft crashes.

### ISSUE THREAD

**Issue by Ollix27** [Geforce132/SecurityCraft#319]
I was on version 1.18.1, and when i placek a block in the projector it crashed.
It showed this crash log:
The game crashed whilst tesselating block in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.BlockEntity.m_58900_()" because the return value of "net.minecraft.world.level.BlockAndTintGetter.m_7702_(net.minecraft.core.BlockPos)" is null
End code: -1

**Comment by bl4ckscor3** [comment]
Known and already reported issue. It's fixed in the next version.
