### ISSUE TITLE
SecurityCrast crashes

### ISSUE THREAD

**Issue by Ollix27** [Geforce132/SecurityCraft#320]
1.18.1 crashes when i put cage block on projector
The game crashed whilst tesselating block in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.BlockEntity.m_58900_()" because the return value of "net.minecraft.world.level.BlockAndTintGetter.m_7702_(net.minecraft.core.BlockPos)" is null
end code: -1

**Comment by bl4ckscor3** [comment]
Please do not create duplicate issue reports. I already told you that the other one was a duplicate and is already fixed.
