### ISSUE TITLE
Crash when putting a cage block in a projector

### ISSUE THREAD

**Issue by jabko12311** [Geforce132/SecurityCraft#322]
if i put a cage block in a projector the game instantly crashes and everytime i open the world it crashes again
the crash message is: The game crashed whilst tesselating block in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.BlockEntity.m_58900_()" because the return value of "net.minecraft.world.level.BlockAndTintGetter.m_7702_(net.minecraft.core.BlockPos)" is null

**Comment by bl4ckscor3** [comment]
Which SecurityCraft version are you using?

**Comment by jabko12311** [comment]
1.18.1

**Comment by bl4ckscor3** [comment]
Update to SecurityCraft v1.9.1 and report back if that fixes your issue.

**Comment by jabko12311** [comment]
yeah it doesnt happen in the 1.9.1 version

**Comment by bl4ckscor3** [comment]
All right, then I'm closing this as fixed.
