### ISSUE TITLE
Zooming when mounted to a Security Camera does not work after rebinding keys

### ISSUE THREAD

**Issue by sashaironfist** [Geforce132/SecurityCraft#323]
My version: [1.12.2]+SecurityCraft+v1.8.23.2

I opened a security camera, and I set the controls of zooming in to up and down arrow keys, but when i tried zooming in or out it didn't work, so plz help

**Comment by bl4ckscor3** [comment]
The version you are using is outdated. Please [update the mod](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3696865) and report back whether the issue still happens.

**Comment by sashaironfist** [comment]
it's still not fixed i'm on the [1.12.2]+SecurityCraft+v1.9.1+(No+Mixin) version now

**Comment by bl4ckscor3** [comment]
Ok. I tried it out myself, and using the up and down arrows to zoom in and out works just fine for me. Do you have these keys bound to something else as well perhaps?

**Comment by sashaironfist** [comment]
No i don't

**Comment by sashaironfist** [comment]
I just checked

**Comment by bl4ckscor3** [comment]
Can you please send the complete list of other mods you have installed? It could be a conflict.

**Comment by sashaironfist** [comment]
how exactly?

**Comment by bl4ckscor3** [comment]
Take images of the mods folder and post them here, or list them manually here, I don't know.... Whatever works best for you.

**Comment by sashaironfist** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/97107514/159918940-736fd829-600d-45b8-aafa-048374ea1f3e.png">

**Comment by sashaironfist** [comment]
Do you know what's wrong?

**Comment by sashaironfist** [comment]
do you know if there is a conflict or what mod it is?

**Comment by sashaironfist** [comment]
oh

I guess its fine
