### ISSUE TITLE
Issue with Little Tiles mod when entering a security camera

### ISSUE THREAD

**Issue by TheCraftedGamer** [Geforce132/SecurityCraft#324]
when using security craft and little tiles at the same time there's an issue with using the cameras.

1.12.2 forge 14.23.5.2860 SecurityCraft v1.9.1
I've made a door with a button. pressing the button slides the door up ~ little tiles
having door active(up/open), entering a camera deloads the door while the button is still there. ~ security craft x little tiles

problem, I don't know which mod is fully responsible for the issue and I haven't found any other reports of this issue.

**Comment by TheCraftedGamer** [comment]
this seems kinda related to the other camera issues

**Comment by bl4ckscor3** [comment]
Can you show a video please? I have not worked or played with Little Tiles yet, so have little to go on here. It could be related to #321 and/or #317, but that depends on how Little Tiles works internally. It's also hard to figure out those kind of issues, since we can't quite reproduce them ourselves.

**Comment by TheCraftedGamer** [comment]
> Can you show a video please? I have not worked or played with Little Tiles yet, so have little to go on here. It could be related to #321 and/or #317, but that depends on how Little Tiles works internally. It's also hard to figure out those kind of issues, since we can't quite reproduce them ourselves.

yeah ill get that in a bit

**Comment by TheCraftedGamer** [comment]
> Can you show a video please? I have not worked or played with Little Tiles yet, so have little to go on here. It could be related to #321 and/or #317, but that depends on how Little Tiles works internally. It's also hard to figure out those kind of issues, since we can't quite reproduce them ourselves.

https://user-images.githubusercontent.com/65487821/160826828-aefc5f18-ba59-46c9-9a09-9125e9615cfe.mp4

**Comment by fabegalo** [comment]
Vehicle-mod Mod Players and Vehicles also disappear after exiting the camera!

**Comment by TheCraftedGamer** [comment]
hey i found the last version it worked on before this bug appeared
[1.12.2] SecurityCraft v1.8.23.2.jar works and doesn't deload the doors
[1.12.2] SecurityCraft v1.9.jar and above deloads the doors.
