### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by ILAIGG** [Geforce132/SecurityCraft#326]
When I try to open minecraft (with various mods) I get the following error:
![image](https://user-images.githubusercontent.com/65608178/162014403-31171511-19d3-490b-aed1-c0e4c122cba9.png)

Minecraft version: 1.12.2
Forge version: 14.23.5.2855
SecurityCraft version: From 1.9 onwards, versions lower than 1.9 do not give me the error.

This is the crash report (there is also the list of mods I use):
https://pastebin.com/AKDqJQB9

How am I sure it is SecurityCraft?
Because when the error occurred, I tried the mods one by one, until I tried SecurityCraft, and then I got the error.

**Comment by bl4ckscor3** [comment]
Update SecurityCraft to v1.9.1, but [use the additional file](https://i.imgur.com/fWzbQjh.png) that is added on CurseForge, not the main one.
If that does **not** work, install [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility).
