### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by KniteRider** [Geforce132/SecurityCraft#329]
Can you please make it so mutable alarms can be activated at once?

**Comment by bl4ckscor3** [comment]
What do you mean by "mutable alarms"?

**Comment by KniteRider** [comment]
sorry i meant that i want to have the option to connect alarms with redstone or something so i can turn on more then one alarm at a time

**Comment by bl4ckscor3** [comment]
Just hook up multiple alarms to the same line of redstone.
