### ISSUE TITLE
Is Retinal Scanner really Retinal Scanner ?

### ISSUE THREAD

**Issue by Rinko1231** [Geforce132/SecurityCraft#330]
Retinal Scanner used to be translated as "虹膜扫描仪( Iris Scanner)" in Chinese, and serveral days ago we found it was absolutely wrong.
So we decided to correct it to "视网膜扫描仪（Retinal Scanner）".
However someone questioned that "maybe what the author really wanted is just **Iris Scanner**, you should ask him/her", so I am here to ask Is Retinal Scanner really Retinal Scanner ?
Sorry for this confusing issue.

**Comment by Geforce132** [comment]
Hi,

Yes, the retinal scanner is meant to be a [retinal scanner](https://en.wikipedia.org/wiki/Retinal_scan), not an iris scanner. After looking on Wikipedia, I found out that iris scanners are a thing, but we intend for the scanner to be scanning retinas, not irises. 

Side note: if you or someone you know is a fluent Chinese speaker, we'd love for them to help to make an official Chinese translation for SecurityCraft that would ship with the mod. Chinese is definitely a big language that we don't support as of right now.
