### ISSUE TITLE
Can't remove owned security camera

### ISSUE THREAD

**Issue by ndma-ucsc** [Geforce132/SecurityCraft#334]

**Comment by Geforce132** [comment]
What version of Minecraft and SecurityCraft are you using? Did you place down the camera in the first place? Are you trying to remove it with the Universal Block Remover? Do you get an error message when trying to remove it? We can't help you much without more information.

**Comment by ndma-ucsc** [comment]
Ah my bad the description didn't save. But it's on ATM7. Didn't realize there was a Universal Block Remover.
