### ISSUE TITLE
Adding the ability to disable security equipment

### ISSUE THREAD

**Issue by sasdallas** [Geforce132/SecurityCraft#335]
I have a suggestion that you should be able to turn off any security equipment, like cameras, turrets, etc. One of the ways you could do this is possibly by adding a redstone module and maybe toggling a setting in the Universal Block Modifier or something, so that when it was not receiving a redstone signal, it would shut off. It doesn't have to be that way, though.

When the cameras were shut down, when you try to access the feed, it could display some sort of "VIDEO ERROR" message.

This is all just a suggestion, and it doesn't have to be my way.

**Comment by sasdallas** [comment]
Add-on: You could also make the cameras be able to be destroyed, and repaired with a certain tool.

**Comment by bl4ckscor3** [comment]
Sorry for the late reply, I missed this somehow. The Sentry can already be disabled (Idle mode), and there are already universal block modifier options for _some_ blocks to disable them. I'll go through our blocks and add such an option where it makes sense.
