### ISSUE TITLE
[1.18.2] Server crash when breaking a Furnace from Iron Furnaces.

### ISSUE THREAD

**Issue by Gbergz** [Geforce132/SecurityCraft#336]
Title^

Users have reported in my modpack that breaking a furnace from Iron Furnaces mod together with SecurityCraft crashes the server.

## Versions:
Forge:  40.1.48
Minecraft: 1.18.2
SecurityCraft: 1.9.2

**Crash-Report**: https://gist.github.com/Gbergz/2a553896bdfc7054366cc8b07ddd9d80

**Comment by bl4ckscor3** [comment]
Looking at the code of that mod, I'd argue it's a bug they need to fix. They need to check whether the block entity they are querying is actually the one they expect it to be. This crash could happen with many blocks, even vanilla ones. Report this to them, this is not on us to fix.
Line in question that needs a check for BlockMillionFurnaceTile before casting: https://github.com/Qelifern/IronFurnaces/blob/1.18.2/src/main/java/ironfurnaces/blocks/furnaces/BlockIronFurnaceBase.java#L262

**Comment by Qelifern** [comment]
ironfurnaces-1.19.2-3.6.3 implements a cast check, bad miss there, hope it does fix it.
