### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by alankasprzyk23** [Geforce132/SecurityCraft#338]
SecurityCraft crashes my MC everytime and whenever I take it out, it stops crashing. Can someone tell me what the issue is?

Error:

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
Exit Code: -1

Log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_22.9.2_Forge_1.12.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 6/18/22 3:17 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 574309656 bytes (547 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version               | Source                                        | Signature                                |
	|:----- |:------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft           | 1.12.2                | minecraft.jar                                 | None                                     |
	| LC    | mcp                 | 9.42                  | minecraft.jar                                 | None                                     |
	| LC    | FML                 | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge               | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | micdoodlecore       |                       | minecraft.jar                                 | None                                     |
	| LC    | xaerominimap_core   | 1.12.2-1.0            | minecraft.jar                                 | None                                     |
	| LC    | obfuscate           | 0.4.2                 | minecraft.jar                                 | None                                     |
	| LC    | securitycraft       | v1.9.2                | [1.12.2]+SecurityCraft+v1.9.2.jar             | None                                     |
	| LC    | aroma1997core       | 2.0.0.2               | Aroma1997Core-1.12.2-2.0.0.2.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | jei                 | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LC    | quark               | r1.6-179              | Quark-r1.6-179.jar                            | None                                     |
	| LC    | autoreglib          | 1.3-32                | AutoRegLib-1.3-32.jar                         | None                                     |
	| LC    | backpack            | 3.0.2                 | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| LC    | forgelin            | 1.8.3                 | Forgelin-1.8.3.jar                            | None                                     |
	| L     | betterportals       | 0.3.7.7               | betterportals-0.3.7.7.jar                     | None                                     |
	| L     | biomesoplenty       | 7.0.1.2445            | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| L     | mantle              | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| L     | tconstruct          | 1.12.2-2.13.0.183     | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| L     | galacticraftcore    | 4.0.2.280             | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
	| L     | malisiscore         | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| L     | malisisdoors        | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| L     | malisisswitches     | 1.12.2-5.1.0          | malisisswitches-1.12.2-5.1.0.jar              | None                                     |
	| L     | cdm                 | 0.4.1                 | MrCrayfish_DeviceMod_1.12.2.jar               | None                                     |
	| L     | cfm                 | 6.3.0                 | MrCrayfish_FurnitureMod_1.12.2.jar            | None                                     |
	| L     | cgm                 | 0.15.3                | MrCrayfish_GunMod_1.12.2.jar                  | None                                     |
	| L     | vehicle             | 0.44.1                | MrCrayfish_VehicleMod_1.12.2.jar              | None                                     |
	| L     | toolbelt            | 1.9.14                | ToolBelt-1.12.2-1.9.14.jar                    | None                                     |
	| L     | veinminer           | 0.38.2                | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| L     | veinminermodsupport | 0.38.2                | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| L     | xaerominimap        | 22.9.2                | Xaeros_Minimap_22.9.2_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
XaeroMinimapPlugin (Xaeros_Minimap_22.9.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce RTX 3060/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

**Comment by bl4ckscor3** [comment]
Please try using the additional file uploaded alongside SecurityCraft 1.12.2 and report back if that fixes this for you. https://i.imgur.com/8lEET5J.png

**Comment by alankasprzyk23** [comment]
> Please try using the additional file uploaded alongside SecurityCraft 1.12.2 and report back if that fixes this for you (replace the mod file with this one). ![](https://camo.githubusercontent.com/a4f98fa57bfebde1c1d4174ab603f14cfc0d50b3409f9225409061841d088b50/68747470733a2f2f692e696d6775722e636f6d2f386c454554354a2e706e67)

Ok it worked,
Thanks!
