### ISSUE TITLE
please add "Crafteable The Universal Owner Changer?"=true/false

### ISSUE THREAD

**Issue by AkaoniNanashi** [Geforce132/SecurityCraft#340]
Hello!

I really like the mod, but i need able or unable the Universal Owner Changer because i dont want just this item on the server.
if can help me with that will be really nice. 

im with 1.12.2

**Comment by bl4ckscor3** [comment]
You can use 3rd party mods like [Craft Tweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker) or [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs) to remove crafting recipes. They are both available for 1.12.2.
