### ISSUE TITLE
Make taser effects configurable

### ISSUE THREAD

**Issue by TheCraftedGamer** [Geforce132/SecurityCraft#341]
I'm using version 1.8.23.2 on 1.12.2
I was wondering if there was a config or in-game way of changing the conditions of the taser. I wanted to change the recharge and stun time and maybe the damage and afflictions(effects).

**Comment by bl4ckscor3** [comment]
I'm not sure about changing the specific effects that are applied (weakness, slowness, etc.), but the time and strength of the effects can definitely be put into the config file no problem.
