### ISSUE TITLE
Compatibility with WTHIT (fork of HWYLA) for 1.18+

### ISSUE THREAD

**Issue by Batimius** [Geforce132/SecurityCraft#342]
Hello there. I am currently using Security Craft in a server with some friends, but it doesn't seem to be compatible with WTHIT. I know that HWYLA used to be compatible since I've used it before, but since HWYLA is no longer maintained, a new mod, WTHIT, was introduced to fill in the gap. That being said, combability with this mod would be very useful. This mod is a fork of HWYLA, so I assume the API is relatively the same.

**Comment by bl4ckscor3** [comment]
See the comment I just posted. You can also check for yourself by clicking on the commit text, then checking which branch the commit is for. We use branches to differentiate between Minecraft versions, so for every Minecraft version that we add a feature for, there is one commit.
