### ISSUE TITLE
Suggestion: Un-Reinforcing the Reinforced Materials!

### ISSUE THREAD

**Issue by CTH999** [Geforce132/SecurityCraft#345]
So, I think there should be a config option that allows you to make reinforced blocks breakable to all, just very strong. the idea being that they have a structure that makes it resistive to all but the owner. So, blast proof, but to the owner miningspeed of the block. everyone else has 2 times the mining speed of obsidion! Bit more realisim.

In conjuction with my [Power consuption Sugestion](https://github.com/Geforce132/SecurityCraft/issues/344), the reinforced blocks could be slightly harder to all, but not be reinforced to anything but explosives (Not harder for people besides the owner), but they require power to do that! THe idea being that it's an "Adaptive Crystal lattice absorbs force to make it harder to break" (Such a thing could work IRL), but without power it can't function. That, however, would need to be a config option, probally defaulting to "off", as I bet many people wouldn't like it. But, people trying to make a PvP modpack would find it useful, as it will make PvP possible

However, that is just my idea. Ultimitly, it's your decision!

**Comment by bl4ckscor3** [comment]
Sorry, reinforced blocks will stay as they are. Also, changing a core functionality in the mod like this is not feasible to old worlds.

**Comment by CTH999** [comment]
Ok-ee. Fair enough!

**Comment by bl4ckscor3** [comment]
Please do not re-close the issue that I have already closed.

**Comment by bl4ckscor3** [comment]
Hey - I'm just writing here to let you know that after lots of internal discussion, the next version of the mod will make SecurityCraft's blocks breakable with normal vanilla tools by the owner. It's still not possible to break someone else's blocks by default, however there is a config setting to turn that on as well as set a breaking speed slowdown factor, which controls how much longer breaking someone else's block is.
