### ISSUE TITLE
Mod Conflict with Create Computing

### ISSUE THREAD

**Issue by Foxydapirate12** [Geforce132/SecurityCraft#347]
I'm currently using the latest 1.18.2 version of the mod with forge 40.1.68.
It crashes on the loading screen
Here's the crash report: https://gist.github.com/Foxydapirate12/5c09dd67a22e29faed3a71f5c1b926ef

**Comment by bl4ckscor3** [comment]
I can't seem to reproduce the crash with [these mods](https://i.imgur.com/CoyVSGs.png) and Forge 40.1.68 installed. Could you please provide a minimal example (the fewest mods where this crash is reproducible) of when this happens?

**Comment by Foxydapirate12** [comment]
Yea sure, i'll do it a bit later though

**Comment by bl4ckscor3** [comment]
If this still happens with v1.9.4, please send the new log and reopen the issue.
