### ISSUE TITLE
disguise module for reinforced blocks

### ISSUE THREAD

**Issue by githubpub900** [Geforce132/SecurityCraft#349]
i want to disguise reinforced blocks, because me and my friend are making a base with our own custom mod that adds in new blocks, we want to reinforce them, i think making the disguise module for reinforced blocks would be amazing so we can have custom reinforced blocks. thanks, i hope you guys understand this and add it in.

**Comment by githubpub900** [comment]
is there anyway to disguise reinforced blocks?

**Comment by bl4ckscor3** [comment]
No. There are already a bunch of reinforced blocks, both in type, and existing in the world when placed down. Adding a disguise module to all of them is wasteful and does not make sense. 
Creating reinforced variants of modded blocks is left to the mods which add those blocks, or specially made addon mods.

**Comment by CoderQCFromScraatch** [comment]
i am a mod maker and i think i can do it

**Comment by githubpub900** [comment]
thanks
