### ISSUE TITLE
turrets dont work

### ISSUE THREAD

**Issue by jjmarshal** [Geforce132/SecurityCraft#351]
hi, im playing in a server with some friends and we add to our modpack the security craft mod for 1.16.5. however despite that the mod load correctly the turrets dont fire to anything a d I need that they attack to mobs and the other players haha. I came here to ask if i can do somerhing to solve it or it just buged?
thank you in advance.

**Comment by Geforce132** [comment]
Sentries not firing at hostiles was a known bug in SecurityCraft v1.9.3. Update to [v1.9.3.1](https://www.curseforge.com/minecraft/mc-mods/security-craft/files) to fix the issue. If you have any previously placed sentries, right-click them with redstone to get them working.
