### ISSUE TITLE
Bug with reinforced sticky pistons 1.16.5 Security Craft Mod

### ISSUE THREAD

**Issue by alexion562** [Geforce132/SecurityCraft#352]
When I place a reinforced sticky piston and another above it so that both can work at the same time, the reinforced sticky piston below is unable to bring the one on top to its original position.

If there is any doubt about the problem, I can send a video so that it can be seen and understood more easily.

**Comment by Geforce132** [comment]
I tried out [this setup](https://i.imgur.com/GUtsse3.png) with reinforced sticky pistons and it worked just fine. The bottom piston could raise/lower the top piston when the top one wasn't extended and when it was, the bottom had no effect (just like vanilla pistons).

I am playing on 1.16.5 and using Forge 36.2.39 and SecurityCraft v1.9.3.1. If I got the setup wrong, please let me know. If you're using an old version of SecurityCraft, try updating and then check again.
