### ISSUE TITLE
all versions of forge crash

### ISSUE THREAD

**Issue by Gabetheman12** [Geforce132/SecurityCraft#353]
When i try to do the latest 1.18.2 version of forge it crashes, when i install an older version, it crashes. PLEASE HELP.

**Comment by Geforce132** [comment]
We can't help you without the crash report. Please post it here in some way.

**Comment by Gabetheman12** [comment]
ok.
ill try

**Comment by Gabetheman12** [comment]
[crash-2022-08-24_15.55.45-server.txt](https://github.com/Geforce132/SecurityCraft/files/9428375/crash-2022-08-24_15.55.45-server.txt)

**Comment by Gabetheman12** [comment]
its a download for some reason

**Comment by bl4ckscor3** [comment]
Try removing OptiFine.
