### ISSUE TITLE
Is there a way to put camera monitors in item frames?

### ISSUE THREAD

**Issue by Begnom** [Geforce132/SecurityCraft#357]
I mean it in the way that you could see the camera assigned to the monitor on the item frame. I once saw there was a mod that could do that but it was an old mod.

**Comment by bl4ckscor3** [comment]
No, there isn't. This feature is exclusive to the 1.7.10 version of SecurityCraft.

And please note, that we use this issue tracker for bug reports and suggestions, not for general questions about the mod. Please use the #help channel in our Discord server for these kind of questions.
