### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by EDDYBELDUMA150** [Geforce132/SecurityCraft#359]
I already had the Security Craft mod installed on my server, however, recently I had some compatibility issues with other mobs but I finally fixed it. However, when I try to start my server it crashes and shows me the following message:

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.material.FlowingFluid.m_76068_(boolean)" because the return value of "net.minecraft.world.level.block.LiquidBlock.getFluid()" is null
at net.minecraft.world.level.block.LiquidBlock.initFluidStateCache(LiquidBlock.java:182) ~[server-1.19-20220607.102129-srg.jar%23109!/:?]

**Comment by bl4ckscor3** [comment]
Please post the complete crash report.

**Comment by EDDYBELDUMA150** [comment]
https://mclo.gs/LkCK0GS

**Comment by bl4ckscor3** [comment]
A server using SecurityCraft v1.9.3 with Forge 41.1.0 starts just fine for me. Make sure that all the mods that you have installed are known to work on Forge 41.1.0. We are no longer supporting SecurityCraft for Minecraft 1.19, so if this _does_ turn out to be an issue with SecurityCraft, it won't be fixed for this version of Minecraft.
