### ISSUE TITLE
Launching crashes

### ISSUE THREAD

**Issue by Vxd1324** [Geforce132/SecurityCraft#362]
Game fails to launch the server and crashes. https://mclo.gs/o4H9euq

**Comment by Geforce132** [comment]
The AllTheSwords mod is crashing, not SecurityCraft. Remove it and see if that helps.

**Comment by bl4ckscor3** [comment]
Correct. I can recreate this crash even with only AllTheSwords installed and no other mods. ATS is trying to load a file, that is only present on the client, on a server, which will obviously fail. ATS is simply broken on dedicated servers.
