### ISSUE TITLE
 How can I disable the crafting of mines on the server, or deactivate the mines?

### ISSUE THREAD

**Issue by tridoxx** [Geforce132/SecurityCraft#366]
hello everyone, I hope this is good, I love this mod, I made a server to play with my friends, but we want to deactivate the mines, so that they do not harm the experience of other people by filling the land with mines, is there a way to deactivate them? Thanks a lot

**Comment by bl4ckscor3** [comment]
First of all, this is not a help forum. Next time you have a question about using the mod, please join our Discord server and ask in the #help channel.

To answer your question: There is a config option to turn off explosion damage from mines. This will still cause explosions and damage to players and other mobs, however no damage to blocks will occur. You can also remove the recipes with a datapack, or a 3rd party mod like Craft Tweaker or KubeJS, making mines unobtainable. This will not make existing mines stop working.
