### ISSUE TITLE
is this suppose to happen? jade is telling me the password

### ISSUE THREAD

**Issue by CuteCyanGirl** [Geforce132/SecurityCraft#369]
![image](https://user-images.githubusercontent.com/110318666/204051636-74837a0d-c14a-460c-899a-47d7691add25.png)

**Comment by bl4ckscor3** [comment]
What? That the password is shown? Yes. Only you can see that, nobody else can. You can disable that completely by pressing 0 on your numpad (by default, can be changed in the key bind settings) and disabling the option in the securitycraft section in that screen.
