### ISSUE TITLE
DUPE briefcase

### ISSUE THREAD

**Issue by SrRapero720** [Geforce132/SecurityCraft#370]
**VERSION**
- FORGE: 40.1.85
- MINECRAFT: 1.18.2
- SC: [1.18.2] SecurityCraft v1.9.3.1.jar

**NEED**
- Briefcase
- any item
- another any item with high value

**HOW TO REPRODUCE**
- Create a briefcase (any password)
- put valuable item inside
- put other non-valuabe item in your hotbar (example: slot 2)
- place your mouse upside non-valuable item
- press the number where is located briefcase (example: slot 1 - press number 1)
- briefcase get switched slot
- now take briefcase with mouse (now its posible) and remove items from briefcase (interface keeps open)
- close interface menu and reopen briefcase
- now items are on briefcase and your inventory

DUPE SUCCESS.

VIDEO:
<video src="https://user-images.githubusercontent.com/29090346/204108111-b751841a-f480-483f-b5f6-c34446232907.mp4"></video>

**Comment by bl4ckscor3** [comment]
Thanks a lot! This was very clear to follow, making it easy to find the issue. It will be fixed in the next version of the mod.
