### ISSUE TITLE
[1.12.2]Installing with Blue Skies caused a crash.

### ISSUE THREAD

**Issue by Ironnoob73** [Geforce132/SecurityCraft#373]
The crash-report:https://paste.ubuntu.com.cn/4546722

**Comment by bl4ckscor3** [comment]
Blue Skies is broken, they shouldn't be calling internal Forge events. If the mod would still be updated in 1.12.2, I'd say report this issue to them. But it can be mitigated on our side, so I'll reluctantly opt for that.
