### ISSUE TITLE
Security Craft Crashes with Blue Skies

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [Geforce132/SecurityCraft#374]
I downloaded the latest version of Security Craft, the one without Mixin included, and it crashed with Blue Skies.

Minecraft Version: 1.12.2

Forge Version: 14.23.5.2860

Crash Log: (https://paste.ee/p/1Z20F)

Latest Log: (https://paste.ee/p/wTsKp)

Security Craft Version: SC v1.9.4 - No Mixin Included (https://www.curseforge.com/minecraft/mc-mods/security-craft/files/4121629)

Blue Skies Version: 1.12.2-v1.1.3 (https://www.curseforge.com/minecraft/mc-mods/blue-skies/files/2827455)

**Comment by bl4ckscor3** [comment]
Duplicate of #373
