### ISSUE TITLE
sentry is targetting villagers

### ISSUE THREAD

**Issue by alessandriLuca** [Geforce132/SecurityCraft#375]
Hi, im using the security craft v 1.18.2 and apparently the sentry is targetting my villager in all modes. Do you know why?

Thanks!

**Comment by Geforce132** [comment]
I'm assuming that you mean SecurityCraft **for** Minecraft 1.18.2 (there is no 1.18.2 version of SecurityCraft). Do you happen to also have the Improved Mobs mod installed?

If so, try the following solution and see if that helps:
![](https://i.imgur.com/djaBQj4.png)

If not, are you using any other mods? What version of SecurityCraft are you using specifically?

**Comment by alessandriLuca** [comment]
yes that's solved my problem !! thank you ;)
