### ISSUE TITLE
Architectury support?

### ISSUE THREAD

**Issue by SolDev69** [Geforce132/SecurityCraft#376]
This would allow a fabric/quilt version without the annoyance of keeping up two versions of the mod. I know a lot of people have suggested a fabric version in the past, and that this is a small dev team, but moving to architectury would make it easier to have a fabric version without having to support two codebases.

**Comment by bl4ckscor3** [comment]
We are well aware of Architectury and other solutions like MultiLoader. However, it would be a significant undertaking to port the mod to Architectury in the first place. As we have said multiple times in the past, we do not plan a Fabric version, and there won't be one in the foreseeable future.
