### ISSUE TITLE
Suggestion: Technician's Goggles

### ISSUE THREAD

**Issue by TheDoctor1977** [Geforce132/SecurityCraft#377]
These would be configurable through their own menu, and would show advanced info about blocks such as turret/rift stabilizer radiuses and block ownership.

**Comment by bl4ckscor3** [comment]
Such information about sentries and other blocks can be seen by rightclicking with a Universal Block Modifier (for blocks with variable range, you can also see the settings of other options there etc.), as well as using Jade, WTHIT, or The One Probe.

The sentry's range cannot be adjust and is 20 blocks, if I remember correctly.

**Comment by TheDoctor1977** [comment]
> Such information about sentries and other blocks can be seen by rightclicking with a Universal Block Modifier (for blocks with variable range, you can also see the settings of other options there etc.)

I meant showing it as in a toggleable transparent sphere around the block(s), which would be especially helpful for things like rift stabilizers to make sure an entire area is covered.
