### ISSUE TITLE
crash with reborncore

### ISSUE THREAD

**Issue by DAmanc123** [Geforce132/SecurityCraft#379]
[crash-2022-12-24_21.26.31-client.txt](https://github.com/Geforce132/SecurityCraft/files/10300850/crash-2022-12-24_21.26.31-client.txt)
is there any way can fix this?plzzz

**Comment by bl4ckscor3** [comment]
Duplicate of #378. Fixed next update.

**Comment by DAmanc123** [comment]
so how i can fix this bug?i see that dupilcated issue and it pointed to another issue which is about crashing with Blue Skies instead of reborn core

**Comment by bl4ckscor3** [comment]
Like I said, the issue will be fixed in the next update of the mod. The crash with Blue Skies is the same as with Reborn Core.

**Comment by DAmanc123** [comment]
but i once saw a modpack which load these two mods successfully,but it used a old version of this mod instead of the latest,however i still looking forward the next update

**Comment by bl4ckscor3** [comment]
Yes that's because a change we made in SecurityCraft v1.9.4 introduced this incompatibility.

**Comment by DAmanc123** [comment]
ok thank you
