### ISSUE TITLE
cant crafting reinforced stained glasses

### ISSUE THREAD

**Issue by fewfwefef** [Geforce132/SecurityCraft#38]
I cant find a way to craft reinforced stained glasses to make lv2 reinforcer because the glass broke when i use the universal block remover,  
and each time if i want to craft reinforced wood stairs, I have to place the wood block first, use the reinforcer to change it, then use remover to remove it into my inventory, so that i can craft it. 
 version 1.8.0 on mc 1.7.10

**Comment by bl4ckscor3** [comment]
Update to SecurityCraft v1.8.1. There, you can break reinforced glass and get a drop.
