### ISSUE TITLE
Security Craft causes the wireless link  from create working when on lecterns

### ISSUE THREAD

**Issue by badgeminer** [Geforce132/SecurityCraft#381]
Security Craft(v1.9.4) causes the wireless link from the create mod(0.5.0f) from working when on lecterns

**Comment by bl4ckscor3** [comment]
Please provide more info, such as reproduction steps. I have no clue how Create works.

**Comment by bl4ckscor3** [comment]
Closing this due to lack of information and assuming you mean the "Display Link", which does work just fine as shown here (as you can see in the beginning, SecurityCraft is installed): https://cdn.discordapp.com/attachments/318544310461136896/1059194239868743730/2023-01-01_20-37-56.mp4
