### ISSUE TITLE
Crash while trying to access Camera

### ISSUE THREAD

**Issue by Alexkrasscool** [Geforce132/SecurityCraft#384]
when i try to access a camera, my minecraft world crashes. I am using Mincraft 1.19.2 with Vivecraft.
[crash-2022-12-31_03.08.02-client.txt](https://github.com/Geforce132/SecurityCraft/files/10339366/crash-2022-12-31_03.08.02-client.txt)

**Comment by bl4ckscor3** [comment]
This is not an issue with SecurityCraft, but with Vivecraft, as it happens in code modified by that mod. That mod needs to have an instanceof check before this line before casting the camera entity. https://github.com/jrbudda/Vivecraft_119/blob/master/patches/VR/net/minecraft/client/renderer/GameRenderer.java.patch#L547

**Comment by Alexkrasscool** [comment]
Can I fix it myself? And if so, how? No one has answered me on support.

**Comment by bl4ckscor3** [comment]
The only way to fix it yourself is modifying the necessary lines in the code accordingly and build your own version of the mod that you then use.
