### ISSUE TITLE
[Suggestion] A way to toggle the damaging ability of the laser block on the fly

### ISSUE THREAD

**Issue by sciguyryan** [Geforce132/SecurityCraft#386]
Hi there.

It would be fantastic if there were a way to toggle the damaging ability of a laser block on or off on the fly. This could be used to allow a non-whitelisted player through the lasers at one time, whilst disallowing them at a later item.

I had though that this could possibly be done by a module that would enable the lasers when powered by redstone signal and disable when when no signal is present. This would obviously be unable to be used with the current redstone module which serves a different purpose.

I have poked around and I couldn't find anything obvious that would achieve this, if I have missed something then I apologise.

**Comment by bl4ckscor3** [comment]
Rightclick the laser block with a Universal Block Modifier, then click the "Disabled" button on the right.

**Comment by sciguyryan** [comment]
> Rightclick the laser block with a Universal Block Modifier, then click the "Disabled" button on the right, or click the module button of the harming module to disable the module.

If I'm not mistaken, that simply disables the block until it's re-enabled later, correct? As far as I'm able to discern that doesn't allow it to be activated or deactivated on the fly, such as through a redstone signal?

**Comment by bl4ckscor3** [comment]
I'm not sure what you mean by "on the fly" then. What I said is what you can do to turn off the laser block, or just the harming module, temporarily. We cannot have a redstone signal turn off the lasers, because they are already able to emit a redstone signal.
