### ISSUE TITLE
brewing stand - potion wont shift-click to right slot

### ISSUE THREAD

**Issue by PanPatrik** [Geforce132/SecurityCraft#387]
so i was playing on version 1.16.5 and i dont know if it is problem on others version of MC but when i shift- click any potion it will not go to botom where suposed to be but it will go to up it is kinda anoying i do need do get each potion manually into botom slot so if could this be fixed

https://user-images.githubusercontent.com/122175664/212313732-c1b5bc25-df89-4779-aa97-813027d96316.mp4

**Comment by bl4ckscor3** [comment]
That's probably because of the fake liquid recipes, which have potions in the top slot. I'll see what can be done, but no promises.
