### ISSUE TITLE
[Suggestion] FTB Teams Support

### ISSUE THREAD

**Issue by KuryKat** [Geforce132/SecurityCraft#389]
As spoken on the Discord server, for a while, afaik, the SC team has been thinking about making possible to integrate FTB Teams, I thought of creating this issue to track this implementation, hope we can see this happening anytime soon!

I'll be waiting for updates as this integration would really benefit anyone wanting to use this amazing mod in their modpacks, including me!

If possible, I would love to see this implemented in all supported versions, including 1.12 and 1.16!

**Comment by bl4ckscor3** [comment]
I briefly checked out their API the other day, and it doesn't seem too hard to add support for the mod. We'll definitely be looking further into this.

**Comment by KuryKat** [comment]
Perfect! I'll be looking forward to see this happening! 🙌🎉

**Comment by bl4ckscor3** [comment]
All done, and will be in the next update! (v1.9.6)
