### ISSUE TITLE
Freezes when activating surveillance cameras at a distance.

### ISSUE THREAD

**Issue by Suu124** [Geforce132/SecurityCraft#391]
If the user is kicked out of the world during the loading process and re-enters the world, MineCrfat will exit and the following error will be displayed.

I am using this mod in a server environment.
The following are error codes.

The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: class net.geforcemods.securitycraft.entity.camera.CameraController tried to access method 'int net.minecraft.client.multiplayer.ClientChunkCache$Storage.m_104481_(int, int)' (net.geforcemods.securitycraft.entity.camera.CameraController is in module securitycraft@1.9.5 of loader 'TRANSFORMER' @61db86bf; net.minecraft.client.multiplayer.ClientChunkCache$Storage is in module minecraft@1.19.3 of loader 'TRANSFORMER' @61db86bf)

**Comment by bl4ckscor3** [comment]
Please post the complete crash report.

**Comment by Suu124** [comment]
すみません。
こちらがサーバーとクライアントのクラッシュリポートになります。

[crash-2023-01-22_18.47.54-client.txt](https://github.com/Geforce132/SecurityCraft/files/10474127/crash-2023-01-22_18.47.54-client.txt)
[crash-2023-01-22_19.04.46-server.txt](https://github.com/Geforce132/SecurityCraft/files/10474128/crash-2023-01-22_19.04.46-server.txt)

**Comment by bl4ckscor3** [comment]
Thank you. The crash says that SecurityCraft tried to access code that it cannot actually access. The weird part about this is that we specifically modify that code to make it accessible. I am unsure what may be the cause of this, and I cannot reproduce it either. Try to see if this error still happens after removing canary, starlight, and rubidium (they make the most extensive changes). In the next version of SecurityCraft, there will be a change regarding this, but I have no idea if that will fix this issue. I'll make the change purely based on a weak suspicion.
