### ISSUE TITLE
(1.12.2) Crash On Constructing Mods When Astral Sorcery Is Installed

### ISSUE THREAD

**Issue by RConTRS** [Geforce132/SecurityCraft#392]
Although Nothing Says That In The Log But After Removing Mods One By One It Appears That The Issue Is Between SC and AS

Log : [latest.log](https://github.com/Geforce132/SecurityCraft/files/10492410/latest.log)

**Comment by bl4ckscor3** [comment]
Based on no response for a week, I am assuming that fixed it. If you are still having this issue after trying out the no mixin version, don't hesitate to comment on this issue.

**Comment by RConTRS** [comment]
it works without any problems, thanks
