### ISSUE TITLE
(1.19.3) Static security camera's glitching + UI issue

### ISSUE THREAD

**Issue by LameProgrammer** [Geforce132/SecurityCraft#393]
I just updated to the latest version of Minecraft, Forge and SecurityCraft and all my existing static camera's are glitching out. 
It looks as if the camera wants to keep on rotating but it's stuck. This only happens with static camera's, rotating ones are fine. 
I tried re-enabling the static mode but it happens again each time I toggle the button between rotating yes/no.

**Additional UI issue:**
On items with a keypad such as a password-protected chest, the UI of the actual keypad is bugged out.
The options in the very lower left and right corners show "â..." instead of the right chatacter it should have.

**Comment by bl4ckscor3** [comment]
The camera issue is fixed for the next version, the other one will be looked into. In the future, please do not post multiple bugs into one issue for better trackability.

**Comment by bl4ckscor3** [comment]
38589fea3f312eacbdfa0697234fdee728dfea64 For the check password screen text fix.
