### ISSUE TITLE
[1.18.2] [FORGE] Random Crash related to Security Camera

### ISSUE THREAD

**Issue by Camawama** [Geforce132/SecurityCraft#394]
I am working on an update for my modpack (CamaCraft). I added your mod and things seem to work find for the most part except for the fact that I am getting a random crash. I can't seem to replicate the crash as it is random.

SC Version:
![image](https://user-images.githubusercontent.com/43620900/219294984-514a7a87-ec14-4a7f-8dbb-7f48cd6d34d7.png)
Forge Version: 
![image](https://user-images.githubusercontent.com/43620900/219295029-f7d03a1f-4903-40ab-9491-79816381a1ad.png)

Crash Report: 
[crash-2023-02-16_01.16.19-client.txt](https://github.com/Geforce132/SecurityCraft/files/10753160/crash-2023-02-16_01.16.19-client.txt)
Logs: 
[latest.log](https://github.com/Geforce132/SecurityCraft/files/10753164/latest.log)

**Comment by bl4ckscor3** [comment]
Sorry, this is out of our control. The mod tries to access code that is not accessible by default. We fix that by telling Forge to make that code accessible for us (see [here](https://github.com/Geforce132/SecurityCraft/blob/1.19.3/src/main/resources/META-INF/accesstransformer.cfg#L32) for this specific case). That's all we can do. I don't know if other mods can somehow influence how accessible that code is made, so it may be a mod conflict in which case the other mod should be more lenient with their access transformer regarding this method.

**Comment by Camawama** [comment]
How can I troubleshoot this issue without meticulously removing every mod from the pack one by one? It looks like it has something to do with Multiplayer and I know the one mod which heavily modifies multiplayer, so I removed the Multiplayer server pause but still had the same issue.

**Comment by bl4ckscor3** [comment]
Do a binary search. Remove half the mods, see if the issue happens. If it doesn't, swap halves. If it does, remove another half. And so on.

**Comment by Camawama** [comment]
It's a lot more work than simple binary swaps. I have over 200 mods in my pack which have all different dependencies. It would take days for me to do that since I also work a full-time job.
