### ISSUE TITLE
[BUG] Fall Damage Canceling with Camera Monitor

### ISSUE THREAD

**Issue by Camawama** [Geforce132/SecurityCraft#395]
If you fall out of the sky while looking through a camera, you don't take fall damage.

**Comment by bl4ckscor3** [comment]
Please be more descriptive when reporting bugs and include the Minecraft version, the SecurityCraft version, and any other mods and their versions that you may be using.

**Comment by bl4ckscor3** [comment]
I have test this in v1.9.5 on every Minecraft version we support, and took fall damage every time.
