### ISSUE TITLE
Retinal Scanner Player Face Flickers

### ISSUE THREAD

**Issue by GitCat3** [Geforce132/SecurityCraft#398]
I am having an issue with the 1.19.2 version of this mod where the retinal scanner's player face that shows up is flickering constantly. Is this a bug or an issue on my end? Thanks!

video of the bug: [video](https://streamable.com/svlz5z)

**Comment by bl4ckscor3** [comment]
We no longer support 1.19.2, and this issue seems to no longer happen versions of the mod in 1.19.3.
