### ISSUE TITLE
Keypads not showing up

### ISSUE THREAD

**Issue by Blitzixt** [Geforce132/SecurityCraft#402]
I've recently installed the 1.9.5 version for 1.19.3, but for some reason, the pop-up for the keypad doesn't work
![image](https://user-images.githubusercontent.com/127593319/224476433-f8b3e93f-89a3-4e36-b49d-dd1c58b4a2c9.png)
The block used is the Keypad Door, but it applies to every other block.

**Comment by bl4ckscor3** [comment]
Duplicate of #397
