### ISSUE TITLE
Suggestion: Badges

### ISSUE THREAD

**Issue by bauerbach** [Geforce132/SecurityCraft#403]
I have a cool idea for the mod: badges and badge readers.

These would work like keycards, except that you would be able to have a badge tied to a username and badge reader IDs.

For more info on what I am suggesting exactly, see: https://en.wikipedia.org/wiki/Access_badge.

**Comment by bl4ckscor3** [comment]
Isn't this pretty much exactly like the current keycard system? Badge reader IDs are equivalent to keycard reader signatures. Keycards are tied to a single signature of a keycard reader owned by a specific player, just like badges are tied to badge reader IDs. The only difference I can see is that the keycards are not tied to the player the keycard is for, but to the owner of the reader that the keycard can open. This distinction shouldn't matter much however, as in both cases the keycard/badge can be lost and used by the wrong hands.

**Comment by bl4ckscor3** [comment]
After internal discussion we have come to the conclusion that the keycard system offers the same overall functionality as what you are suggesting. As such, this will not be worked on.
