### ISSUE TITLE
if u place alarm in 1.16.5 the server goes down

### ISSUE THREAD

**Issue by Catspin** [Geforce132/SecurityCraft#407]

**Comment by RedstoneDubstep** [comment]
Can you please provide a crash report or a relevant log of when the crash happens? Also, what version of SecurityCraft are you using?

**Comment by bl4ckscor3** [comment]
While this was an easy problem to reproduce, please always under any circumstances when reporting crashes include the Minecraft version, the mod version, and any logs (latest.log, debug.log, and most importantly the crash report as well). This helps mod authors to diagnose issues more quickly.

**Comment by Catspin** [comment]
the logs! https://mclo.gs/HcbOk7I

**Comment by bl4ckscor3** [comment]
Thank you, but I already fixed it. A new version will be released shortly!
