### ISSUE TITLE
Trying to view camera disconnects all players except host on Essential 

### ISSUE THREAD

**Issue by KEEGUNATOR2** [Geforce132/SecurityCraft#408]
Hello,
I am using the Essential mod to play multiplayer with the boys without having to pay for a server. When I try and view a security camera, there is a major lag spike and all players except me get disconnected, which seems to be because I am the one hosting the server. 

Game version: 1.16.5
Forge version: 36.32.9
Securitycraft version: 1.9.5

Mods list: (Everybody connected to the server has only these mods.) 
Securitycraft (obviously)
Create
Mr Crayfish Furniture Mod 
Mr Crayfish Gun Mod
Essential 
Flywheel (Library for the Create mod)
Just Enough Items 
Obfuscate (Library for Mr Crayfish mods)
Optifine
XL Food Mod 

All other mods and other features of security craft seem to be working normally except the cameras. 
Let me know if you need other information and I'll try my best to get it.

**Comment by bl4ckscor3** [comment]
Please try out v1.9.6 of the mod, where we fixed an issue that sounds like it could be the one you are experiencing.

**Comment by KEEGUNATOR2** [comment]
Fixed
