### ISSUE TITLE
[1.12.2] Entities disappear after dismounting the camera monitor

### ISSUE THREAD

**Issue by SmirkishBoi** [Geforce132/SecurityCraft#410]
Hello, whenever I spawn an npc by using the npc wand which is from a mod called Custom Npcs created by someone, and when I add a camera in front of it and then I connect the camera by using its monitor, when I use the camera monitor and then I dismount it, the npc suddenly disappears for no reason, and when I use the camera monitor once again, the npc sometimes appears, I have tried deleting all of my mods and use only custom npc and security craft, but yet, the bug still refuses to go away.

here's a video which is showing the bug: https://drive.google.com/file/d/1kBxRtRDWchky5HtkKoNesOJO-rXSjQTg/view?usp=sharing

**Comment by bl4ckscor3** [comment]
Which Minecraft version and which SecurityCraft version are you using?
