### ISSUE TITLE
Cant install any mods from the curseforge website to curse forge

### ISSUE THREAD

**Issue by benjiiman** [Geforce132/SecurityCraft#411]
im not sure if this is an issue with the modpack or if its my software but every time i try to download this modpack it says java runtime is out of date
![image](https://user-images.githubusercontent.com/84321360/229162264-e6aadbe9-dfa0-4e94-b19f-08b3a1b1c17c.png)

**Comment by bl4ckscor3** [comment]
This is not a bug pertaining to SecurityCraft, please ask in the CurseForge discord for help with installing modpacks. The modpack you are showing doesn't even have SecurityCraft.

**Comment by benjiiman** [comment]
im aware, i was showing the error message that was at the bottom?


Sent from my Galaxy Tab A (2016)-------- Original message --------From: bl4ckscor3 ***@***.***> Date: 3/31/2023  10:27 AM  (GMT-06:00) To: Geforce132/SecurityCraft ***@***.***> Cc: Colormitz3 ***@***.***>, Author ***@***.***> Subject: Re: [Geforce132/SecurityCraft] Cant install any mods from the
  curseforge website to curse forge (Issue #411) 

This is not a bug pertaining to SecurityCraft, please ask in the CurseForge discord for help with installing modpacks. The modpack you are showing doesn't even have SecurityCraft.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Geforce132/SecurityCraft/issues/411#issuecomment-1492129262",
"url": "https://github.com/Geforce132/SecurityCraft/issues/411#issuecomment-1492129262",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bl4ckscor3** [comment]
If you are aware of that, then you shouldn't have come to this issue tracker in the first place. It is for the mod SecurityCraft and nothing else. There won't be support for issues that do not affect us for obvious reasons.
