### ISSUE TITLE
Player disappears when using the camera monitor

### ISSUE THREAD

**Issue by SmirkishBoi** [Geforce132/SecurityCraft#413]
hello so yesterday, I found another bug on [1.12.2] SecurityCraft v1.9.6],  when the player who has joined my server uses the camera monitor to use the security cameras, he then disappears for no reasons, which idk why

**Comment by bl4ckscor3** [comment]
When reporting bugs, please always include the Minecraft version and the mod version (in this case SecurityCraft's) you are using. This helps figure out when an issue may have been introduced, or if a fix is already available.

**Comment by SmirkishBoi** [comment]
just edited the post

**Comment by bl4ckscor3** [comment]
Closing as fixed and duplicate of #410.

**Comment by SmirkishBoi** [comment]
here https://drive.google.com/file/d/1PmLxfJA5KxWUZoVVn0JauZhJFJpDy5TJ/view?usp=sharing

**Comment by bl4ckscor3** [comment]
That just lookes like general poor performance.
