### ISSUE TITLE
Added Nothing

### ISSUE THREAD

**Issue by PurpleKit9012** [Geforce132/SecurityCraft#414]
When im in it added NOTHING

**Comment by bl4ckscor3** [comment]
I don't have a magic crystal ball with which I can see what what you did, what doesn't work, and what the issue may be. The information you have given us cannot be more vague. You must be more descriptive when reporting issues.
I am assuming that you tried to install SecurityCraft, but don't see any content of the mod when you join a world. Please make sure that you properly installed the mod. You need to use Minecraft Forge, Fabric won't work. If you have difficulties installing mods, please take a look at [this recent tutorial](https://www.youtube.com/watch?v=FGj0VgYwqzs) on how to install mods.
