### ISSUE TITLE
Sentry disguise module don't working (1.16.5)

### ISSUE THREAD

**Issue by vinhor** [Geforce132/SecurityCraft#416]
When I use disguise module on sentry, after few minutes it will look like normal.

**Comment by bl4ckscor3** [comment]
Can you please elaborate on which block you have added to the disguise module, and when the disguise disappears? Do you stay next to the sentry, do you go away? If the latter, how far are you going away, does the sentry get unloaded? If you come back, is the disguise still there or is it immediately gone?

**Comment by vinhor** [comment]
I added to the disguise module one modded item and grass block, I go away, on every sentry it disapperar at different time. Sometimes disguise module there is, sometimes not. I have this mod on server, and it doesn't show to another player, but it does to me. On some sentrys it never disappears.

**Comment by bl4ckscor3** [comment]
Which SecurityCraft version are you using?

**Comment by vinhor** [comment]
1.9.6.1.

**Comment by bl4ckscor3** [comment]
Hmm, I can't seem to reproduce this. On a server, no matter how far I go away, if I relog, add the module with a second player while far away/offline, I can always see the disguise of the sentry. Do you have any other mods installed, and if so which? There *may* be a conflict here.

**Comment by vinhor** [comment]
Alex's mobs, Architectury, Awesome dungeon, Awesome dungeon nether edition, YUNG's Better Dungeons, Better end forge, Oh The Biomes You'll Go, Caelus, Carry on, Citadel, Cloth config, Curios, Cyclic, Easier Sleeping (server only), Everlasting Skins (server only), Goblin traders, Gravestone, Ice and fire, Just Enough Items, Library Ferret, Luggage, Macaw's furniture, Origins forge, Serene Seasons, Spartan Weaponry, Spartan Weaponry: Ice and fire, Upgraded core, Upgraded netherite spartan weaponry, Upgaded Netherite Ultimerite, Upgraded netherite, Void totem, Waystones, World Edit (server only), Xaero's minimap and worldmap (both client only)

**Comment by bl4ckscor3** [comment]
What was the cause? We would like to fix it if possible.
