### ISSUE TITLE
Server crash due to security craft

### ISSUE THREAD

**Issue by vinhor** [Geforce132/SecurityCraft#417]
[crash-2023-04-17_15.25.03-server.txt](https://github.com/Geforce132/SecurityCraft/files/11252777/crash-2023-04-17_15.25.03-server.txt)

**Comment by bl4ckscor3** [comment]
Sadly this gives nothing to go on. Everything the log says is that the server hung up for 60 seconds without doing anything, and was thus shut down. What did you do before that happened?

**Comment by vinhor** [comment]
Sorry, I sent bad crash report. It crash always when one specific player connect to the server.
[crash-2023-04-17_15.24.03-server.txt](https://github.com/Geforce132/SecurityCraft/files/11261449/crash-2023-04-17_15.24.03-server.txt)

**Comment by bl4ckscor3** [comment]
Thank you, we'll get this fixed for the next update.
