### ISSUE TITLE
Bug, impossible to disable the destruction of the blocks of the explosion of the mines on a server

### ISSUE THREAD

**Issue by Matheobrn** [Geforce132/SecurityCraft#419]
![Capture d’écran 2023-04-22 234218](https://user-images.githubusercontent.com/131559312/233808226-70e461ac-bb4c-4cb1-8211-2892b131ceed.png)

even after disable, the mines still destroy the blocks

**Comment by bl4ckscor3** [comment]
I cannot reproduce this. I tested it on Minecraft 1.16.5, 1.18.2, 1.19.3, and 1.19.4 with SecurityCraft v1.9.6.2. Tested with a stone mine and a mine. Every time the config option was set to false, and mines did not break blocks when they exploded as expected.
Which Minecraft version and which SecurityCraft version are you using? Did you edit the config file while the server was offline? Which mine are you using that still destroys blocks for you?

**Comment by Matheobrn** [comment]
I use minecraft 1.16.5 but security craft version 1.9.6.1 . I have edit the files during the serveur on line and i restart 2 times the server. All mines destruct blockl

**Comment by bl4ckscor3** [comment]
Try editing the config while the server is offline.

**Comment by Matheobrn** [comment]
I try to stop the server, put true start the server, restop and put false , restart, and nothing changes

**Comment by bl4ckscor3** [comment]
Weird. I'm sorry, I don't know what might be causing this.

**Comment by Matheobrn** [comment]
Okey thanks
