### ISSUE TITLE
using the camera would cause the player to disappear and the plane to change its position

### ISSUE THREAD

**Issue by SmirkishBoi** [Geforce132/SecurityCraft#421]
hello, I have just found a new bug on the 1.12.2 version of the security craft mod version 1.12.2_SecurityCraft_v1.9.6-GitHub-413 and the bug is that when I use the security cameras to check on a plane and myself, the plane had suddenly changed its position and my player have just disappeared AGAIN! is there a way to fix this issue please?
thanks
![2023-05-12_17 25 17](https://github.com/Geforce132/SecurityCraft/assets/129232831/1d408ca6-cd3a-4ba4-b0ff-15ed249895a8)

**Comment by bl4ckscor3** [comment]
When reporting bugs, please always include the Minecraft version and the version of the mod that you are reporting to.

**Comment by bl4ckscor3** [comment]
You have now edited in the Minecraft version - but you failed to mention the SecurityCraft version as I asked you to do.

**Comment by SmirkishBoi** [comment]
there I have just mentioned the security craft mod version that I'm using

**Comment by SmirkishBoi** [comment]
now how can I fix this bug?

**Comment by bl4ckscor3** [comment]
What mod is the plane from?

**Comment by SmirkishBoi** [comment]
Immersive+Vehicles-1.12.2-22.8.0

**Comment by SmirkishBoi** [comment]
idk if it's from the mod or from the security craft mod itself

**Comment by SmirkishBoi** [comment]
hello?

**Comment by bl4ckscor3** [comment]
We're not your 24/7 support and we can't look into your issues the immediate instant you report them to us. We are humans with lives that take priority over the hobby of us that is modding Minecraft. Be patient. You are getting this mod for free after all, act like it.

**Comment by SmirkishBoi** [comment]
oh sorry if I have bothered you

**Comment by bl4ckscor3** [comment]
Please try it again with the newly released v1.9.7.

**Comment by bl4ckscor3** [comment]
Hello. We just released v1.9.10.1 which fixes a different camera bug. Can you please see if this bug still happens to you if you use v1.9.10.1?
