### ISSUE TITLE
1.12.2 Mod Question

### ISSUE THREAD

**Issue by gameplayoffert** [Geforce132/SecurityCraft#423]
Hi, currently this is not an issue with the security craft mod but i have a question ? I saw the last version of security craft in 1.12.2 and it has been made in march 2023 so i have a question ? Which version of the "MCP" are you using ? Is it a "FG3" version like the 2859 ? or is it a "FG2" version like the 2846 ? I just wanted to know because for me every version after the migration to "FG3" is not working.

**Comment by bl4ckscor3** [comment]
Hi 👋 We use this issue tracker for bug reports and suggestions for SecurityCraft, not questions about the mod, its development, or mod development in general. You can see which Forge and ForgeGradle version we are using in the mod's build.gradle file. For a working mod using FG3, check out [ICBM-Classic](https://github.com/BuiltBrokenModding/ICBM-Classic).
