### ISSUE TITLE
Please make the maximum keycard number for Keycard readers customizable (or at least double it).

### ISSUE THREAD

**Issue by bauerbach** [Geforce132/SecurityCraft#424]
I have a big server I am making and there will be both "apartments" and "hotel rooms" using the keycard system. However, I am wondering how quickly I would hit the limit (currently it's 32768), and I don't really see a technical reason for the limit at all. Can you please make it so we can set a maximum in the config file (e.g. somewhere between 32768 and 99999) or increase it to 65336?

**Comment by bl4ckscor3** [comment]
The limit was chosen because it is 2^15 (maximum value for the short type in Java), and we didn't think anyone would ever have the need for more than thirty-two thousand keycard setups. But we can easily increase the limit to 99999.
