### ISSUE TITLE
How do I block an item?

### ISSUE THREAD

**Issue by polarbeen** [Geforce132/SecurityCraft#425]
Hi, I have a minecraft server and I would like to block the Code Breaker because some people are stealing to people that doesn't connects to the server. 

Thank you.

**Comment by Big-Guns** [comment]
You can disable it in the server configuration file
either:
Disable allowCodebreakerItem (old versions only)
Or:
Set codebreaker_chance to 0.0 (does not function, still damages durability) or set to -1.0 to effectively make it do nothing.

You can also disable the recipe with a mod like https://kubejs.com/

**Comment by polarbeen** [comment]
ok, thank you so much for the information.
