### ISSUE TITLE
1.18.2 - Disguise Module Bug with Inventory Scanner

### ISSUE THREAD

**Issue by NEONBLUETROOPER** [Geforce132/SecurityCraft#426]
When I was working with my creations on a Minecraft world, experimenting with the disguise module with the inventory scanner, I got kicked out of Minecraft.
When I tried to re-join the Minecraft world where the incident happened, I got kicked out again likely because of the bug.

During my experimenting, the two scanners are facing each other in an online state.

I am not sure if it was conflict with 1 of the 8 other mods that I installed such as Create, Re-chiselled, etc but I didn't bother to confirm that.

**Comment by bl4ckscor3** [comment]
Do you have any logs from when the issue happened and that you can post, please? latest.log and debug.log for instance.

**Comment by NEONBLUETROOPER** [comment]
Sorry for the late reply, this may have been the first time that I am reporting an issue with a mod.
I am not sure how I can get access to that information since I am still new to having mods however, if you speaking on what pops up after Minecraft crashes in the launcher, I can send you that.

If that's not what you are after then I need some guidance on how to get access to that information so I can forward it for you or/and your team.

**Comment by bl4ckscor3** [comment]
There should be a "View crash report" button in the launcher after the crash. Click it, and send the file it opens here.

**Comment by NEONBLUETROOPER** [comment]
[crash-2023-06-03_22.06.42-client.txt](https://github.com/Geforce132/SecurityCraft/files/11646613/crash-2023-06-03_22.06.42-client.txt)

I suppose it is something like this I assume. I like how the disguise module works, without the crashing lol.

**Comment by bl4ckscor3** [comment]
Thank you! That immediately shows me where the issue is. I'll make sure it's fixed for our next release. I'm afraid that apart from using 3rd party programs to edit the inventory scanner to remove the disguise module, or outright remove the whole block, there's not much you can do to fix the issue yourself.

**Comment by NEONBLUETROOPER** [comment]
That's understandable, thank you for paying attention.
