### ISSUE TITLE
Crash to place a blocks

### ISSUE THREAD

**Issue by HittDust** [Geforce132/SecurityCraft#433]
I'm trying to create a server using the mod for version 1.16.5, when trying to place a block the game crashes and closes

**Comment by bl4ckscor3** [comment]
Please always post the crash report when reporting crashes. Without it, we can't do anything.

**Comment by bl4ckscor3** [comment]
Closing due to lack of a crash report and being unable to reproduce the issue as it was reported. If you still want to provide the crash report, feel free to post it here.
