### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Gamer101233** [Geforce132/SecurityCraft#434]
Every time i go to use the security doors or other stuff in the mod i get a game crash with the error

The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events

Im currently on 1.12.2 and the mod version is 1.9.6
some other things work
i tried using the keypad door and it caused the crash and other things i wanted to use caused the crash 
im not sure whats going on i just wanted to use this mod i think its cool but, i cant use anything rlly due to this issue.

<details>
<summary>Crash report</summary>

Time: 6/13/23 8:06 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.github.ipixeli.gender.client.ClientEvents.onEvent(ClientEvents.java:85)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_ClientEvents_onEvent_PlaySoundAtEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onPlaySoundAtEntity(ForgeEventFactory.java:498)
	at net.minecraft.client.entity.EntityPlayerSP.func_184185_a(EntityPlayerSP.java:581)
	at net.geforcemods.securitycraft.screen.CheckPasswordScreen.func_73869_a(CheckPasswordScreen.java:149)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.ipixeli.gender.client.ClientEvents.onEvent(ClientEvents.java:85)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_ClientEvents_onEvent_PlaySoundAtEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onPlaySoundAtEntity(ForgeEventFactory.java:498)
	at net.minecraft.client.entity.EntityPlayerSP.func_184185_a(EntityPlayerSP.java:581)
	at net.geforcemods.securitycraft.screen.CheckPasswordScreen.func_73869_a(CheckPasswordScreen.java:149)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: net.geforcemods.securitycraft.screen.CheckPasswordScreen

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['promaster4'/84, l='MpServer', x=287.51, y=64.00, z=-2961.94], EntityOtherPlayerMP['Elite3'/858, l='MpServer', x=296.02, y=64.00, z=-2972.52]]
	Chunk stats: MultiplayerChunkCache: 961, 961
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-120,64,68), Chunk: (at 8,4,4 in -8,4; contains blocks -128,0,64 to -113,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 247777 game time, 21751 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntityItem['item.item.egg'/5892, l='MpServer', x=270.35, y=70.00, z=-2927.66], EntityItem['item.item.egg'/5898, l='MpServer', x=247.07, y=69.00, z=-2981.19], EntityBat['Bat'/5903, l='MpServer', x=249.84, y=34.26, z=-3033.13], EntityMirror['entity.Mirror.name'/537, l='MpServer', x=291.93, y=65.50, z=-2959.50], EntityChicken['Chicken'/287, l='MpServer', x=355.18, y=66.00, z=-2906.53], EntityChicken['Chicken'/288, l='MpServer', x=362.20, y=68.00, z=-2909.43], EntityChicken['Chicken'/289, l='MpServer', x=353.50, y=65.00, z=-2905.50], EntityMinecartChest['Minecart with Chest'/305, l='MpServer', x=262.50, y=25.06, z=-3040.50], EntityBat['Bat'/5943, l='MpServer', x=220.30, y=27.10, z=-2965.25], EntitySheep['Sheep'/317, l='MpServer', x=283.45, y=71.00, z=-3016.20], EntityItem['item.item.egg'/5443, l='MpServer', x=274.24, y=71.00, z=-3016.38], EntitySheep['Sheep'/324, l='MpServer', x=289.42, y=72.00, z=-3039.25], EntityCow['Cow'/325, l='MpServer', x=264.57, y=70.00, z=-3035.19], EntitySheep['Sheep'/326, l='MpServer', x=258.61, y=68.00, z=-3042.73], EntityItem['item.item.egg'/5959, l='MpServer', x=275.25, y=70.00, z=-2926.88], EntityChicken['Chicken'/330, l='MpServer', x=287.52, y=72.00, z=-3036.12], EntityItem['item.item.egg'/5450, l='MpServer', x=303.02, y=66.00, z=-2908.28], EntityChicken['Chicken'/340, l='MpServer', x=273.81, y=71.00, z=-3015.57], EntityBat['Bat'/5974, l='MpServer', x=215.25, y=28.06, z=-2996.39], EntityMirror['entity.Mirror.name'/599, l='MpServer', x=279.07, y=72.50, z=-2945.50], EntityOtherPlayerMP['Elite3'/858, l='MpServer', x=296.02, y=64.00, z=-2972.52], EntityOtherPlayerMP['Elite3'/858, l='MpServer', x=296.02, y=64.00, z=-2972.52], EntityLatchedRenderer['unknown'/860, l='MpServer', x=296.02, y=64.00, z=-2972.52], EntityItem['item.item.egg'/5470, l='MpServer', x=300.41, y=73.00, z=-2985.36], EntityChicken['Chicken'/99, l='MpServer', x=207.13, y=82.00, z=-2903.45], EntityChicken['Chicken'/107, l='MpServer', x=214.50, y=76.00, z=-2884.59], EntityPlayerSP['Promaster4'/84, l='MpServer', x=287.51, y=64.00, z=-2961.94], EntityChicken['Chicken'/108, l='MpServer', x=214.50, y=76.00, z=-2884.18], EntityLatchedRenderer['unknown'/365, l='MpServer', x=8.50, y=65.00, z=8.50], EntityChicken['Chicken'/110, l='MpServer', x=209.53, y=82.00, z=-2894.19], EntityChicken['Chicken'/111, l='MpServer', x=216.45, y=80.00, z=-2892.21], EntityBat['Bat'/6008, l='MpServer', x=214.70, y=26.75, z=-2998.22], EntityMinecartChest['Minecart with Chest'/126, l='MpServer', x=223.50, y=24.06, z=-3019.50], EntityMinecartChest['Minecart with Chest'/127, l='MpServer', x=238.50, y=26.06, z=-3026.50], EntityBat['Bat'/6024, l='MpServer', x=219.75, y=29.10, z=-3015.49], EntityMinecartChest['Minecart with Chest'/137, l='MpServer', x=232.50, y=27.06, z=-3010.50], EntitySheep['Sheep'/139, l='MpServer', x=242.50, y=70.00, z=-3039.19], EntitySheep['Sheep'/140, l='MpServer', x=241.55, y=68.00, z=-3034.61], EntityChicken['Chicken'/141, l='MpServer', x=310.58, y=72.00, z=-2982.11], EntityChicken['Chicken'/142, l='MpServer', x=246.49, y=69.00, z=-2981.21], EntityMinecartChest['Minecart with Chest'/144, l='MpServer', x=216.50, y=28.06, z=-2970.50], EntityMinecartChest['Minecart with Chest'/145, l='MpServer', x=228.50, y=25.06, z=-2987.50], EntityChicken['Chicken'/146, l='MpServer', x=209.88, y=82.00, z=-2896.50], EntityVillager['Villager'/148, l='MpServer', x=225.95, y=66.00, z=-2911.45], EntityVillager['Villager'/149, l='MpServer', x=234.44, y=69.00, z=-2912.98], EntityVillager['Villager'/150, l='MpServer', x=226.70, y=66.00, z=-2912.95], EntityVillager['Villager'/151, l='MpServer', x=234.68, y=69.00, z=-2912.01], EntityVillager['Villager'/152, l='MpServer', x=226.67, y=66.00, z=-2912.12], EntityVillager['Villager'/153, l='MpServer', x=237.50, y=71.00, z=-2912.07], EntityVillager['Villager'/154, l='MpServer', x=232.50, y=64.50, z=-2934.08], EntityVillager['Villager'/155, l='MpServer', x=232.90, y=64.00, z=-2935.08], EntityVillager['Villager'/156, l='MpServer', x=234.69, y=64.00, z=-2944.41], EntityVillager['Villager'/157, l='MpServer', x=231.93, y=64.00, z=-2936.21], EntityVillager['Villager'/158, l='MpServer', x=231.30, y=64.00, z=-2936.70], EntityVillager['Villager'/159, l='MpServer', x=236.41, y=64.00, z=-2934.19], EntityVillager['Villager'/160, l='MpServer', x=234.37, y=64.00, z=-2943.49], EntityVillager['Villager'/161, l='MpServer', x=237.70, y=64.00, z=-2934.94], EntityVillager['Villager'/162, l='MpServer', x=237.07, y=64.00, z=-2934.65], EntityVillager['Villager'/163, l='MpServer', x=235.70, y=64.00, z=-2934.73], EntityMinecartChest['Minecart with Chest'/164, l='MpServer', x=263.50, y=35.06, z=-2977.50], EntityMirror['entity.Mirror.name'/676, l='MpServer', x=251.93, y=71.50, z=-2910.50], EntityBat['Bat'/5798, l='MpServer', x=336.23, y=44.92, z=-3034.45], EntitySquid['Squid'/6061, l='MpServer', x=229.44, y=61.63, z=-3018.39], EntitySquid['Squid'/6062, l='MpServer', x=228.46, y=59.39, z=-3011.79], EntitySquid['Squid'/6063, l='MpServer', x=223.65, y=59.09, z=-3016.22], EntitySquid['Squid'/6064, l='MpServer', x=232.62, y=61.36, z=-3012.20], EntitySquid['Squid'/6069, l='MpServer', x=240.55, y=60.26, z=-3015.82], EntityVillager['Villager'/182, l='MpServer', x=264.44, y=66.00, z=-2923.22], EntitySquid['Squid'/6070, l='MpServer', x=241.61, y=60.25, z=-3016.27], EntityVillager['Villager'/183, l='MpServer', x=264.50, y=66.00, z=-2924.57], EntitySquid['Squid'/6071, l='MpServer', x=237.77, y=57.91, z=-3006.85], EntityChicken['Chicken'/184, l='MpServer', x=274.80, y=70.00, z=-2926.50], EntitySquid['Squid'/6072, l='MpServer', x=243.93, y=58.10, z=-3008.02], EntitySheep['Sheep'/186, l='MpServer', x=322.19, y=72.00, z=-2994.50], EntityVillager['Villager'/189, l='MpServer', x=261.51, y=67.80, z=-2938.52], EntitySheep['Sheep'/190, l='MpServer', x=323.44, y=71.00, z=-3000.25], EntityVillager['Villager'/191, l='MpServer', x=247.26, y=72.00, z=-2921.86], EntityVillager['Villager'/192, l='MpServer', x=247.29, y=71.00, z=-2905.96], EntityVillager['Villager'/193, l='MpServer', x=247.70, y=71.00, z=-2907.70], EntityVillager['Villager'/194, l='MpServer', x=246.52, y=71.00, z=-2906.86], EntityVillager['Villager'/195, l='MpServer', x=247.70, y=71.00, z=-2906.80], EntityVillager['Villager'/196, l='MpServer', x=247.70, y=71.00, z=-2905.09], EntityChicken['Chicken'/204, l='MpServer', x=291.77, y=72.00, z=-2915.50], EntityChicken['Chicken'/210, l='MpServer', x=270.49, y=70.00, z=-2927.80], EntityItem['item.item.egg'/6098, l='MpServer', x=349.50, y=65.00, z=-2939.77], EntityChicken['Chicken'/212, l='MpServer', x=351.50, y=63.00, z=-2933.50], EntityItem['item.item.egg'/5844, l='MpServer', x=293.34, y=71.00, z=-2912.54], EntityChicken['Chicken'/213, l='MpServer', x=348.11, y=63.00, z=-2934.20], EntityChicken['Chicken'/214, l='MpServer', x=346.88, y=63.00, z=-2934.58], EntityBat['Bat'/6103, l='MpServer', x=233.66, y=41.38, z=-2961.32], EntityChicken['Chicken'/217, l='MpServer', x=350.13, y=66.00, z=-2939.51], EntityChicken['Chicken'/219, l='MpServer', x=354.47, y=73.00, z=-2958.02], EntityChicken['Chicken'/224, l='MpServer', x=357.78, y=74.00, z=-2962.50], EntityChicken['Chicken'/225, l='MpServer', x=358.87, y=73.00, z=-2960.91], EntityBat['Bat'/6113, l='MpServer', x=237.49, y=16.03, z=-2906.30], EntityItem['item.item.egg'/4834, l='MpServer', x=347.70, y=63.00, z=-2934.13], EntityBat['Bat'/6116, l='MpServer', x=219.75, y=32.00, z=-2971.42], EntityItem['item.item.egg'/5609, l='MpServer', x=316.49, y=63.00, z=-2926.17], EntityChicken['Chicken'/234, l='MpServer', x=302.51, y=66.00, z=-2908.13], EntityChicken['Chicken'/235, l='MpServer', x=293.18, y=71.00, z=-2911.59], EntityChicken['Chicken'/238, l='MpServer', x=316.88, y=63.00, z=-2925.51], EntityChicken['Chicken'/240, l='MpServer', x=308.87, y=65.00, z=-2918.45], EntityChicken['Chicken'/249, l='MpServer', x=350.55, y=64.00, z=-2905.78]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/365, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 313950032 bytes (299 MB) / 2251816960 bytes (2147 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version        | Source                                          | Signature                                |
	|:------ |:--------------------------- |:-------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2         | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                         | 9.42           | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                         | 8.0.99.99      | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2859   | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core           | 1.12.2-1.0     | minecraft.jar                                   | None                                     |
	| LCHIJA | obfuscate                   | 0.4.2          | minecraft.jar                                   | None                                     |
	| LCHIJA | securitycraft               | v1.9.6         | [1.12.2] SecurityCraft v1.9.6.jar               | None                                     |
	| LCHIJA | gender                      | 1.7.0          | [1.12.2]Gender-1.7.0.jar                        | None                                     |
	| LCHIJA | betterbuilderswands         | 0.11.1         | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCHIJA | bibliocraft                 | 2.4.6          | BiblioCraft[v2.4.6][MC1.12.2].jar               | None                                     |
	| LCHIJA | biomesoplenty               | 7.0.1.2445     | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None                                     |
	| LCHIJA | extendedrenderer            | v1.0           | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | coroutil                    | 1.12.1-1.2.37  | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | configmod                   | v1.0           | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | df-roads                    | 1.5.2-mc1.12.2 | df-roads-1.5.2-mc1.12.2.jar                     | None                                     |
	| LCHIJA | dynamiclights               | 1.4.9          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_onfire        | 1.0.7          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_creepers      | 1.0.6          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_dropitems     | 1.1.0          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_entityclasses | 1.0.1          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_mobequipment  | 1.1.0          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_flamearrows   | 1.0.1          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_floodlights   | 1.0.3          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_otherplayers  | 1.0.9          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | dynamiclights_theplayer     | 1.1.3          | DynamicLights-1.12.2.jar                        | None                                     |
	| LCHIJA | fastleafdecay               | v14            | FastLeafDecay-v14.jar                           | None                                     |
	| LCHIJA | cfm                         | 6.3.0          | furniture-6.3.2-1.12.2.jar                      | None                                     |
	| LCHIJA | cgm                         | 0.15.3         | guns-0.15.3-1.12.2.jar                          | None                                     |
	| LCHIJA | ichunutil                   | 7.2.2          | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mcwbridges                  | 1.0.6          | mcw-bridges-1.0.6b-mc1.12.2.jar                 | None                                     |
	| LCHIJA | harvestcraft                | 1.12.2zb       | Pam's HarvestCraft 1.12.2zg.jar                 | None                                     |
	| LCHIJA | portalgun                   | 7.1.0          | PortalGun-1.12.2-7.1.0.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | vehicle                     | 0.44.1         | vehicle-mod-0.44.1-1.12.2.jar                   | None                                     |
	| LCHIJA | weather2                    | 1.12.1-2.6.12  | weather2-1.12.1-2.6.12.jar                      | None                                     |
	| LCHIJA | xaerominimap                | 23.4.4         | Xaeros_Minimap_23.4.4_Forge_1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.6.jar)
  
GenderLoadingPlugin ([1.12.2]Gender-1.7.0.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_23.4.4_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.Q1.1.230424' Renderer: 'AMD Radeon RX 5600 XT'
	Launched Version: forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.Q1.1.230424, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.</details>

**Comment by bl4ckscor3** [comment]
This was unknowingly fixed in a0005f90a6e023b3366f1afb773ba340e809670e. It'll be part of v1.9.7, to be released some time soon.
