### ISSUE TITLE
exiting cameras makes me stuck in place and I have to leave and re enter my world to get back to normal

### ISSUE THREAD

**Issue by kittykatgameree** [Geforce132/SecurityCraft#436]
Minecraft 1.12.2
SecurityCraft 1.9.7

Other mods:
HBM's nuclear tech mod extended
Jade 
Just Enough Items
Mekanism
Open Turrets

(All Latest Version)

**Comment by bl4ckscor3** [comment]
I can't reproduce this. Exiting cameras works just fine for me with the following mods;
- Jade-0.1.0.jar
- jei_1.12.2-4.16.1.1003.jar
- Mekanism-1.12.2-9.8.3.390.jar
- NTM-Extended-1.12.2-1.9.6.jar
- omlib-1.12.2-3.1.5-256.jar
- openmodularturrets-1.12.2-3.1.14-382.jar
- [1.12.2]+SecurityCraft+v1.9.7.jar

**Comment by kittykatgameree** [comment]
It happens when i look at the camera and open a silo door so maybe try that

**Comment by kittykatgameree** [comment]
yeah

**Comment by kittykatgameree** [comment]
https://github.com/Geforce132/SecurityCraft/assets/121590866/21dd73ba-7a6d-490f-89d0-396a9864a5b1

**Comment by bl4ckscor3** [comment]
Fixed in v1.9.10.1.
