### ISSUE TITLE
Crashing on startup [1.9.7]

### ISSUE THREAD

**Issue by DeanCotton** [Geforce132/SecurityCraft#440]
I have been using version 1.8.23.1 as ALL the later version crash on startup.

Here is a copy of the crash-report if it helps. 
[crash-2023-07-11_19.43.38-client.txt](https://github.com/Geforce132/SecurityCraft/files/12017704/crash-2023-07-11_19.43.38-client.txt)

The modpack I am updating is FactoriaCraft-ServerEdition.

**Comment by bl4ckscor3** [comment]
Might be a duplicate of #300. If the solution there does not work, also try installing https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility.

**Comment by Geforce132** [comment]
Try using [this alternative version](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/4605463) of SecurityCraft. If it doesn't work initially, make sure you have a mod such as MixinBootstrap, Phosphor, or another mod that loads mixins in 1.12.2. Let us know if it works or not. 🙂

**Comment by DeanCotton** [comment]
All works. Thank You
