### ISSUE TITLE
Reinforced Doors not opening correctly

### ISSUE THREAD

**Issue by GabrieleYT9768** [Geforce132/SecurityCraft#441]
I just place my reinforced doors near the keycard reader and they both open correctly.
But if I restart the server, then just the door near the keycard reader will open and the other one stays closed.

**Comment by bl4ckscor3** [comment]
When reporting bugs and crashes, please always include at the very least the Minecraft version, the Forge/Fabric version, and the mod version. This helps narrow down when an issue may have first occurred, or whether it has already been fixed.

**Comment by GabrieleYT9768** [comment]
I'm sorry, you're right.
I'm playing on 1.12.2 Forge (Latest Mod Version)

**Comment by bl4ckscor3** [comment]
Please don't say "latest version". It's ambiguous, and there is no way to know that what you believe to be the latest version is actually the latest version. Only use explicit version numbers, it makes everything so much easier.

**Comment by GabrieleYT9768** [comment]
I'm sorry. This is the filemame:
[1.12.2] SecurityCraft v1.9.7.jar

**Comment by bl4ckscor3** [comment]
No worries, thank you! I will look into this in a bit.

**Comment by bl4ckscor3** [comment]
I can reproduce this. We'll try and get the bug fixed for the next update, thank you for reporting it!

**Comment by GabrieleYT9768** [comment]
Were you able to reproduce the issue?

**Comment by bl4ckscor3** [comment]
Read my previous comment.

**Comment by GabrieleYT9768** [comment]
Oh, I'm sorry, I didn't really understand what you were saying previously.
