### ISSUE TITLE
An allow lists for pets?

### ISSUE THREAD

**Issue by DTech10** [Geforce132/SecurityCraft#447]
I dont want my pets to roasted by the Protecto so maybe add option to add pets on the allow list

**Comment by bl4ckscor3** [comment]
We'd probably just have the Protecto ignore its owner's pets by default, I think that's the better solution here.

**Comment by DTech10** [comment]
yeah dat would be better, would it also be on other harming blocks too?

**Comment by bl4ckscor3** [comment]
Not inherently, we would need to explicitly add that to all relevant blocks.
