### ISSUE TITLE
Password doors reset and without proprietaire

### ISSUE THREAD

**Issue by WolfMethod** [Geforce132/SecurityCraft#451]
### Issue description

I'm on minecraft 1.20.1 with Security Craft 1.9.7-beta1

Out of nowhere, some (only some) of my password-protected doors and trapdoors have deleted the password and removed me from my proprietaire role.

I tried using the removing tool, the modification tool, the proprietaire changing tool, etc

What should I do? 

### Minecraft version

1.20.1

### Forge version

47.1.0

### SecurityCraft version

1.9.7.1 (Latest)

**Comment by bl4ckscor3** [comment]
Do you perhaps have the log of the time you played when this happened? There may be an issue that caused the blocks to fail loading, and in that case the cause would be in the log.

**Comment by WolfMethod** [comment]
Can you tell me where I can find those logs?

**Comment by bl4ckscor3** [comment]
In the logs folder of your .minecraft or server folder. There are multiple files, you have to find the one that has logs from the time you played when the issue happened.

**Comment by WolfMethod** [comment]
I think this is the one

[2023-07-29-2.log](https://github.com/Geforce132/SecurityCraft/files/12208147/2023-07-29-2.log)

**Comment by bl4ckscor3** [comment]
Thank you! That shows exactly what the issue is. Tagging @RedstoneDubstep because he wrote this code.

**Comment by bl4ckscor3** [comment]
Actually, disregard the tag and assignation. I found the cause.

**Comment by WolfMethod** [comment]
Just a question: I'm using CurseForge to manage my mods.

How do I proceed to upload your fix?

**Comment by bl4ckscor3** [comment]
You clone the git repository locally and run `gradlew build`. Once that's done, you can find the jar file in the `build/libs` folder.

**Comment by WolfMethod** [comment]
I tried running the build.gradle file, but I got an error. Can you run it on your end and send me the .jar file ?
![Sans titre](https://github.com/Geforce132/SecurityCraft/assets/18483836/be8d4ace-9769-4691-9f62-8a650155c85c)

**Comment by bl4ckscor3** [comment]
You did not run what I  said you should run. You need Java 17 and run the *exact* command I told you above. Please note that this is not an issue tracker to help people how to make, edit, build, or use mods. There will be no further assistance here. Feel free to join our Discord server if you are still having trouble, and we'll gladly assist you there to build your own version of SecurityCraft.
