### ISSUE TITLE
Fabric!

### ISSUE THREAD

**Issue by NateT27** [Geforce132/SecurityCraft#452]
### Issue description

Please Add Fabric Compatability please!!!!!!

### Minecraft version

1.20.1

### Forge version

47.10

### SecurityCraft version

1.9.7.1 (Latest)

**Comment by NateT27** [comment]
btw not an issue just a request!

**Comment by bl4ckscor3** [comment]
This is neither a bug nor a problem with SecurityCraft. Please do not abuse this issue tracker. We will not add Fabric support for the time being.
