### ISSUE TITLE
Mixin crash with SpongeForge

### ISSUE THREAD

**Issue by Artem-VV** [Geforce132/SecurityCraft#454]
### Issue description

When adding a mod, the server fails to start with a mixin error. log attached

### Minecraft version

1.12.2

### Forge version

14.23.5.2860

### SecurityCraft version

v1.9.7

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/kmFNvLyr

**Comment by Artem-VV** [comment]
I tried both versions of the mod: with mixin and without.
The logs are for the version without the mixin

**Comment by bl4ckscor3** [comment]
Thank you for reporting! This has already been fixed for the next update of SecurityCraft: https://github.com/Geforce132/SecurityCraft/commit/e97e7a49ddc5addf576755041ba529ffbe12e949

To fix this for yourself, open the SecurityCraft jar file with WinRAR/7-Zip/etc., open `securitycraft.mixins.json` with a normal text editor, and remove **exactly this** - nothing more nothing less. `"portal.TeleporterMixin",` Note, that this will reintroduce a bug where nether portals can remove reinforced blocks when generating in another dimension.

**Comment by Artem-VV** [comment]
Thank you very much!
