### ISSUE TITLE
[suggestion] add holo into blocks

### ISSUE THREAD

**Issue by FewerElk** [Geforce132/SecurityCraft#459]
### Issue description

Is it possible to add holographic block into not full block like tracks or stairs, for example ?
When I use the projector on a track the hologram disappears.

### Steps to reproduce

Not required

### Minecraft version

1.20.1

### Forge version

NR

### SecurityCraft version

v1.9.7.1

**Comment by bl4ckscor3** [comment]
Works for me. ![](https://i.imgur.com/fnt4GTH.png)

Stairs work, too.

**Comment by FewerElk** [comment]
I don't know if I my question was well-formuled (I ´me not very good in English), but in fact I wanted to create an hidden track : a normal track go to a wall, but this wall is in fact a projection and the track go into it. But the projection is overwrites by the track, so I can't hide the way.

**Comment by bl4ckscor3** [comment]
Ah! I understand now. Sorry about the confusion. The reason projected blocks do not show up in a block space where another block is already placed can be seen in the video below. I would like a way that makes it possible to have the projection not be overwritten, but it's tricky to decide on something concise and easy to use, that also works in most commonly used situations.

https://github.com/Geforce132/SecurityCraft/assets/5149876/37248ffc-ea7b-4c6b-90ed-1f4f439ebdcc

**Comment by FewerElk** [comment]
It is possible to add this feature in 1.20 ?
It will be cool…
Thank you !

**Comment by bl4ckscor3** [comment]
You can see that I've done that by looking at the commits you see above. One of them is on the 1.20 branch, which means it was added to that.
In general, we always add a feature/fix/change to all reasonable Minecraft versions that we currently support, which are 1.20.1, 1.19.4, 1.19.3, 1.8.2, 1.16.5, 1.12.2.

**Comment by FewerElk** [comment]
It is just that I don’t see the 1.20 commit. Here a video : https://drive.google.com/file/d/10kq-3Ryi_k_I5VfmiS6-4csBNe0numDS/view?usp=drivesdk

**Comment by bl4ckscor3** [comment]
This is the 1.20 commit.  
![](https://i.imgur.com/EUh6sI1.png)
