### ISSUE TITLE
Keypad Not Craftable, only Keypanel - 1.11.2

### ISSUE THREAD

**Issue by spylor** [Geforce132/SecurityCraft#46]
Keypad is visible in item list of JEI, but no recipe is visible. The Key Panel is craftable but no idea how to use it. So this might be me, or this might be a bug.

Used version:
Minecraft 1.11.2
Forge 13_20_1_2530 both client and server side
Securitycraft 1.8.2.4

Other mods installed:
authmod 2.6
binnie mod 2.1.0.41
extraplanets 0.4.4
forestry 5.3.4.202
forgelin 1.5.1
galacticraft planets + core 4.0.0.119
immersive Engineering 0.11.63
Immersive Petroleum 1.1.3
jei 4.5.1.296
JRFTL 1.1 (zombie flesh to leather)
Lingeringloot 3.1
MicDoodlecore 4.0.0.119
Roots 2 0.025
ThutPermissions 1.0.0
Waila 1.7.1

**Comment by spylor** [comment]
It was may bad.

**Comment by spylor** [comment]
I just can't read. :-(

**Comment by bl4ckscor3** [comment]
Yeah, I should really add these special recipes to the JEI interface...
