### ISSUE TITLE
Mod not appearing

### ISSUE THREAD

**Issue by LionEclipse** [Geforce132/SecurityCraft#462]
### Issue description

trying to use securitycraft (1.20.1), all my other 1.20.1 mods work, but securitycraft doesnt appear in the game. any solution? the mod is in the .minecraft mod file.

### Minecraft version

1.20.1

### Forge version

?

### SecurityCraft version

v1.9.7-beta2

**Comment by FewerElk** [comment]
Nothing about security craft or mod loading in the Minecraft logs ?

**Comment by bl4ckscor3** [comment]
Being handled on Discord.
