### ISSUE TITLE
"Minecraft failed to start!"

### ISSUE THREAD

**Issue by Oliwier20B** [Geforce132/SecurityCraft#464]
### Issue description

I start up my 1.12.2 Forge Modpack with the mod included. After Forge finished constructing the mods, the message shown on the screenshot pops up. Without the mod, the modpack works perfectly fine, and I don't know what's the problem.
![Bez tytułu](https://github.com/Geforce132/SecurityCraft/assets/143183907/305aef31-5128-4018-b419-117c50ed51a1)

### Steps to reproduce

1. I got a Forge 1.12.2 pack.
2. Then installed some mods
3. Installed the SecurityCraft mod.
4. Then, the error message shown on the screenshot pops up.

### Minecraft version

1.12,2

### Forge version

14.23.5.2859

### SecurityCraft version

v1.9.7.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

---- Minecraft Crash Report ---- // But it works on my machine.  Time: 2023-08-25 13:28:29 CEST Description: Initializing game  java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader     at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1141)     at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)     at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)     at net.minecraft.client.main.Main.main(SourceFile:123)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)     at crystallauncher.MineClient.start(MineClient.java:228)     at crystallauncher.MineClient.main(MineClient.java:36)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details --   Minecraft Version: 1.12.2   Operating System: Windows 7 (amd64) version 6.1   Java Version: 1.8.0_312, Temurin   Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin   Memory: 1053371344 bytes (1004 MB) / 1476395008 bytes (1408 MB) up to 3892314112 bytes (3712 MB)   JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3700M -Xms400M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0   FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 33 mods loaded, 32 mods active        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored                | State | ID                | Version       | Source                                          | Signature                                |        |:----- |:----------------- |:------------- |:----------------------------------------------- |:---------------------------------------- |        | L     | minecraft         | 1.12.2        | minecraft.jar                                   | None                                     |        | L     | mcp               | 9.42          | minecraft.jar                                   | None                                     |        | L     | FML               | 8.0.99.99     | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |        | L     | forge             | 14.23.5.2859  | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |        | L     | creativecoredummy | 1.0.0         | minecraft.jar                                   | None                                     |        | L     | foamfixcore       | 7.7.4         | minecraft.jar                                   | None                                     |        | L     | obfuscate         | 0.4.2         | minecraft.jar                                   | None                                     |        | L     | securitycraft     | v1.9.7        | [1.12.2]+SecurityCraft+v1.9.7 (2).jar           | None                                     |        | L     | aiimprovements    | 0.0.1.3       | AIImprovements-1.12-0.0.1b3 (2).jar             | None                                     |        | L     | jei               | 4.16.1.1003   | jei_1.12.2-4.16.1.1003 (2).jar                  | None                                     |        | L     | appleskin         | 1.0.14        | AppleSkin-mc1.12-1.0.14 (4).jar                 | None                                     |        | L     | bibliocraft       | 2.4.6         | BiblioCraft[v2.4.6][MC1.12.2] (2).jar           | None                                     |        | L     | carryon           | 1.12.3        | carryon-1.12.2-1.12.7.23 (2).jar                | None                                     |        | L     | clumps            | 3.1.2         | Clumps-3.1.2 (1).jar                            | None                                     |        | L     | corpse            | 1.12.2-1.0.8  | corpse-1.12.2-1.0.8 (2).jar                     | None                                     |        | L     | creativecore      | 1.10.0        | CreativeCore_v1.10.70_mc1.12.2 (2).jar          | None                                     |        | L     | ptrmodellib       | 1.0.5         | PTRLib-1.0.5 (3).jar                            | None                                     |        | L     | props             | 2.6.3.7       | Decocraft-2.6.3.7_1.12.2 (3).jar                | None                                     |        | L     | mclib             | 2.4.2         | mclib-2.4.2-1.12.2.jar                          | None                                     |        | L     | emoticons         | 1.1.2         | emoticons-1.1.2-1.12.2.jar                      | None                                     |        | L     | foamfix           | @VERSION@     | foamfix-0.10.15-1.12.2.jar                      | None                                     |        | L     | cfm               | 6.3.0         | furniture-6.3.2-1.12.2 (4).jar                  | None                                     |        | L     | cgm               | 0.15.3        | guns-0.15.3-1.12.2 (2).jar                      | None                                     |        | L     | harvest           | 1.12-1.2.7-20 | Harvest-1.12-1.2.7-20 (1).jar                   | None                                     |        | L     | jrftl             | 1.1           | JRFTL[1.12.2]-1.1 (3).jar                       | None                                     |        | L     | mcwfurnitures     | 1.0.1         | mcw-furniture-1.0.1-mc1.12.2beta (3).jar        | None                                     |        | L     | phonesalpha       | v1.11         | pa1.11.jar                                      | None                                     |        | L     | toughasnails      | 3.1.0.141     | ToughAsNails-1.12.2-3.1.0.141-universal (3).jar | None                                     |        | L     | trapcraft         | 2.4.5         | Trapcraft-1.12.2-2.4.5 (2).jar                  | None                                     |        | L     | vanillafix        | 1.0.10-150    | VanillaFix-1.0.10-150 (2).jar                   | None                                     |        | L     | vehicle           | 0.44.1        | vehicle-mod-0.44.1-1.12.2 (4).jar               | None                                     |        | L     | worldedit         | 6.1.10        | worldedit-forge-mc1.12.2-6.1.10-dist (2).jar    | None                                     |        | UD    | mclib_core        | 2.4.2         | minecraft.jar                                   | None                                     |   Loaded coremods (and transformers): CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2 (2).jar)                                                                                VanillaFixLoadingPlugin (VanillaFix-1.0.10-150 (2).jar)                                                                                Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)                                         pl.asie.foamfix.coremod.FoamFixTransformer                                       McLib core mod (mclib-2.4.2-1.12.2.jar)                                         mchorse.mclib.core.McLibCMClassTransformer                                       ObfuscatePlugin (obfuscate-0.4.2-1.12.2 (2).jar)                                         com.mrcrayfish.obfuscate.asm.ObfuscateTransformer                                       SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.7 (2).jar)   GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 2500'   Suspected Mods: Unknown   Launched Version: 1.12.2-forge-14.23.5.2859   LWJGL: 2.9.4   OpenGL: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.4276, Intel   GL Caps: Using GL 1.3 multitexturing.            Using GL 1.3 texture combiners.            Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.            Shaders are available because OpenGL 2.1 is supported.            VBOs are available because OpenGL 1.5 is supported.   Using VBOs: Yes   Is Modded: Definitely; Client brand changed to 'fml,forge'   Type: Client (map_client.txt)   Resource Packs:    Current Language: English (US)   Profiler Position: N/A (disabled)   CPU: 4x Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz  [13:28:29] [Client thread/INFO]: [OptiFine] *** Reloading textures *** [13:28:29] [Client thread/INFO]: [pl.asie.foamfix.coremod.patches.ReturnIfBooleanTruePatch:apply:89]: Added return if option true in net/minecraft/client/renderer/texture/TextureMap func_94248_c [13:28:29] [Client thread/INFO]: [OptiFine] Resource packs: Default [13:28:29] [Client thread/INFO]: Reloading ResourceManager: BetterFps, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SecurityCraft, FMLFileResourcePack:AI Improvements, FMLFileResourcePack:AppleSkin, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Carry On, FMLFileResourcePack:Clumps, FMLFileResourcePack:Corpse, FMLFileResourcePack:CreativeCore, FMLFileResourcePack:Decocraft, FMLFileResourcePack:Emoticons, FMLFileResourcePack:FoamFix, FMLFileResourcePack:MrCrayfish's Furniture Mod, FMLFileResourcePack:MrCrayfish's Gun Mod, FMLFileResourcePack:Harvest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Just Another Rotten Flesh to Leather Mod, FMLFileResourcePack:McLib, FMLFileResourcePack:Macaw's Furniture, FMLFileResourcePack:PhonesAlpha, FMLFileResourcePack:ptrmodellib, FMLFileResourcePack:Tough As Nails, FMLFileResourcePack:Trapcraft, FMLFileResourcePack:VanillaFix, FMLFileResourcePack:MrCrayfish's Vehicle Mod, FMLFileResourcePack:WorldEdit, VanillaFix-1.0.10-150 (2).jar [13:28:29] [Client thread/INFO]: [OptiFine] *** Reloading textures *** [13:28:29] [Client thread/INFO]: [OptiFine] Resource packs: Default [13:28:34] [Sound Library Loader/INFO]: Starting up SoundSystem... [13:28:34] [Thread-6/INFO]: Initializing LWJGL OpenAL [13:28:34] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org) [13:28:35] [Thread-6/INFO]: OpenAL initialized. [13:28:35] [Sound Library Loader/INFO]: Sound engine started

**Comment by bl4ckscor3** [comment]
Please try installing the [No Mixin version](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/4605463) of SecurityCraft. If that does not work, try also installing [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility).
