### ISSUE TITLE
Mixins issue, even with no mixins version.

### ISSUE THREAD

**Issue by SfortzaPhantom** [Geforce132/SecurityCraft#465]
### Issue description

Alright, it seems that SecurityCraft doesn't work with Sponge. Here is [the log](https://hastebin.com/share/ifowicunot.ruby) for this issue.

Even "no mixins" version is broken, which seems illogical to me.

### Steps to reproduce

1. cover yourself in oil
2. install SpongeForge (latest) and Forge
3. install securitycraft
4. observe crashes

### Minecraft version

1.12.2

### Forge version

14.23.5.2860

### SecurityCraft version

v1.9.7

### Other relevant versions

spongeforge-1.12.2-2838-7.4.8-RC4142

**Comment by bl4ckscor3** [comment]
No mixin only means that the mixin library is not included in the jar file of SecurityCraft. However we still make use her is it.

**Comment by bl4ckscor3** [comment]
Duplicate of #454.

**Comment by SfortzaPhantom** [comment]
Thanks for poiting it out.
