### ISSUE TITLE
Could you please make a fabric version? I am a fabric player of mc1.19.2, thank you!

### ISSUE THREAD

**Issue by Night-GUA** [Geforce132/SecurityCraft#466]
### Issue description

Could you please make a fabric version? I am a fabric player of mc1.19.2, thank you!

### Minecraft version

1.19.3

### Forge version

Could you please make a fabric version? I am a fabric player of mc1.19.2, thank you!

### SecurityCraft version

v1.9.7.1

### Other relevant versions

Could you please make a fabric version? I am a fabric player of mc1.19.2, thank you!

**Comment by Night-GUA** [comment]
Could you please make a fabric version? I am a fabric player of mc1.19.2, thank you!！

**Comment by bl4ckscor3** [comment]
This issue tracker is for bug reports not for questions. Please use our Discord server for those.

No, there will not be a Fabric version in the foreseeable future.
