### ISSUE TITLE
[Suggestion] Add a « whitelist mode » to inventory scanner

### ISSUE THREAD

**Issue by FewerElk** [Geforce132/SecurityCraft#467]
### Issue description

Inventory scanner doesn’t allow by default items configured. Is it possible to add a whitelist mode that allow ONLY configured items ? If no items configured, will allow players that have any items in their inventory.
EDIT : does the inventory scanner scan shulker boxes or bundles ?

### Minecraft version

1.20.1

### Forge version

NR

### SecurityCraft version

v1.9.7.1

**Comment by bl4ckscor3** [comment]
Please do not use this issue tracker for suggestions. Join our Discord server and create a new post in the suggestions forum.

**Comment by FewerElk** [comment]
I have not discord
