### ISSUE TITLE
Suggestion: Place a modification of timimng to close a Reforced Door

### ISSUE THREAD

**Issue by Lajara930** [Geforce132/SecurityCraft#468]
### Issue description

Can be a good idea place a Timing for close the reenforced door using the block modifier with this we can use a keycard or inventory scanner for open the door for only one way  by controlling the timing of the door close. can be a good implement because with the passcode door and the retina cant use the keycard or inv.scanner for open the door.

### Minecraft version

1.18.2

### Forge version

40.2.10

### SecurityCraft version

v1.9.7

**Comment by Geforce132** [comment]
Our Github issues are used to submit bug reports or to otherwise point out issues in the mod, not for suggestions. You're welcome to join our [Discord server](https://discord.gg/U8DvBAW) and create a thread in the suggestions section where we can discuss the idea further though.
