### ISSUE TITLE
Reinforced Glass

### ISSUE THREAD

**Issue by t0rched** [Geforce132/SecurityCraft#47]
The recipe for reinforced glass appears to be missing all together. 

Version: [1.7.10] SecurityCraft v1.8.2.4

What can I do to fix this for my players?

**Comment by Geforce132** [comment]
We changed the "recipe" of the reinforced glass blocks so you no longer "craft" them in the crafting grid. You now use the Universal Block Reinforcer instead. Either break placed glass blocks with the Reinforcer to reinforce them, or right-click with the U.B.R. in your hand, and a GUI will appear in which you can insert blocks. Once you close the GUI, the blocks will be automatically reinforced and dropped.

**Comment by t0rched** [comment]
My fault brother. Off topic, but how well do the camera's and LookingGlass hold up on a server? Can this be used in "production"? Or does it lag players and/or the server?

Thank you again. Excellent mod.

**Comment by bl4ckscor3** [comment]
It's not very lightweight. The more cameras there are, the heavier the impact.

**Comment by Cireelim** [comment]
Back to topic... I placed a glass-block and hit it with the UBR and now I have a block of reinforced glass on my floor. And I cant break it with the UBR. Great mod. Easy to understand...
