### ISSUE TITLE
1.12.2 Minecraft fails to start

### ISSUE THREAD

**Issue by DylanJ3191** [Geforce132/SecurityCraft#475]
### Issue description

*Crash report below*
At the most recent version, Minecraft won't start, but if I remove Security Craft or change it to version 1.8.20.2 it will start without a problem.

(Thoughts) Maybe it's just the mods I have installed... They are listed in the crash report.

### Minecraft version

1.12.2

### Forge version

14.23.5.2860

### SecurityCraft version

v1.9.7

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Ec4gDX79

**Comment by bl4ckscor3** [comment]
Duplicate of #300
