### ISSUE TITLE
Projector Dupe Glitch

### ISSUE THREAD

**Issue by HumdrumPanic** [Geforce132/SecurityCraft#478]
### Issue description

Rotating the projector causes the item to pop out while also remaining inside causing a duplication. Not my discovery just reporting a dupe glitch that appears to have never been reported here. 

where I noticed it:
https://github.com/AllTheMods/ATM-8/issues/817

Has way more info

### Minecraft version

1.19.4

### Forge version

43.2.14

### SecurityCraft version

Older (update the mod and try again with the new version before continuing.)

### Other relevant versions

[1.19.2] SecurityCraft v1.9.6.1.jar

No dropdown option  for 1.19.2 minecraft version

**Comment by bl4ckscor3** [comment]
This was fixed in v1.9.8 of the mod. There is no 1.19.2 in the dropdown because we no longer update the mod for that version.
