### ISSUE TITLE
Can I share this mod in China?

### ISSUE THREAD

**Issue by 6Bpencle** [Geforce132/SecurityCraft#48]
The mod is very interesting ,I very like it.I think you can do it better.So I want to share this mod with the minecraft forum in China.This is [website](http://www.mcbbs.net),and let more friends use it.I hope you can agree!

**Comment by bl4ckscor3** [comment]
Yes, under the following conditions:

1. Do NOT rehost the mod. Link to the official [download page](https://minecraft.curseforge.com/projects/security-craft/files).
2. You clearly state that the mod is NOT made by you and that Geforce and bl4ckscor3 are the only authors.
3. Reply to this issue with a link to the post you created on the forum.

Thanks! :)
