### ISSUE TITLE
Crash at server launch

### ISSUE THREAD

**Issue by IPSEON** [Geforce132/SecurityCraft#480]
### Issue description

Simply crash my serv when i start it.

I try multiple version of Security Craft.

### Minecraft version

1.19.4

### Forge version

45.2.0

### SecurityCraft version

v1.9.8

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/WUkpKdPD

**Comment by bl4ckscor3** [comment]
Please try without Arclight, hybrid servers are bound to cause issues like these. If an issue is caused by such a server software, we won't be fixing it as it is hard to track down and maintain.

**Comment by IPSEON** [comment]
So sad... This mod is unbelievable, but i can't remove Arclight

**Comment by Wdits** [comment]
i'm also running arclight, works flawlessly, try arclight 1.20.1 with forge 47.2.0

**Comment by FewerElk** [comment]
I got a crash in similar condition with only Optifine and securitycraft when I connected to the official mc server.

**Comment by FewerElk** [comment]
I got a crash in similar condition with only Optifine and securitycraft when I connect to the official mc server.

**Comment by IPSEON** [comment]
Thanks guys for your answer, i'll try that
