### ISSUE TITLE
Crash immediately after entering a newly created world

### ISSUE THREAD

**Issue by ChromaPIE** [Geforce132/SecurityCraft#481]
### Issue description

Dont know if its actually caused by SecurityCraft tho

crash report: https://mclo.gs/61JhYaz

### Minecraft version

1.12.2

### Forge version

2860

### SecurityCraft version

v1.9.8

**Comment by bl4ckscor3** [comment]
Try removing OptiFine.

**Comment by ChromaPIE** [comment]
Sorry that's actually caused by some tweaks i made to lost cities' generation palette being messed up
