### ISSUE TITLE
keypad doors their password is visible when using create mod

### ISSUE THREAD

**Issue by judojonas** [Geforce132/SecurityCraft#482]
### Issue description

password doors their password is visible when using create mod

![afbeelding_2023-12-05_171257674](https://github.com/Geforce132/SecurityCraft/assets/147813783/acc4a921-3130-42c3-915b-75295f1fd61a)

### Steps to reproduce

instal creatmod and security craft
start your forgeprofile
look at a keypad door

### Minecraft version

1.19.3

### Forge version

43.2.21

### SecurityCraft version

v1.9.7/.1

### Other relevant versions

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.19.2-1.2.2.236.jar
Kotlin for Forge
thedarkcolour
kotlinforforge-3.12.0-all.jar
Lazy DataFixerUpper(LazyDFU) [FORGE]
Corgi_Taco
lazydfu-1.19-1.0.2.jar
Litematica
masady
litematica-fabric-1.20.2-0.16.0.jar
Mouse Tweaks
YaLTeR
MouseTweaks-forge-mc1.19-2.23.jar
MrCrayfish's Gun Mod
MrCrayfish
cgm-forge-1.19.2-1.3.7.jar
Oculus
Asek3
oculus-mc1.19.2-1.6.4.jar
Rechiseled
SuperMartijn642
rechiseled-1.1.2-forge-mc1.19.2.jar
Rechiseled: Create
SuperMartijn642
rechiseledcreate-1.0.0-forge-mc1.19.jar
Rubidium
Asek3
rubidium-0.6.2b.jar
Searchables
Jaredlll08
Searchables-forge-1.19.2-1.0.2.jar

**Comment by bl4ckscor3** [comment]
This is a non-issue.
1. The mod showing the passcode is Jade/TOP or similar, not Create
2. v1.9.7 does not exist for 1.19.2
3. The passcode only shows for the owner
4. You can turn off the passcode in Jade's config, accessible by pressing numpad 0 by default.
5. As of v1.9.7 of the mod we've changed how passcodes are stored, and they no longer exist in plaintext and aren't shown by Jade etc. anymore.
