### ISSUE TITLE
Crash at Launch with Optifine 1.12.2

### ISSUE THREAD

**Issue by TimbreTern** [Geforce132/SecurityCraft#483]
### Issue description

I cannot find a way to play Security Craft with Optifine, however, I don't see it listed as a conflict anywhere else. Is this incompatible? I've searched the other fixes and here are the fixes I have tried. None have been successful yet.
> 1. Using the no mixin version.
> 2. Adding the Mixin 0.7-0.8 Compatability mod with the no mixin version.
> 3. Adding the Mixin 0.7-0.8 Compatability mod with the regular version.
> 4. Using the no mixin version while removing the portal teleporter in the mixin.json described in #454.
> 5. Using the regular version while removing the portal teleporter in the mixin.json described in #454.

Here's the crash report. The only thing that fixes this is removing Optifine, but it is necessary for other mods in the pack, so I would like to keep it. Removing Optifine makes the mod work with just the regular version though.

### Minecraft version

1.12.2

### Forge version

14.23.5.2858

### SecurityCraft version

v1.9.8

### Other relevant versions

SC v1.9.8 - No mixin included

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/TimbreTern/175fb0efe8355a7bcbdd7fe061b56615

**Comment by bl4ckscor3** [comment]
The crash report mentions a Mixin from the mod Fusion erroring. Try removing that and see if it works then.

**Comment by TimbreTern** [comment]
That's embarrassing. For some reason I thought the mentions of Fusion were part of the assembly language. This is fixed now, and it runs fine.

For others seeing this later, I still have the no-mixin version installed with the Mixin 0.7-0.8 Compatability mod and the portal.teleporter removed from the json file.

**Comment by bl4ckscor3** [comment]
Note: I do not think you should need to remove the TeleporterMixin. Removing it was a temporary fix I mentioned that could be applied prior to us releasing the update with the proper fix. As you are using v1.9.8 where a fix for the underlying issue is included, you should be just fine with leaving the TeleporterMixin line in.

**Comment by TimbreTern** [comment]
Thanks so much. I did a fresh install and it worked with the regular v1.9.8 file.
