### ISSUE TITLE
Block's Turning into other blocks but whithout the other blocks functionality and some of it's functionality.

### ISSUE THREAD

**Issue by 29LHR** [Geforce132/SecurityCraft#484]
### Issue description

Every time I put down a securitycraft block on my server it turns into another block from another mod or it's own mod. It used to work on my other server. Then these blocks don't have the securitycraft block I placed down functionalities or the blocks it turned into.

### Steps to reproduce

1. Go into Creative
2. Pick a SecurityCraft block
3. Place down the block

### Minecraft version

1.20.4

### Forge version

47.2.0

### SecurityCraft version

v1.9.8

### Other relevant versions

1. MrCrayfish's Furniture Mod, cfm-forge-1.20.1-7.0.0-pre36.jar
2. I have other mods enabled but they don't seem to be the blocks the security craft blocks are turning into

**Comment by bl4ckscor3** [comment]
I cannot reproduce this with the given versions. This also does not sound like a mod problem, but rather an installation problem. This sort of thing can happen when the server and client don't have the exact same mods installed and aren't configured the same way.
