### ISSUE TITLE
Cheat mode on JEI drops a duplicate "ghost" item after opening rift stabilizer GUI in Survival Mode

### ISSUE THREAD

**Issue by MyUsernameisAstro** [Geforce132/SecurityCraft#486]
### Issue description

Not sure if to post this bug on JEI repository or here, but after opening the Rift stabilizer GUI, spawning in an item with JEI's cheat mode in Survival Mode will result in 2 copies of the item being created. One will appear on the floor, and one will appear in your inventory. The one that is dropped on the floor functions as expected, however the copy that is in your inventory will disappear after being used (i.e placing it if it's a block, throwing if a projectile etc) or won't be usable at all. I attached a video which hopefully demonstrates the problem well.

The problem gets fixed after relogging, I'm playing on singleplayer, no other mods but Optifine, JEI and Securitycraft.

https://github.com/Geforce132/SecurityCraft/assets/107489039/31f0a864-2784-4212-9863-2a8068e63c89

### Steps to reproduce

1. Place Rift Stabilizer
2. Right click rift stabilizer to open GUI
3. Turn on cheat mode for JEI
4. Go in survival and try to spawn item

Two copies should be created of the item, one will drop on the floor and is the working item, the one in your inventory will be glitched.

### Minecraft version

1.12.2

### Forge version

14.23.5.2859

### SecurityCraft version

v1.9.8

### Other relevant versions

JEI Version/Filename - jei_1.12.2-4.16.1.301

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Et00CUq7

**Comment by bl4ckscor3** [comment]
I can't reproduce this. Does this still happen if you remove OptiFine?

https://github.com/Geforce132/SecurityCraft/assets/5149876/ffd2f2f0-e372-422e-b6ed-bfc4be0a7055

**Comment by MyUsernameisAstro** [comment]
You need to be in survival for the glitch to occur, for some reason it doesn't happen while in creative mode. Also just to make sure I tested and yes it still occurs without optifine

**Comment by bl4ckscor3** [comment]
Oh, I completely glossed over that part. My bad. I can reproduce it now, and it also happens in other GUIs like the Alarm's.
