### ISSUE TITLE
Possible Mod Incompatibility with Man from the Fog: The Man can destroy Reinforced Iron Doors

### ISSUE THREAD

**Issue by Daralexen05** [Geforce132/SecurityCraft#487]
### Issue description

The title says it all. The Man can still destroy and instantly break Reinforced Iron Doors like they were normal wooden doors. I cannot tell if this is an issue on SecurityCraft's end or Man From the Fog's end. Since The Man like most "Dweller" mods is full of critical bugs and oversights. Especially with other mods. Aren't the reinforced blocks supposed to be immune to all griefing and destruction aside from being removed by the player that placed them? He will also destroy the doors in their item form with lightning if he cannot get inside due to his awful AI, which is very frustrating.

### Steps to reproduce

1. Build a small shelter that uses an Enhanced Iron Door as an entrance.
2. Spawn "ManAggressive" via commands outside the shelter in Creative or wait for him to naturally spawn and start his "chase sequence."
3. 3. Be inside the shelter protected by the Enhanced Iron Door and watch the Man break it and one-shot you.

### Minecraft version

1.20.1

### Forge version

forge-1.20.1-47.2.0.

### SecurityCraft version

v1.9.8

### Other relevant versions

The latest release of Man From the Fog for 1.20.1

**Comment by bl4ckscor3** [comment]
This is something to report to the Dev(s) of Man from the Fog. SecurityCraft's block have the same hardness and resistance as bedrock, which generally is something that needs to be respected when checking for breakability.

**Comment by Daralexen05** [comment]
> This is something to report to the Dev(s) of Man from the Fog. SecurityCraft's block have the same hardness and resistance as bedrock, which generally is something that needs to be respected when checking for breakability.
Thank you so much. I guess the mod maker programmed The Man's griefing patterns to instantly break any block classified as a door or glass regardless of hardness. Since he also instantly destroys normal Iron Doors and Doors from other mods. The Man and many other Cave Dweller clones that were made just for clout on YouTube do suffer from a lot of bugs that make them more frustrating and annoying to play with than fun for general survival. I guess I will keep my "doormat" system in place for the entrance to my bunker to keep him out. Since mobs cannot walk over Moss Layers for some reason.

**Comment by Daralexen05** [comment]
I also might test more of his behaviours with the mod such as seeing if he will react to being viewed in a security camera.

**Comment by Daralexen05** [comment]
> This is something to report to the Dev(s) of Man from the Fog. You're right in that only the owner of a block is supposed to be able to remove it. Mods that don't respect this are broken in that regard. There is nothing special with how SecurityCraft's blocks handle this, they simply have the same hardness and resistance as bedrock, which generally is something that needs to be respected when checking for breakability.

I am not sure if you will see this, but I did do further testing with the Man and his reactions to SecurityCraft, and he cannot break Reinforced Glass or Reinforced Glass Panes. He also does not react to being viewed on a Security Camera. I also reached out to the Man From the Fog developer, and he said that the Man is programmed to break any block with the door and glass tags regardless of hardness value and that this bug will most likely not be patched. I find it odd that he cannot break Reinforced Glass though, even with the dev stating the programming of their mob. I think that it is just cheap/unfair that a boss-like entity that spawns every night can break blocks as hard as bedrock.

**Comment by bl4ckscor3** [comment]
Reinforced glass and reinforced glass panes are not in the glass tags added by Forge (vanilla doesn't have any). I am guessing that's why the Man can't break them. As for the door problem, you should be able to fix it by removing SecurityCraft's doors from the door tag. Though I'm not sure how to accomplish that apart from outright removing the tag json file from SecurityCraft's jar file.
