### ISSUE TITLE
Crash when in Creative and opening inventory.

### ISSUE THREAD

**Issue by Xlaits** [Geforce132/SecurityCraft#488]
### Issue description

See title. Crashlog attached.

### Steps to reproduce

1. Be in creative mode
2. Open inventory.

### Minecraft version

1.20.1

### Forge version

47.2.0

### SecurityCraft version

v1.9.8

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

[crash-2024-01-17_11.46.21-client.txt](https://github.com/Geforce132/SecurityCraft/files/13966213/crash-2024-01-17_11.46.21-client.txt)

**Comment by bl4ckscor3** [comment]
This has already been fixed in the next version of the mod, thank you for reporting! The crash only happens when using certain other mods (Roughly Enough Items being one of them).

**Comment by bl4ckscor3** [comment]
For the record, fixed in d9260826c7777e9c9fd7f0f0fe5769fc3260b70d
