### ISSUE TITLE
Game Started Crashing out of no where

### ISSUE THREAD

**Issue by ModernGamingWorld** [Geforce132/SecurityCraft#491]
### Issue description

java.lang.IllegalArgumentException: Comparison method violates its general contract!

### Steps to reproduce

Not sure, its happening in my custom modpack with over 500 mods

### Minecraft version

1.20.1

### Forge version

47.2.20

### SecurityCraft version

v1.9.8

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/ModernGamingWorld/5d94fb1f7ff32151753e9a032c7ea769

**Comment by bl4ckscor3** [comment]
Duplicate of #488.
