### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

### ISSUE THREAD

**Issue by Artem-VV** [Geforce132/SecurityCraft#492]
### Issue description

When I trying to move a block to a universal block reinforcer the client crashes.
Log attached.

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2859

### SecurityCraft version

v1.9.8

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/FXbKdCU3

**Comment by bl4ckscor3** [comment]
Please redownload SecurityCraft from [CurseForge](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/4795499) or [Modrinth](https://cdn.modrinth.com/data/v8jzRtAt/versions/hkgADf1T/%5B1.12.2%5D%20SecurityCraft%20v1.9.8.jar), as we were notified of and fixed this crash shortly after initial release. Thanks for reporting though, it's very much appreciated!

**Comment by Artem-VV** [comment]
Thank you very much, this helped.
