### ISSUE TITLE
crash 1.20.1 forge 

### ISSUE THREAD

**Issue by Thunderrock424242** [Geforce132/SecurityCraft#493]
### Issue description

crash when loading a game 

### Steps to reproduce

use my modpack if you need the zip lmk

### Minecraft version

1.20.1

### Forge version

47.2.0

### SecurityCraft version

v1.9.8

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/gTXydrQ

**Comment by bl4ckscor3** [comment]
This is a crash caused by `respawn_animals`. Please report this issue to that mod's author.
