### ISSUE TITLE
Constant Global Invalid Update Packet Spam

### ISSUE THREAD

**Issue by Renno231** [Geforce132/SecurityCraft#499]
### Issue description

I've been experiencing periodic and significant desyncs and in my hunt to find the source I found the following in my client log (I have censored relevant identifying playerdata to main the privacy of the players).
[securitycraft bug report.txt](https://github.com/Geforce132/SecurityCraft/files/14733427/securitycraft.bug.report.txt)

### Minecraft version

1.12.2

### Forge version

14.23.5.2860

### SecurityCraft version

v1.9.8

**Comment by bl4ckscor3** [comment]
I believe there should be a fix for the cause of this in the next update, which we will release within the next 24 hours. This means that after updating, the log entries will not stop, but what caused them to start showing up would no longer be happening. So after updating, break and replace the affected blocks and see if the log starts appearing again (if I am right about my assumption that should not happen), and please report back your findings!

**Comment by bl4ckscor3** [comment]
Closing this as no further issues have been reported after the update with the potential fix.
