### ISSUE TITLE
Ability to do cross dimension on cameras

### ISSUE THREAD

**Issue by OCDiary** [Geforce132/SecurityCraft#50]
Hi,
I want to add this to my modpack, but the issue is I kinda need the cameras to work cross dimension! Is there any way this can be added into the config as a customisation option at all?
Thanks
OC

**Comment by bl4ckscor3** [comment]
To quote someone on our Discord server: "Cross dimension cameras? Yeah, that won't work unless you wanna have a loading everytime you switch to that camera and exit it."
