### ISSUE TITLE
Crash 1.20.1 - 1.9.9 - java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by lupiiiin** [Geforce132/SecurityCraft#500]
### Issue description

When starting a game and opening the inventory the game crashes sometimes.

The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Comparison method violates its general contract!

"https://pastebin.com/W2v84q0T
	

### Steps to reproduce

Start a new game and open the inventory (only on certain occasions)

### Minecraft version

1.20.1

### Forge version

47.2.23

### SecurityCraft version

v1.9.9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/W2v84q0T

**Comment by bl4ckscor3** [comment]
We included a fix for this in v1.9.9, but evidently it does not fully work. What other mods are you using? They're not in the crash report.

**Comment by lupiiiin** [comment]
[2024-04-05-3.log.gz](https://github.com/Geforce132/SecurityCraft/files/14898903/2024-04-05-3.log.gz)

I send you the complete crash with the list of mods.

**Comment by bl4ckscor3** [comment]
Thank you! I would appreciate if you could try out [this development version of the mod](https://cdn.discordapp.com/attachments/402175060716158986/1226833438305423421/securitycraft-1.9.9-creative-tab-crash-fix.jar?ex=662634ad&is=6613bfad&hm=5b24aec50c90072701c94f500140758c045c87e0719f3dbcd39b48d1ddb62c85&), to see if the fix I applied in it works for you.

**Comment by harryxd-x** [comment]
finally The development version of the mod won't crash when i open my inventory in creative mode :>

**Comment by bl4ckscor3** [comment]
Thanks for testing! However I'm sorry for asking again, but I noticed a logical error in my fix, which resulted in SecurityCraft's creative tabs not being sorted properly (they should match vanilla tab sorting). Hence [here's a second development version](https://cdn.discordapp.com/attachments/402175060716158986/1226848973093081088/securitycraft-1.9.9-second-creative-tab-crash-fix.jar?ex=66264324&is=6613ce24&hm=3950a8d195ed0dc7521e0ef39c879c6be521a9d0f0be866448b9b450dd79de76&) with the fixed fix, which I would again greatly appreciate if you tried it out. I'm sorry for this error on my part.
This version should have the crash fix + correctly sorted tabs. Thank you in advance for verifying!

**Comment by harryxd-x** [comment]
Sorry for late reply it still good and the sorted tabs match vanilla tab sorting now

**Comment by bl4ckscor3** [comment]
No worries, thank you so much for testing!
