### ISSUE TITLE
Security Craft crashes the Debug world

### ISSUE THREAD

**Issue by Lolothepro** [Geforce132/SecurityCraft#501]
### Issue description

Security Craft crashes the Debug world

### Steps to reproduce

1. Generate a "Debug" world
2. Generate all chunks
3. See that Minecraft server side crashes

### Minecraft version

1.20.4

### Forge version

20.4.232

### SecurityCraft version

Older (update the mod and try again with the new version before continuing.)

### Other relevant versions

It's SC v1.4.2024

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/KErxqb0

**Comment by bl4ckscor3** [comment]
Looks like we already fixed this in dev with commit a5c0b4324d82a7f7003d734aa064d465f80c3889. Thanks for reporting!
