### ISSUE TITLE
Stuck after exiting camera

### ISSUE THREAD

**Issue by CREATIVE-CRE4** [Geforce132/SecurityCraft#503]
### Issue description

After exiting the camera, the player can do nothing but turn his head. The rest of the actions either don't work or don't work properly.

The video shows the moment with the bug. After placing the player on the edges of the chunks, this happens.
https://github.com/Geforce132/SecurityCraft/assets/168589908/23f50997-1ec3-434a-987e-3710a156af81

Although there have been reports of this bug, I still hope that it will give some results.

### Steps to reproduce

Stand on the edges of chunks

### Minecraft version

1.12.2

### Forge version

14.23.5.2860

### SecurityCraft version

v1.9.9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/CREATIVE-CRE4/c43bbfa9a03bd0bf2e328651b0d61f0b

**Comment by bl4ckscor3** [comment]
Related to #457 and #436

**Comment by CREATIVE-CRE4** [comment]
Sorry, the previous logs were not completely copied. Here is the link to the file.

[debug.log](https://github.com/Geforce132/SecurityCraft/files/15170499/debug.log)

**Comment by CREATIVE-CRE4** [comment]
Is there any progress on fixing the bug?

**Comment by bl4ckscor3** [comment]
The bug has not been fixed, so no. We can't reproduce it, and we have no idea what causes it.
