### ISSUE TITLE
security craft 1.20.1 forge crashes whenever opens camera on multiplayer

### ISSUE THREAD

**Issue by JamesTheFroggo** [Geforce132/SecurityCraft#504]
### Issue description

I'm playing with a friend using the essentials mod and the game of whoever opens the camera crashes whenever they open the cameras we're using a bunch of different mods I couldn't get anything out of the Log but I can get a log if needed

### Steps to reproduce

1. Join a friend through Essentials
2. Place a camera
3. Open the camera

### Minecraft version

1.20.1

### Forge version

47.2.0

### SecurityCraft version

v1.9.9

**Comment by bl4ckscor3** [comment]
Please include the crash report.

**Comment by bl4ckscor3** [comment]
Closing this as we weren't able to reproduce this with the reproduction steps given, and also haven't received a crash report.
