### ISSUE TITLE
[1.7.10] Camera Monitor not working

### ISSUE THREAD

**Issue by Shahelion** [Geforce132/SecurityCraft#505]
### Issue description

I have bound it to a camera, but I can't actually use it to view the camera's feed. Also, I can only bind it to one camera at a time, despite the tooltip showing 1/30.

I know that 1.7.10 is most likely unsupported. I don't expect an update to the mod, I'd mostly just like to know if I did something wrong or maybe there's some way to fix it on my end.

### Minecraft version

1.7.10

### Forge version

10.13.4.1614

### SecurityCraft version

1.8.13, the latest for 1.7.10.

**Comment by bl4ckscor3** [comment]
With only SecurityCraft installed, I can use the camera monitor just fine. When I install LookingGlass, I experience the same behavior, but that's intentional as only one camera can be shown on the monitor's feed at once.

**Comment by Shahelion** [comment]
I disabled the looking glass option and it works fine, it's just with it enabled that it doesn't work. The monitor stays black and can't be used, after linking to a camera.

**Comment by bl4ckscor3** [comment]
Yeah the looking glass config option is made to only be used when [LookingGlass](https://www.curseforge.com/minecraft/mc-mods/lookingglass) is installed. I think we made it so that it automatically turns it on or off based on the presence of that mod, but I could be wrong.

**Comment by Shahelion** [comment]
I do have LookingGlass, though. With that option enabled, it should be working.

**Comment by bl4ckscor3** [comment]
Ah, sorry that wasn't clear to me. Perhaps there is some other mod which interferes with LookingGlass. I remember we used to have a few problems like these that we were never quite sure about.

**Comment by Shahelion** [comment]
https://gist.github.com/Shahelion/7317c71538ef6e1a2c4aa9c15d3a1295

That's the mod list. Unfortunately, it's difficult to remove chunks of mods to see which one is at fault, due to how everything is entwined together. A binary search would likely cause many unrelated issues and crashes.

**Comment by bl4ckscor3** [comment]
Any performance mod, mods that change rendering, etc. could theoretically interfere with this. I see you have MystCraft installed - do the dimension previews work there? They use LookingGlass as well.

**Comment by Shahelion** [comment]
I actually had LookingGlass for Mystcraft already, just updated it for SecurityCraft (required 0.2.0.01). I just checked, the book previews actually don't work anymore. They did with the version of LookingGlass I had previously (0.2.0.00), but that one didn't work with SecurityCraft. So, something in that update broke everything?

**Comment by bl4ckscor3** [comment]
SecurityCraft seems to only be compatible with LookingGlass 0.2.0.01. I tried spoofing the version by editing the jar file, but that didn't work. So I think you're out of luck here, I'm afraid :/

**Comment by Shahelion** [comment]
Would it be possible to remove the dependency on LookingGlass? The LG option for SC doesn't even work for me. That way I could downgrade it to have it working with Mystcraft.

**Comment by bl4ckscor3** [comment]
I don't have the means to create a new 1.7.10 version anymore. The only solution I have for you is to open the SecurityCraft jar file, navigating to `net/geforcemods/securitycraft`, and opening `SecurityCraft.class` with a normal text editor. Then, in the 4th or so line, you'll see `after:LookingGlass@[0.2.0.01,);`. Replace exactly those characters (no more no less) with exactly these (no more no less): `after:LookingGlass@[0.2.0.00,);` (for reference, the only difference is the `01` having been changed to `00`). That'll lower the minimum version of LookingGlass that SecurityCraft needs. You then need to make sure the LookingGlass config is turned off, otherwise the game will crash when you rightclick a camera with a monitor. I'm aware this solution is not ideal if you want to distribute the modpack.

**Comment by Shahelion** [comment]
So, it looks like that just prevented SecurityCraft from loading at all. I changed the 1 to 0, and put back the older version of LookingGlass, but SecurityCraft stuff is gone from the game.

**Comment by bl4ckscor3** [comment]
Hm. I did the same with the following file, and that one loads fine for me. (Replace the file ending `.zip` with `.jar` before using this file)
[[1.7.10] SecurityCraft v1.8.13.zip](https://github.com/Geforce132/SecurityCraft/files/15474615/1.7.10.SecurityCraft.v1.8.13.zip)

**Comment by Shahelion** [comment]
Not sure why, but that worked. Thank you!

**Comment by Shahelion** [comment]
Oh yeah, definitely something is very wrong with LookingGlass. I spawned in a new linking book and opened it, and the console gave me this: https://gist.github.com/Shahelion/c060636355b155e6e6750d7c3b8b64e4

Note that I only had the book open for a few seconds.

**Comment by bl4ckscor3** [comment]
Ah, it looks like LookingGlass is incompatible with NEID. I only have NEID, SecurityCraft, and LookingGlass installed (the proper versions, unedited), and trying to get an image on a camera monitor doesn't work - I just get a black screen like you do.

**Comment by Shahelion** [comment]
Maybe I'll give the GTNH fork a try.
