### ISSUE TITLE
Crash When Attempting To Opening Inventory in Create Mode [1.20.1] 

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [Geforce132/SecurityCraft#506]
### Issue description

Crash occurs immediately after pressing "E" to open inventory. Not Enough Crashes is installed so there is an option to return to the main menu after receiving the crash. I haven't tested without SecurityCraft to see if it's SecurityCraft is just catching a problem further down the line, I will update if it appears to be the case.

### Steps to reproduce

Open inventory in creative mode (unsure if being in create is necessary for the crash) while mods listed in crash report are installed.

### Minecraft version

1.20.1

### Forge version

47.2.32

### SecurityCraft version

v1.9.9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/caniplzjustlogin4godsakesthistakesforev/91dd77809de5132f34700b1e15614797

**Comment by bl4ckscor3** [comment]
Duplicate of #500. Here's a fix version for 1.20.1 (replace the .zip file ending with .jar before using)
[securitycraft-1.9.9-second-creative-tab-crash-fix.zip](https://github.com/Geforce132/SecurityCraft/files/15430418/securitycraft-1.9.9-second-creative-tab-crash-fix.zip)
