### ISSUE TITLE
Server does not launch

### ISSUE THREAD

**Issue by Samino2** [Geforce132/SecurityCraft#51]
My moded server have problem with security craft =|

This is the log in question:
[fml-server-latest.log](https://github.com/Geforce132/SecurityCraft/files/1734912/fml-server-latest.log)

**Comment by bl4ckscor3** [comment]
When does the server crash?

**Comment by Samino2** [comment]
The server don't launch =[

**Comment by bl4ckscor3** [comment]
Try redownloading the latest SecurityCraft version and see if that fixes it.

**Comment by Samino2** [comment]
(I am in 1.7.10)

**Comment by bl4ckscor3** [comment]
I know

**Comment by bl4ckscor3** [comment]
Can you give me the new server log, please?

**Comment by Samino2** [comment]
Sure:

[fml-server-latest.log](https://github.com/Geforce132/SecurityCraft/files/1734965/fml-server-latest.log)

**Comment by bl4ckscor3** [comment]
You didn't do what I wrote above. Download the newest version, please.

**Comment by Samino2** [comment]
On curse the last version is the 1.8.4 version of the mod

**Comment by bl4ckscor3** [comment]
Download v1.8.4.1. I edited my previous comment because I forgot that I didn't change the version number that is displayed in the crashlogs for that revision.

**Comment by bl4ckscor3** [comment]
Are both client and server using the same version?

**Comment by Samino2** [comment]
yes, but its at the initialisation who the server crash (The server is host at LocationMinecraft.com)

**Comment by bl4ckscor3** [comment]
So the error here is that Minecraft cannot find the main mod file. But if you look into SecurityCraft's .jar file, `net/geforcemods/securitycraft/SecurityCraft.class` is present. So I don't know what the issue here is...

**Comment by Samino2** [comment]
oki doki, thanks anymay ^^

**Comment by bl4ckscor3** [comment]
Last idea I have, try [this file](https://www.dropbox.com/s/l8zsbqxa77dbirm/%5B1.7.10%5D%20SecurityCraft%20v1.8.4.jar?dl=1).

**Comment by Samino2** [comment]
don't work =(

**Comment by bl4ckscor3** [comment]
That file is working for me locally with Forge #1614 and only SecurityCraft. I would guess it's something with your modpack :/

**Comment by Samino2** [comment]
Surely = | thank you so much for your time ^^

**Comment by bl4ckscor3** [comment]
You shouldn't be downloading your mods from anywhere else other than Curse, anyways. Those sites do not support the mod authors and are often shipping the mod files with malware. More info: http://stopmodreposts.org/
