### ISSUE TITLE
Startup crash when installed alongside "Simple Uncrafting Table"

### ISSUE THREAD

**Issue by Omegacrafterhd** [Geforce132/SecurityCraft#510]
### Issue description

It wont start up the game correctly when using the "Simple Uncrafting Table" mod by Pitan 76

### Steps to reproduce

Step 1 install mods

Step 2 Join the game

Step 3 Crash

Step 4 fix

### Minecraft version

1.18.2

### Forge version

40.2.21

### SecurityCraft version

v1.9.9

### Simple Uncrafting Table

v1.3.1

_No response_

**Comment by bl4ckscor3** [comment]
I can load into a world just fine with these mods intalled. Please post your crash report.
 ![](https://i.imgur.com/O4SyZjE.png)

**Comment by Omegacrafterhd** [comment]
I forgot to tell you, That the UncraftingTable 1.3.4 doesnt even work. the item doesnt show up nothing. i used 1.3.1 of simple uncrafting table

**Comment by Leon1324765s** [comment]
Having the same Problem. 1.3.4 doesn't show the uncrafting table and the crafting recipe isn't working too. It's just working on version 1.3.1 as Omega said, but It's not working with SecurityCraft

**Comment by bl4ckscor3** [comment]
Works fine for me using 1.3.1 instead. Again, please post the crash report.

![](https://i.imgur.com/nWMlzVg.png)

**Comment by Leon1324765s** [comment]
[crash-2024-06-01_20.17.14-fml.txt](https://github.com/user-attachments/files/15522890/crash-2024-06-01_20.17.14-fml.txt)

**Comment by bl4ckscor3** [comment]
Yeah that error you posted does not point towards anything to do with SecurityCraft. Perhaps if you still have the older crash report from when it did get caused by SC, you could post it. That would be appreciated.
