### ISSUE TITLE
Game crash when open Inventory in Creative

### ISSUE THREAD

**Issue by shinei01** [Geforce132/SecurityCraft#512]
### Issue description

Any time you are in creative mode and you try to open your Inventory the game is crashing

### Minecraft version

1.20.1

### Forge version

47.2.32

### SecurityCraft version

v1.9.9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://bytebin.lucko.me/cmgDzMTMn6

**Comment by bl4ckscor3** [comment]
Duplicate of https://github.com/Geforce132/SecurityCraft/issues/500. Here's a fix version for 1.20.1 (replace the .zip file ending with .jar before using)
[securitycraft-1.9.9-second-creative-tab-crash-fix.zip](https://github.com/Geforce132/SecurityCraft/files/15430418/securitycraft-1.9.9-second-creative-tab-crash-fix.zip)
