### ISSUE TITLE
Sentry Crash On 1.21

### ISSUE THREAD

**Issue by AverageTurtle** [Geforce132/SecurityCraft#515]
### Issue description

When the sentry attempts to shoot it crashes the game

### Steps to reproduce

1. Place Sentry
2. Spawn Mob
3. Game Crashes

### Minecraft version

1.21

### Forge/NeoForge version

21.0.6-beta

### SecurityCraft version

v1.9.10

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/xFY00KfM

**Comment by bl4ckscor3** [comment]
Thank you very much for reporting! We'll release a fix for this momentarily.
