### ISSUE TITLE
Crash Mod 1.16.5 - 1.9.10

### ISSUE THREAD

**Issue by ForTyxx13** [Geforce132/SecurityCraft#516]
### Issue description

Hello, I am making this post to warn you of a crash during the latest version of Security Craft version 1.9.10 for Minecraft 1.16.5. When I enter the world I open the instruction book and scroll and I get a screen crash. The error is unknown. I tried several times but nothing works, so I have to go back to version 1.9.9 of the mod.

### Steps to reproduce

1. Starts Minecraft with SecurityCraft 1.9.10 for 1.16.5 ; 2. Enter in a random world ; 3. Open the SecurityCraft manual ; 4. Go to the next page -> Screen Crash

### Minecraft version

1.16.5

### Forge/NeoForge version

36.2.34

### SecurityCraft version

v1.9.9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/6jiiu5p7

**Comment by bl4ckscor3** [comment]
Thank you very much for reporting! We'll release a version that fixes this momentarily.
