### ISSUE TITLE
Neoforge Issue

### ISSUE THREAD

**Issue by whydoiexist1232** [Geforce132/SecurityCraft#517]
### Issue description

Tried to connect to the nodecraft server, with the proper neoforge version still says channels are missing, shoulda connected.

### Steps to reproduce
1. use neoforge 2.6.116 and securitycraft on modrinth (DO NOT TELL ME TO USE CURSEFORGE!!!!!!!!)
2. connect.
### Minecraft version

1.20.6

### Forge/NeoForge version

2.6.116

### SecurityCraft version

v1.9.10.2

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/wNQZSkLp

**Comment by bl4ckscor3** [comment]
It seems you don't have SecurityCraft installed correctly, see line 45 in your log and so on:
> failed to connect: Channel of mod "SecurityCraft" failed to connect: This channel *is missing on the client* side, but required on the server!

Doublecheck the mods screen in the main menu.
