### ISSUE TITLE
Game Crash after limited use

### ISSUE THREAD

**Issue by HighlandHunter** [Geforce132/SecurityCraft#518]
### Issue description

It would occur randomly but I would basically get a game error in my world that would state the following:
The game crashed whilst rendering screen
Error: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1

This would be after a minute of loading back into my world. Each time I make a new world, it would be okay for a while and then suddenly it would crash once again.

### Minecraft version

1.20.6

### Forge/NeoForge version

20.6.119

### SecurityCraft version

v1.9.10.2

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/44DLxJJa

**Comment by bl4ckscor3** [comment]
This crash can happen sometimes when you hover over a Sonic Security System/Portable Tune Player in your inventory. You may be able to work around this if you enable advanced tooltips by pressing F3+H.
