### ISSUE TITLE
Crash when joining a world

### ISSUE THREAD

**Issue by emanuele246gi** [Geforce132/SecurityCraft#519]
### Issue description

The game crashed when I tried to join a world I already joined multiple times before, with this same version of SecurityCraft

### Steps to reproduce

1. Have the latest 1.21 version of the mod
2. Joining a world

### Minecraft version

1.21

### Forge/NeoForge version

21.0.66

### SecurityCraft version

v1.9.10-beta4

### Other relevant versions

(the mod's version is actually 1.9.10-beta6

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/bjEWqDHB

**Comment by bl4ckscor3** [comment]
Thank you! Recent NeoForge builds broke the mod, and I was actually already updating it but didn't have time to release a fixed version. It'll be released tomorrow at the latest.

**Comment by emanuele246gi** [comment]
Okay, thank you!
