### ISSUE TITLE
Mobs do not trigger mines

### ISSUE THREAD

**Issue by blockfever54** [Geforce132/SecurityCraft#52]

**Comment by bl4ckscor3** [comment]
Can you please go into as much detail as possible? What do you do? When do they work/not work? I'm assuming you're using 1.12.2 and v1.8.4.1.

**Comment by blockfever54** [comment]
So when an animal steps on a mine it doesn't blow up in my private world and I only use the latest version of both Minecraft version and security craft version

**Comment by bl4ckscor3** [comment]
Works for me. https://i.imgur.com/Or9Xmvs.mp4

**Comment by jorge-precich** [comment]
Is this configurable? To disable all mobs/entities besides players on a server? I've heard about CraftTweaker but I'm not sure if it can be changed there

**Comment by bl4ckscor3** [comment]
No, it is not.
Please do not necropost and use [our Discord](https://discord.gg/U8DvBAW) to receive support for the mod.
