### ISSUE TITLE
reinforcing blocks

### ISSUE THREAD

**Issue by WesleyGamepy** [Geforce132/SecurityCraft#524]
### Issue description

How to reinforce blocks from other mods?

### Minecraft version

1.20.1

### Forge/NeoForge version

47.3.3

### SecurityCraft version

v1.9.10

**Comment by bl4ckscor3** [comment]
3rd party mod support is not included in SecurityCraft. Adding reinforced blocks for other mods' blocks is the other mod's or an addon mod's job.

Also, this is an issue tracker, we use it to keep track of bug reports. For suggestions and questions about the mod, please use our Discord server.
