### ISSUE TITLE
Looking Glass and Security Craft

### ISSUE THREAD

**Issue by DarkMatterXCIX** [Geforce132/SecurityCraft#53]
Would u have any ideas as to why Looking Glass is not updated to 1.12 as of yet to use security systems in a building with security craft? I've been waiting for ages and would love a update, but then again it isn't your mod and you may not know, and is there a way around looking glass I guess to implement the same feature? or would u add that ability in the future to see your security cameras on a monitor without looking glass in the future?

**Comment by bl4ckscor3** [comment]
I have discussed this thoroughly tons of times with multiple people, privately and publicly. We have no control over what xCompWiz does with LookingGlass. We have attempted to update the mod, but did not manage to do it. There is an update available, and this one is currently being implemented in the 1.12 version of SecurityCraft. When it will be released is not known.
