### ISSUE TITLE
Modded Boats that Extend Boat.Type Prevent Game from Starting Correctly

### ISSUE THREAD

**Issue by quek04** [Geforce132/SecurityCraft#538]
### Issue description

As of NeoForge 21.0.132-beta, Boat.Type is extensible which allows modders to add their boat types to the vanilla boat entity, rather than having to make a separate modded boat entity. This causes a problem with loading the game with SecurityCraft and any other mod (such as The Undergarden) that adds to the Boat.Type enum because the game fails to create the model for the Security Sea Boat due to a colon being present in the texture path.
`Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: securitycraft:textures/entity/security_sea_boat/undergarden:grongle.png`
Tested in ATM10 modpack
[2024-08-22-1.log](https://github.com/user-attachments/files/16723869/2024-08-22-1.log)

### Steps to reproduce

1. Install SecurityCraft
2. Install Undergarden
3. Game fails to reach main menu due to above problem

### Minecraft version

1.21

### Forge/NeoForge version

21.1.23

### SecurityCraft version

v1.9.10-beta8

### Other relevant versions

Undergarden 0.8.21

**Comment by bl4ckscor3** [comment]
Thank you!
