### ISSUE TITLE
Minecraft crashes when i go past page 77 (i guess) in the security craft book

### ISSUE THREAD

**Issue by matesaman9910** [Geforce132/SecurityCraft#539]
### Issue description

when I go past page 77 (not sure if it is that page but it is close) Minecraft crashes

### Steps to reproduce

1. open the security craft book found in the security craft creative menu tab
2. change pages until you reach page +/- 77
3. Minecraft crashes

### Minecraft version

1.20.1

### Forge/NeoForge version

47.3.0

### SecurityCraft version

v1.9.10

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/bqVeY8rL

**Comment by bl4ckscor3** [comment]
Thanks for reporting! This will be fixed in the next update. Duplicate of #521
