### ISSUE TITLE
Reinforced Glass 1.7.10 

### ISSUE THREAD

**Issue by FR057F1R3** [Geforce132/SecurityCraft#54]
I noticed on a different topic that you have to use the U.B.R. to make reinforced glass. However you need reinforced glass to even make it. 
Pic 1
http://bit.ly/2thxnGm
Pic 2
http://bit.ly/2FUI4Bq

Is this a bug or am i missing something? This makes it so you can't get cameras unless you are in creative.

**Comment by bl4ckscor3** [comment]
Could you provide those images on a different host, please? The images do not load for me.

**Comment by FR057F1R3** [comment]
https://www.flickr.com/photos/73687704@N00/40638521431/in/dateposted-public/

https://www.flickr.com/photos/73687704@N00/39742724445/in/dateposted-public/

**Comment by bl4ckscor3** [comment]
Which version of SecurityCraft are you using? I can create Reinforced Glass with the Universal Block Reinforcer just fine by either using the GUI or breaking normal glass in the world.

**Comment by FR057F1R3** [comment]
That's what i'm saying. In the pictures i sent it shows that i cant even create the Universal Block Reinforcer without already having reinforced glass.

The version is 1.8.2.4 i got it off the Minecraft Curse site.

**Comment by FR057F1R3** [comment]
My mistake. -_- Seems the only one that was showing up in the search bar was the LvL 3. I had to open NEI to find the LvL 1.

**Comment by bl4ckscor3** [comment]
Oh, I misunderstood you. Yeah, there are three levels with varying amounts of durability.
There's also a newer version of SecurityCraft out, if you like you could update ;)
