### ISSUE TITLE
Crash ( saving world )

### ISSUE THREAD

**Issue by SmartStreamLabs** [Geforce132/SecurityCraft#540]
### Issue description

	- SecurityCraft (securitycraft) encountered an error while dispatching the net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent event

### Steps to reproduce

1 - Switch to creative mod.
2 - Open creative menu.
3 - Server crash.

### Minecraft version

1.21.1

### Forge/NeoForge version

1.21.1

### SecurityCraft version

v1.9.10-beta9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/SmartStreamLabs/dd92c91fa9394daa812071c14bf72c61

**Comment by bl4ckscor3** [comment]
Same crash as #528

**Comment by bl4ckscor3** [comment]
Is there a modpack available for this or the other one?

**Comment by bl4ckscor3** [comment]
I have no idea what the issue is, but something is seriously broken with some mod in there. The next update of SecurityCraft should fix it, but I can't say for certain without the information I asked for previously.
