### ISSUE TITLE
[1.20.1] Unpublished `null` fix when calling `BoatItem#getBoat`

### ISSUE THREAD

**Issue by MrCrayfish** [Geforce132/SecurityCraft#541]
### Issue description

I've had an issue (https://github.com/MrCrayfish/Framework/issues/24) reported to my library with a crash related to this mod. I've noticed after looking at your code that the issue is fixed (as shown here: https://github.com/Geforce132/SecurityCraft/commit/a88e69ba80842ef06738078a6035d88a617c413f), however a release containing the fix is yet to be published.

### Minecraft version

1.20.1

### Forge/NeoForge version

47.1.47

### SecurityCraft version

v1.9.10

**Comment by bl4ckscor3** [comment]
We're aware and will release a new version of the mod when ready.

**Comment by MrCrayfish** [comment]
Thank you for the timely reply. I'll let the OP on my issue know.
