### ISSUE TITLE
java.lang.IllegalArgumentException: The stack count must be 1

### ISSUE THREAD

**Issue by wuweidmw** [Geforce132/SecurityCraft#542]
### Issue description

[crash-2024-09-29_02.29.15-client.txt](https://github.com/user-attachments/files/17175869/crash-2024-09-29_02.29.15-client.txt)

### Steps to reproduce

I am using the Arclight server 1.21.1 with the latest build, and the mod is the latest beta version 9. The server crashes and exits directly after entering the server and opening the inventory.

### Minecraft version

1.21.1

### Forge/NeoForge version

21.1.54

### SecurityCraft version

v1.9.10-beta9

**Comment by bl4ckscor3** [comment]
I can't reproduce this on [Arclight build 1224](https://github.com/IzzelAliz/Arclight/actions/runs/10952674846). However I have a hunch as to why this issue may occur. If it is correct, you should be able to fix it by adding SecurityCraft's Lens item (`securitycraft:lens`) to the `minecraft:dyeable` item tag.

**Comment by wuweidmw** [comment]
thanks
