### ISSUE TITLE
Crash when opening Page 72 of manual

### ISSUE THREAD

**Issue by CreedOfLies** [Geforce132/SecurityCraft#543]
### Issue description

When reading through the security craft manual, attempting to turn to page 72 causes player's game to crash.

### Steps to reproduce

Obtain a security manual
Open it
Turn to page 72

### Minecraft version

1.20.1

### Forge/NeoForge version

47.3.6

### SecurityCraft version

v1.9.10

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/It2XQfO

**Comment by bl4ckscor3** [comment]
Please update the mod. This was fixed in v1.9.11.
Duplicate of #521
