### ISSUE TITLE
Trinity

### ISSUE THREAD

**Issue by DragonbornLevent** [Geforce132/SecurityCraft#548]
### Issue description

These 3 mods
![Screenshot_1](https://github.com/user-attachments/assets/f20fd3e4-3340-447e-bda6-33f10e722e1a)
Crashing only on dedicated servers, not lan multiplayer.
Removing one of them (no matter which one) solves the issue.
I tried no mixin version of the SecurityCraft but not solved the issue.

### Minecraft version

1.12.2

### Forge/NeoForge version

forge-1.12.2-14.23.5.2860

### SecurityCraft version

v1.9.11

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Su39BHsv

**Comment by bl4ckscor3** [comment]
This is a bug in the Double Slabs mod, please report this crash to them. They are calling a method that only exists client side on the server.
https://github.com/CJMinecraft01/DoubleSlabs/blob/1.12.x/src/main/java/cjminecraft/doubleslabs/common/items/VerticalSlabItem.java#L59
