### ISSUE TITLE
Security Cameras Crash The Game

### ISSUE THREAD

**Issue by AnonymousUser98** [Geforce132/SecurityCraft#551]
Everything works fine, except for security cameras. I can place one safely, but if I try to view it, the game crashes. This happens on all worlds.

**Minecraft Version:** 1.21.4
**Mod Loader:** neoforge-21.4.30-beta
**SecurityCraft Version:** v1.9.12-beta1

**Crash Report:** [crash-2024-12-20_11.25.42-client.txt](https://github.com/user-attachments/files/18215074/crash-2024-12-20_11.25.42-client.txt)
**Video of the crash:** https://app.weet.co/play/e1ac476f/create-video-tutorials-with-weet

**Screenshot of the "game crashed" message in Minecraft Launcher:
![LauncherCrashMessage](https://github.com/user-attachments/assets/eb767f45-96b0-4562-be0c-483ac87b0341)

**Comment by bl4ckscor3** [comment]
Thanks for reporting, I will release a second beta to address this.
By the way, I fixed not being able to create a normal issue on this repository :)
