### ISSUE TITLE
Instructions for setting the mod on my own server?

### ISSUE THREAD

**Issue by thbar** [Geforce132/SecurityCraft#56]
Hello - I've started a little custom server to play around with my sons & friends.

I currently have no mods enabled and was thinking about SecurityCraft.

Is it supposed to be installed on the server? On the client? Or on both?

Do you have some guidelines on how to install it on the server, if it should be installed there?

Happy to issue a PR with a bit of readme with my findings if you'd like.

Thanks in advance!

**Comment by bl4ckscor3** [comment]
SecurityCraft ist installed like any other Forge mod. Download and execute the latest installer from http://files.minecraftforge.net then run the forge jar file created in your server directory. After that simply drag and drop the SecurityCraft jar file that you downloaded on the mods folder within your server directory.

**Comment by thbar** [comment]
Great - thanks for the quick response! This is clear now, thanks.

If you're willing to, I can issue a PR later to add that information to the readme (just let me know if that's the case).

**Comment by bl4ckscor3** [comment]
I don't think that's necessary. There are a multitude of Client/Server mod installation guides for MinecraftForge out there.
