### ISSUE TITLE
Game Grash with Camera

### ISSUE THREAD

**Issue by lays24mc** [Geforce132/SecurityCraft#58]
I build a SC Camera and since this my game crashed everytime. Can you help me?

Forge 2697
MC 1.12.2
SecurityCraft 1.12.2-1.8.4.1
Crashlog: https://pastebin.com/5npcjeSX

**Comment by bl4ckscor3** [comment]
This is not caused by SecurityCraft. Whatever is in any of your worlds will not affect anything during startup. What happens when you remove SecurityCraft? What happens when you remove FoamFix? What happens if you give the game more RAM?
