### ISSUE TITLE
Request: The ability for more to break reinforced blocks

### ISSUE THREAD

**Issue by SupremeDraco** [Geforce132/SecurityCraft#61]
Hello,

I've been running a server with Security Craft for a while, and I've been wanting and wondering about a feature. Is it possible an item, or possibly a configuration option could be added that would allow for players, to be able to break Reinforced blocks placed by another? That would take away the "player's claim" to a block.

Some mods, like Better Builder Wands, unfortunately clash with this mod, making it so blocks placed by it are not registered as any player, and thus are unbreakable by all not in creative. I wouldn't want this feature added as a mandatory part of the mod, but as an optional config part.

**Comment by bl4ckscor3** [comment]
With the current infrastructure of how the mod is set up, having multiple owners for a block is not really implementable. I could add an option that allows anyone to claim a block without an owner, though, as a kind of workaround if you like.

**Comment by SupremeDraco** [comment]
That would be perfect, thank you so much! When it isn't owned for me, it's UUID will show up as "ownerUUID" in the Admin tool

**Comment by GrimReaper1214** [comment]
Was this Ever Implemented I'm trying to use world edit with the mod and need to claim the blocks it makes.

**Comment by AlephNLL** [comment]
How can you get a block to have no owner? I´ve tried modifying the nbt tags but blank counts as an owner and cant be claimed.

**Comment by bl4ckscor3** [comment]
You can't.
