### ISSUE TITLE
Wither breaks out.

### ISSUE THREAD

**Issue by spylor** [Geforce132/SecurityCraft#63]
The wither just broke out of my 6 by 6 reinforced box.

**Comment by spylor** [comment]
Latest securitycraft for latest stable forge 1.12.2

**Comment by bl4ckscor3** [comment]
Are you using v1.8.10? Just saying "latest" doesn't tell me anything, you might have missed an update.

**Comment by spylor** [comment]
Yes, that's the one. That's why I report it. I'll try it again and report back.
