### ISSUE TITLE
[1.7.10] Problem with Security Craft and LookingGlass

### ISSUE THREAD

**Issue by demycat** [Geforce132/SecurityCraft#64]
I have a problem with cameras, when I tie a tablet to the camera and put everything on the frame, but after a while I just have to crash the game, what is the reason and how to fix it?

Crafh log - [crash-2018-12-27_20.18.05-client.txt](https://github.com/Geforce132/SecurityCraft/files/2713063/crash-2018-12-27_20.18.05-client.txt)

**Comment by demycat** [comment]
SecurityCraft v1.8.10
LookingGlass 0.2.0.01

**Comment by bl4ckscor3** [comment]
Seems to be an issue with LookingGlass. Try having fewer active frames, or avoid pointing cameras at active frames. No guarantee.
