### ISSUE TITLE
Wither and Enderdragon still break securitycraft blocks.

### ISSUE THREAD

**Issue by spylor** [Geforce132/SecurityCraft#65]
Hi,

One of my players confirmed both creatures can still somehow break the blocks. I'm not sure how.

Using:
[1.12.2]+SecurityCraft+v1.8.10
forge-1.12.2-14.23.5.2768-universal

Maybe some other mod?
Has this been tested by a non-creative player in a room that spans multiple chunks?

I'm not sure why the updated didn't fix it for my server.

**Comment by bl4ckscor3** [comment]
Already fixed for the Wither, the Ender Dragon won't be supported. The fix will be out in the next version.
