### ISSUE TITLE
Client Crash when I get away from a camera.

### ISSUE THREAD

**Issue by iBisho** [Geforce132/SecurityCraft#66]
Whenever I get away from a camera (~80 blocks), the game crashes.

Here's the error: https://pastebin.com/YHtQMtZv

My Mods List is:
`Backpacks Mod 1.8;
Bloodmon 1.3;
CCC 1.8 & CCL 1.8;
CyclopsCore 1.8;
Damage Indicators 1.8;
Infernal Mobs 1.8;
IntegratedDynamics 1.8;
JourneyMap 1.8;
LotOMobs 1.8/1.2;
MCA 1.8;
MiniBosses 1.2.8;
NEI 1.8;
Optifine 1.8;
ProgressiveAutomation 1.8;
RadixCore 1.8;
SimpleCorn Mod 1.8;
Slimevoidlibrary 1.8;
ToolsCombine+ 1.8
and Wireless Redstone 1.8`

**Comment by bl4ckscor3** [comment]
Can you please post the complete crash report?

**Comment by iBisho** [comment]
@bl4ckscor3 Here it is: https://pastebin.com/tJ6JA35u

**Comment by bl4ckscor3** [comment]
A new version is available on CurseForge.
