### ISSUE TITLE
Secruity craft bug 

### ISSUE THREAD

**Issue by RealBrianOG** [Geforce132/SecurityCraft#70]
[https://gyazo.com/d1cd4f64e5f1402272025e6135749bfe](url)
[crash-2019-06-15_01.32.20-client.txt](https://github.com/Geforce132/SecurityCraft/files/3292770/crash-2019-06-15_01.32.20-client.txt)

Everytime I go in my server, which loaded in fine, I go in join and then crash back to Technic Launcher.
Don't know what to do help.

**Comment by bl4ckscor3** [comment]
Update SecurityCraft. The version you're using is multiple years old. 

Yes, the newest version also works on 1.7.10.

Download the following file, drop it in your mods folder and remove the old SecurityCraft file. https://minecraft.curseforge.com/projects/security-craft/files/2683639
