### ISSUE TITLE
Cant access multiple Cameras

### ISSUE THREAD

**Issue by AndysComing** [Geforce132/SecurityCraft#71]
So I play on a forge server hosted on my PC with friends. Before we had lookingglass installed, cameras would work at all, I would bind them, right click, then click #1 and it would just bug out, I would disappear from my friends prespective, but stay where I was in mine. I decided maybe it was not having lookingglass, so I installed it. Now, I can bind 1 camera at a time, and can only view in from my hands, not in a full-frame POV. I right click and nothing happens! Please help.

**Comment by bl4ckscor3** [comment]
If the server has LookingGlass installed but the client doesn't, unexpected behavior will happen. The fact that you can only view one camera with LookingGlass is intended.
