### ISSUE TITLE
Add more uses for the disguise module

### ISSUE THREAD

**Issue by darthvader45** [Geforce132/SecurityCraft#81]
I'd like to see more uses for the disguise module than just to make the keypad look like a secret bookcase switch.  Maybe allow for blocks like the card reader to take the texture of another block?  Would look cool for disguised bases.  Sure, there's Secret Rooms, but that mod isn't entirely secure.

**Comment by bl4ckscor3** [comment]
We definitely have that planned for more blocks for the next update!

**Comment by darthvader45** [comment]
Sounds awesome, will be looking forward to it!
