### ISSUE TITLE
Less Harsh Inventory Scanner

### ISSUE THREAD

**Issue by DarianLStephens** [Geforce132/SecurityCraft#82]
From what I've read, the Inventory Scanner will simply delete any specified items it detects.
I'd love to see an option that's less harsh, since simply having potentially-expensive items deleted is a bit much.

Perhaps the block could have an inventory, so the items could be collected? Sort of an automated confiscation, where the items can be delivered by hopper to a collection point outside the base.

Or, at least a config option to lock the Inventory Scanner in to redstone output mode, avoiding the issue entirely. That would at least still allow containment. If you can detect unauthorized items, simply don't allow the person in to your base until they remove them, and the scanner will make sure they keep their word.

**Comment by bl4ckscor3** [comment]
This is already in the mod. Right-click the Inventory Scanner with a Universal Block Modifier and insert a Storage Module into one of the slots. This makes it so the Inventory Scanner stores the items in an inventory that's added by the Storage Module (accessible through the Inventory Scanner's interface) instead of deleting them.

**Comment by DarianLStephens** [comment]
Oh, that's good to know. Would it still be possible to have a mod config option to enable that by default, or lock it out of delete mode?

**Comment by bl4ckscor3** [comment]
No. Just adding a Storage Module is not that hard, there's no need to remove delete mode.

**Comment by DarianLStephens** [comment]
Not everyone will listen when you tell them to do that, and it could be annoying to fix damage that occurs.
