### ISSUE TITLE
Account for Invisibility

### ISSUE THREAD

**Issue by DarianLStephens** [Geforce132/SecurityCraft#83]
One feature I'd love to see is for Invisibility to have an effect. For example, Motion-Activated Lights won't respond to entities with Invisibility, Sentry turrets won't shoot at invisible targets, retina scanners won't work, perhaps even Lasers could remain dormant when an invisible entity passes and Username Loggers won't log.

It's a shame when you go through preparation to try and breach someone's defenses and no matter how little they can see you, every block and machine can still detect you with no issues.

**Comment by bl4ckscor3** [comment]
Good idea, could be op though as an invisibility potion is not particularly hard to make.

**Comment by scmcgowen** [comment]
Make it a config option

**Comment by DarianLStephens** [comment]
Nice to see this in.
I'm not familiar with the update schedule, so should I expect this in 1.7.10 eventually or not?

**Comment by bl4ckscor3** [comment]
I'm afraid we have stopped updating the mod for 1.7.10 at the end of October last year. The only supported versions are 1.12.2, 1.14.4, and 1.15.2 at the moment.
