### ISSUE TITLE
[1.12.2] Removing a Password-protected Chest with a Universal Block Remover does not drop items using SpongeForge

### ISSUE THREAD

**Issue by Shalker96** [Geforce132/SecurityCraft#93]
Using:
Forge Version 1.12.2 - 14.23.5.2847
Sponge Version 1.12.2 - 2838-7.1.8
SecurityCraft mod version [1.12.2]+SecurityCraft+v1.8.15

Steps to reproduce:

Whenever you right click a password-protected chest with the item Universal Block Remover the items stored inside the chest are lost and an error appears in the console of the server:

https://gist.github.com/Shalker96/407db0365a118f1b6a14ed6290b1e023

I tried different versions of the mod and of Sponge but the error keeps happening.

I don't know if you support Sponge but if you would be able to fix this I would gladly appreciate it!

**Comment by bl4ckscor3** [comment]
We don't officially support SpongeForge, and I've already tried fixing the issue. Not sure what causes it. I'll leave this open just in case.

**Comment by gununakuna** [comment]
I just create a pull request #97, with this bu fixed.
